### ISSUE TITLE
Allow alternative requirements

### ISSUE THREAD

**Issue by Natureshadow** [pypa/setuptools#1000]
I recently hit an issue when requiring a module for MIME magic detection. There are the file-magic and the magic distribution. Because the developers are idiots, both distributions contain the magic package, with entirely different APIs.

While I could detect this in my code and generate matching wrapper code, I wanted to also declare a requirement in setup.py that can be satisfied by botI came up with the following snippet: https://gist.github.com/Natureshadow/92f30ce650682a638b0bc75e6d54e8b4

The idea is to check all provided alternatives, and if one is installed, return that, and if not, return the first, which has highest precedence (the same logic used by APT).

You can just add a call to `requires_alternative("file-magic", "magic")` to the `install_requires` list.

Feel free to incorporate this into setuptools; if the implementation is not on par with your code, please take this as a feature request.

**Comment by jaraco** [comment]
What you're describing here needs to be addressed at a higher level, as a PEP or at least discussion within distutils-sig. It's not sufficient to have supply a `requires_alternative()` to an `install_requires` directive because that directive is run when setup.py is invoked, which happens during builds, including wheel (binary) builds. These builds would then resolve their requirements relative to the build environment and not the user's target environment.

What you need instead is a specification on how alternative requirements might be declared and guidance on how builders and installers should deal with such requirements. I think there are already efforts underway in this vein, not only dealing with alternatives, but also dealing with packages that supersede others or satisfy a requirement of another (e.g. Pillow satisfying PIL).

As it stands, this request isn't actionable here. Thanks for the suggestion and do feel free to pursue this with the community.
