### ISSUE TITLE
Documentation on configuring setup using setup.cfg incomplete

### ISSUE THREAD

**Issue by rudolphfroger** [pypa/setuptools#1006]
The documentation on the options to be used in setup.cfg is quite clear. However instruction seem to be missing on how to create a package by using just a setup.cfg en no setup.py.

https://setuptools.readthedocs.io/en/latest/setuptools.html#configuring-setup-using-setup-cfg-files

**Comment by jaraco** [comment]
@rudolphfroger: I think you still have to use setup.py but you can omit many (all?) of the parameters. Also, since the feature was only added in [30.3.0](http://setuptools.readthedocs.io/en/latest/history.html#v30-3-0), and if you were to rely on the feature entirely, your package would only be installable with those later releases of setuptools.

@idlesign Do you have anything to add or recommend?

**Comment by idlesign** [comment]
Yes `setup.py` is still required as the entry point. Bare minimum is to call `setup()`.

If you init venv, pip ensures you have latest setuptools, so you packages will install there. 
In other cases you'll propably need  `ez_setup.py` to update `setuptools`.

@jaraco I wonder whether there's already some magic to make the following line to do the trick `ez_setup.py` does:
```
setup(setup_requires=['setuptools>=30.4.0'])
```

**Comment by jaraco** [comment]
Don't try `setup_requires` for setuptools itself. Especially since setuptools 34, it doesn't support installing itself, so isn't a solution. Also ez_setup.py is deprecated as well. Best just to require that setuptools meets the minimum version (perhaps with `assert setuptools.__version__ > '30.3'`) thus forcing the user to upgrade before installing your package, or wait for PEP 518 support to land in pip (at which point you can declare a minimum dependency on setuptools).

**Comment by rudolphfroger** [comment]
Thanks for your answers. Would be a good idea to document that setup.py is still required with at least an empty setup() call. I had to find out by reading setuptools source code.

**Comment by jaraco** [comment]
Seems reasonable. Feel free to provide a pull request.

**Comment by idlesign** [comment]
A note on version date and number when this feature has been added should be useful too.

@rudolphfroger I'd be able to improve docs in a few days, or you can do it yourself.
