### ISSUE TITLE
setup.py test -s test/filename.py

### ISSUE THREAD

**Issue by techtonik** [pypa/setuptools#1035]
Currently, `setup.py test -s test/filename.py` fails with `ImportError: Import by filename is not supported.`. But `setup.py test -s test.filename` works okay. What makes supporting this case difficult or impossible?

**Comment by jaraco** [comment]
Zen of Python says there should be (preferably) one best way to do things. My guess is `test.filename` is the one best way. `-s` is short for `--test-suite` and the example in the command-line is `some_module.test_suite`, so it seems to be referring to a name in a module, which in Python terminology is best written as indicated.

**Comment by techtonik** [comment]
@jaraco two issues here;

1. which is the best way to specifying test case in command line
   1.1 use bash completion to get to the filename
   1.2 type in all the dotted path by hand manually
2. `--test-suite` doesn't run suites anymore, see #1034

**Comment by jaraco** [comment]
> which is the best way? 

1.2, because it's incongruent to solicit the module by file name when when the whole module is desired, but to require the dotted notation when a suite in the module is specified. You wouldn't want to accept "path/module.py.test_suite" would you? Plus, there are issues with sys.path. If the suite is in "tests.module", but "tests" is found as "src/tests", should one specify "src/tests/module.py" or "tests/module.py" (and if the latter, then tab completion is no help).

I'd like to deprecate `setup.py test` and instead direct users to `tox` or `rwt` or simply `venv`+`unittest` for running tests and let setuptools get out of the business of installing packages. Therefore, I'm disinclined to invest the effort in honing the behavior here (and especially in expanding its scope).

**Comment by techtonik** [comment]
>  You wouldn't want to accept "path/module.py.test_suite" would you?

`path/module.py:test_suite`

> If the suite is in "tests.module", but "tests" is found as "src/tests", should one specify "src/tests/module.py" or "tests/module.py" (and if the latter, then tab completion is no help).

In this case how `setup.py` detects the correct `sys.path`? It is not `src/` by default, so the same rule apply - one specifies `src/tests/module.py` and `setup.py` strips the common prefix.

> I'd like to deprecate setup.py test and instead direct users to ...

No need to complicate things. There should be a single intuitive way to run tests out of the box - like with `setup.py this` - and and opt-in for `tox`, `rwt` etc. for those who need to complicate things for some reason.
