### ISSUE TITLE
upload_docs raises AttributeError with Sphinx 1.6

### ISSUE THREAD

**Issue by mitya57** [pypa/setuptools#1060]
In Sphinx 1.6, `builder_target_dir` was replaced with `builder_target_dirs`, see sphinx-doc/sphinx@2afa0b6627f7e5afb188d5a60c8c4767f6250774 and sphinx-doc/sphinx#3476.

This causes an AttributeError in setuptools:

```pytb
Traceback (most recent call last):
  File "setup.py", line 67, in <module>
    setup(**setup_args)
  File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.5/distutils/dist.py", line 973, in run_command
    cmd_obj.ensure_finalized()
  File "/usr/lib/python3.5/distutils/cmd.py", line 107, in ensure_finalized
    self.finalize_options()
  File "/home/dmitry/.local/lib/python3.5/site-packages/setuptools/command/upload_docs.py", line 65, in finalize_options
    self.target_dir = build_sphinx.builder_target_dir
  File "/usr/lib/python3.5/distutils/cmd.py", line 103, in __getattr__
    raise AttributeError(attr)
AttributeError: builder_target_dir
```

**Comment by pganssle** [comment]
I'm guessing that, going forward, we don't want people using `python setup.py upload_docs`, but I'm not sure what the replacement for it is.

I am not really sure how the API changes between `builder_target_dir` and `builder_target_dirs`. At first I thought it was a trivial rename, but I guess now this returns a list instead of a path, so I'm not sure what other effects this has.

One thing that disturbs me is that this does not seem to have broken our test suite, so I think to start we need some tests for this, even if it's just so that we can start safely removing it.

**Comment by webknjaz** [comment]
AFAIU pythonhosted.org is read-only now and this command doesn't make sense anymore. So the correct course of action would be removing it from https://github.com/pypa/setuptools/blob/main/setuptools/command/upload_docs.py and any other places.

**Comment by melissa-kun-li** [comment]
@webknjaz I believe we can keep the `upload_docs` command because v36.1.0 restored support for `upload_docs` for sites other than PyPi. https://github.com/pypa/setuptools/blob/e1ffc2abbae4f2aa78dd09ee9827d754b7702b7b/CHANGES.rst#v3610. "Only warehouse is dropping support, but services like devpi continue to support docs built by setuptools' plugins."
