### ISSUE TITLE
Re-add hashsum check to ez_setup.py

### ISSUE THREAD

**Issue by ghost** [pypa/setuptools#11]
Originally reported by: **tiran (Bitbucket: [tiran](http://bitbucket.org/tiran), GitHub: [tiran](http://github.com/tiran))**

---

For setuptools 0.6 ez_setup.py used to validate the downloaded file against a table of known hashsums. I wonder ... why was this feature removed? It adds a simple layer of security and prevents broken downloads, too.

Python 2.4+ support SHA-1, 2.5+ SHA-2 family (sha224 to sha512). Since setuptools still supports Python 2.4 we have to use SHA-1. It's broken but not as broken as MD5. You can limit the possibility of a collision attack if you include and verify the file size, too.

---
- Bitbucket: https://bitbucket.org/pypa/setuptools/issue/11

**Comment by abravalheri** [comment]
Since `ez_setup` is deprecated (and no longer used) in setuptools, I think we can safely close this issue now.

I also assume that the regular (modern) means of installation (`pip` or OS/distribution specific package manager/software store) is already checking for checksums when downloading setuptools, so the security concern is already handled.

If any of the users originally involved in this discussion would like to re-open the issue, please let me know and I will gladly do it.
