### ISSUE TITLE
include_package_data=False reads MANIFEST.in in sdist command

### ISSUE THREAD

**Issue by ghost** [pypa/setuptools#110]
Originally reported by: **ostcar (Bitbucket: [ostcar](http://bitbucket.org/ostcar), GitHub: [ostcar](http://github.com/ostcar))**

---

Your documentation defines, that the MANIFEST.in is only parsed, if include_package_data is set to True. So I suppose it is not read if include_package_data is set to False. That works fine for the 'build' or 'bdist' command. But the sdist commands includes parses the MANIFEST.in even if include_package_data is set to False.

This could probably be fixed in the method `commands.egg_info.manifest_maker.run`
by changing the line `if os.path.exists(self.template)` to `if os.path.exists(self.template) and self.distribution.include_package_data:`

---
- Bitbucket: https://bitbucket.org/pypa/setuptools/issue/110

**Comment by tuukkamustonen** [comment]
@ostcar Isn't `MANIFEST.in` supposed to be always read when building `sdist` (but not when building wheel or egg). So this should be just about clarifying the documentation (that MANIFEST.in is read only when `include_package_data` is enabled _or_ source distribution is being built)?

**Comment by ostcar** [comment]
It was a long time ago, that I opened that ticket. I can not remember what that situation was.

For all I care the ticket can be closed.

**Comment by abravalheri** [comment]
Does this ticket still make sense?

According to the latest interaction in #2835, setuptools will always "act like" building a sdist and then it will create a wheel based on that.

Since `MANIFEST.in` is always supposed to be read when building sdist, (as put by @tuukkamustonen), it will should also be read when creating a wheel.

(I also consider that `bdist` and `egg`s are deprecated)

**Comment by ostcar** [comment]
I have no idea. It was a very long time that I opened this issue. It's ok for if you close it.
