### ISSUE TITLE
windows manifests

### ISSUE THREAD

**Issue by ghost** [pypa/setuptools#119]
Originally reported by: **guyroz (Bitbucket: [guyroz](http://bitbucket.org/guyroz), GitHub: Unknown)**

---

from http://msdn.microsoft.com/en-us/library/windows/desktop/ms724451(v=vs.85).aspx:

> Applications not manifested for Windows 8.1 will return the Windows 8 OS version value (6.2). Once an application is manifested for a given operating system version, GetVersionEx will always return the version that the application is manifested for in future releases. To manifest your applications for Windows 8.1 please refer to Targeting your application for Windows 8.1.

With this change in Widows 8.1, it is imperative for setuptools to generate manifests for the executables it writes for the console/gui scripts.

---
- Bitbucket: https://bitbucket.org/pypa/setuptools/issue/119

**Comment by abravalheri** [comment]
Is it correct to assume that the problem here just concern the (gui-)script wrappers being generated and not the other files?

If that is the case, I think currently `pip` is the tool creating these wrappers (since running `python setup.py install` is no longer recommended)... We could raise this issue with pip, but considering the [current market share for Windows 8.1 seems to be very small](https://gs.statcounter.com/os-version-market-share/windows/desktop/worldwide/) and that this issue never got much traction, maybe the best would be closing this issue.

**Comment by abravalheri** [comment]
I will go ahead and close this issue, since I believe (gui-)script wrappers are now being handled by `pip` (and therefore there is no action point from the setuptools perspective). But I am more than happy to re-open it if my understanding is wrong...
