### ISSUE TITLE
Add icon to entry_points and gui_scripts

### ISSUE THREAD

**Issue by fredrikaverpil** [pypa/setuptools#1245]
I am creating executables by specifying `entry_points` and `gui_scripts` in my `setup.py`.
I haven't figured out how I can add icons to these executables other than manually doing so after having pip-installed my wheel. It would be very useful (and nice) to be able to specify an .ico file for each executable (regardless of using GUI scripts or console scripts).

  Here's a related SO question with no answers: https://stackoverflow.com/questions/42166105/how-to-add-an-icon-to-an-entry-points-for-python-pip-generated-executable

**Comment by albertosottile** [comment]
Any news on this?

**Comment by Parvez-Khan-1** [comment]
Any update on this??

**Comment by abravalheri** [comment]
Hi @fredrikaverpil, thank you for bringing this up. My understanding is that script/entry-point wrappers are generated by the package installer, not the backend.

I am also under the impression that, currently when you `pip install` a package, `pip` will be the software generating those executable wrappers around `console_scripts` and `gui_scripts` entrypoints.

**Comment by abravalheri** [comment]
To support this feature, (which in my view is outside of the scope of the setuptools project) it would be necessary to coordinate some sort of metadata (e.g. in the core metadata specification) with the package installer (e.g. pip).

So I think the best place to start a discussion would be in https://discuss.python.org/c/packaging.

---

I will close this issue by now since I don't see any action point that could be immediately taken by setuptools.

If at some point the community agrees on how to implement the features in the ecosystem and it needs collaboration with setuptools, please feel free to open another issue.
