### ISSUE TITLE
resource_listdir() can yield empty string in setuptools==38.2.5

### ISSUE THREAD

**Issue by sirosen** [pypa/setuptools#1268]
I'm not clear enough on the defined/expected behavior for this call to know that this is definitely a bug.
It caused buggy behavior in client code, and I think it is a setuptools bug.

[`nose2`](https://github.com/nose-devs/nose2) has a [segment of code for loading tests from a zipped egg](https://github.com/nose-devs/nose2/blob/804b78b922bbe064efda4864eadf06e4da279f3a/nose2/plugins/loader/eggdiscovery.py#L51-L68). In its simplest form, it goes something like this:
```python
def find_tests_in_egg_dir(rel_path, dist):
    # blah blah blah, handle some base cases
    for path in dist.resource_listdir(rel_path):
        entry_path = os.path.join(rel_path, path)
        if not dist.resource_isdir(entry_path):
            # other base case
        else:
            for test in find_tests_in_egg_dir(entry_path, dist):
                yield test
```

Under `setuptools>=38.2.5` we can have cases where `resource_listdir` yields the empty string and we go into an infinite recursive loop.
I think #1232 is probably the cause (since that's what was released at that time).

In case it's useful, [here's my initial investigation into the `nose2` bug](https://github.com/nose-devs/nose2/issues/383), and [here's the patch I submitted there](https://github.com/nose-devs/nose2/pull/384).

I'm happy to help dig into this if it's useful, but I've never contributed to setuptools before so I don't have relevant proficiency.

**Comment by jaraco** [comment]
@duggelz Can you investigate?

**Comment by duggelz** [comment]
I will take a look

**Comment by duggelz** [comment]
The behavior of `resource_listdir()` in eggs is kind of surprising: It returns a list of filenames, and one of those filenames is the empty string.  From what I can tell, it's had this behavior since at least setuptools 5.0.

My change in #1232 doesn't change what `resource_listdir()` returns, but it does cause `resources_isdir('foo/')` to return True where previously it returned False for anything ending with a backslash.

The behavior of these functions is fairly underspecified, so I'm not sure what qualifies as feature or bug at this point.  The behavior of the egg and zip-based resources is supposed to match the behavior of filesystem based resources, and `os.path.isdir('foo/')` does return True.

If you want to revert my change #1232, that would be reasonable.  If you want me to change the behavior of `resource_listdir` to be a little less surprising, I could that instead, but there is undoubtedly tons of code that expects the old behavior.

**Comment by sirosen** [comment]
> [the change causes] `resources_isdir('foo/')` to return True where previously it returned False for anything ending with a backslash.

When phrased that way, it sounds like `resources_isdir` had a bug, and `nose2` happened to be relying on that bug. I can't see any way of interpreting #1232 as anything short of a bugfix.

> The behavior of `resource_listdir()` in eggs is kind of surprising: It returns a list of filenames, and one of those filenames is the empty string. From what I can tell, it's had this behavior since at least setuptools 5.0.
> ...
>  If you want me to change the behavior of `resource_listdir` to be a little less surprising, I could that instead, but there is undoubtedly tons of code that expects the old behavior.

Yeah, that definitely qualifies as surprising. I'd call it a bug.

While I'm loathe to advocate changing something that will cause breakage downstream, this is probably already broken for a lot of packages which don't know it.
A lot of maintainers probably assume that `resource_listdir` behaves the same on zipped and unzipped eggs, and don't explicitly test both cases.

Lots of people probably `pip install -U setuptools` in their builds, but IMO that doesn't make it right to never fix this.
I think the best thing to do is to change it and release it as a major version update to setuptools (`39.0.0`). Optionally, there can be a deprecation+warning cycle for the current behavior, but I'm not sure that's worth the effort for a moderately obscure bug.

**Comment by sirosen** [comment]
A quick review of this issue suggests to me that it should be summarily closed as stale.
