### ISSUE TITLE
Issue related to setup_requires (since #1150)

### ISSUE THREAD

**Issue by astrofrog** [pypa/setuptools#1273]
For one of the projects I work on (Astropy) we have been making use of code that can be simplified to:

```python
import pkg_resources
from setuptools import Distribution


class CustomDistribution(Distribution):
    def get_option_dict(self, command_name):
        opts = Distribution.get_option_dict(self, command_name)
        if command_name == 'easy_install':
            opts['find_links'] = ('setup script', ['astropy-helpers-2.0.3.tar.gz'])
            opts['allow_hosts'] = ('setup script', '')
        return opts


CustomDistribution(attrs={'setup_requires': ['astropy-helpers']})

print(pkg_resources.working_set.by_key.get('astropy-helpers'))
```

This requires the following tar file to run: [astropy-helpers-2.0.3.tar.gz](https://files.pythonhosted.org/packages/46/49/4882dc7b3fc1c47d481db229777a82e74751e6a1f0a4af90d9df5285bb21/astropy-helpers-2.0.3.tar.gz)

Before https://github.com/pypa/setuptools/pull/1150, this would cause astropy-helpers to be installed to the ``.eggs`` directory using the local tar file, but since the changes in https://github.com/pypa/setuptools/pull/1150 this no longer works (in the above example, the last line used to return a distribution object, but astropy-helpers is now no longer in the ``working_set`` so this returns ``None``)

Is this an unintended consequence of https://github.com/pypa/setuptools/pull/1150, or should we update our code above for it to continue working?

cc @benoit-pierre @jaraco

**Comment by benoit-pierre** [comment]
Requirements in `setup_requires` are now installed by `setup` before creating the `Distribution` object, not in the `Distribution.__init__` phase anymore. Why don't you use `setup.cfg` and let `setup` do it for you? Is it because you need `astropy-helpers` available before calling `setup`? In which case you can use `fetch_build_eggs` directly (see [example](https://github.com/openstenoproject/plover/pull/881/files#diff-9a5b183b4aaeeafcb19ff0cedaeb440fR163)).

**Comment by astrofrog** [comment]
@benoit-pierre - ok, thanks for the clarification, I'll switch to calling ``fetch_build_eggs`` directly instead. We do need astropy-helpers to be available before calling ``setup``.
