### ISSUE TITLE
(Module) file permissions not set correctly upon install

### ISSUE THREAD

**Issue by tovrstra** [pypa/setuptools#1283]
When installing a python package system-wide with setuptools, using `zip_safe=False`, on Linux, the file permissions are not updated to make them world-readable. This effectively breaks the installation.

This is an example source tree:

```
.
├── [-rw-r-----]  setup.py
└── [drwxr-x---]  toyproject
    ├── [-rw-r-----]  ball.py
    └── [-rw-r-----]  __init__.py
```

Note that in the source tree, I do not allow other users to see my files. This is intentional.

My `setup.py` contains:

```python
#!/usr/bin/env python
#from distutils.core import setup
from setuptools import setup
setup(
    name="toyproject",
    package_dir={'toyproject': 'toyproject'},
    packages=['toyproject'],
    zip_safe=False,
)
```

The file `__init__.py` is empty and `ball.py` contains:

```python
from __future__ import print_function
print("ball")
```

After running `sudo python setup.py install` and changing to a different directory, I cannot import `toyproject.ball`:

```
Python 2.7.14 (default, Feb 17 2018, 10:42:17) 
[GCC 7.3.1 20180130 (Red Hat 7.3.1-2)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import toyproject.ball
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named ball
>>> 
```

The reason is that the permissions and ownerships of the installed files make it impossible to import the `ball` module:

```
/usr/lib/python2.7/site-packages/toyproject-0.0.0-py2.7.egg
├── [drwxr-xr-x root     root    ]  EGG-INFO
│   ├── [-rw-r----- root     root    ]  dependency_links.txt
│   ├── [-rw-r----- root     root    ]  not-zip-safe
│   ├── [-rw-r----- root     root    ]  PKG-INFO
│   ├── [-rw-r----- root     root    ]  SOURCES.txt
│   └── [-rw-r----- root     root    ]  top_level.txt
└── [drwxr-xr-x root     root    ]  toyproject
    ├── [-rw-r----- root     root    ]  ball.py
    ├── [-rw-r----- root     root    ]  ball.pyc
    ├── [-rw-r----- root     root    ]  __init__.py
    └── [-rw-r----- root     root    ]  __init__.pyc
```

I would have expected the following permissions:

```
/usr/lib/python2.7/site-packages/toyproject-0.0.0-py2.7.egg
├── [drwxr-xr-x root     root    ]  EGG-INFO
│   ├── [-rw-r--r-- root     root    ]  dependency_links.txt
│   ├── [-rw-r--r-- root     root    ]  not-zip-safe
│   ├── [-rw-r--r-- root     root    ]  PKG-INFO
│   ├── [-rw-r--r-- root     root    ]  SOURCES.txt
│   └── [-rw-r--r-- root     root    ]  top_level.txt
└── [drwxr-xr-x root     root    ]  toyproject
    ├── [-rw-r--r-- root     root    ]  ball.py
    ├── [-rw-r--r-- root     root    ]  ball.pyc
    ├── [-rw-r--r-- root     root    ]  __init__.py
    └── [-rw-r--r-- root     root    ]  __init__.pyc
```

Setting these permissions manually fixes the problem, but it is obviously inconvenient that setuptools does not take care of this.

There are other ways to solve this, but each of them has its own set of limitations:

- Use distutils. (not ok because I need other setuptools features)
- Use ` zip_safe=True`. (not ok in several of my projects, e.g. because then nosetests cannot discover unit tests.)

Anyway, my reasons for using `zip_safe=False` are not so relevant.

**Comment by jaraco** [comment]
Granted, you shouldn't have to rely on distutils or zip_safe.

I've been installing packages using Setuptools on Unix with and without sudo for some time now and I've never encountered this situation. There's something about your environment that's forcing this unwanted behavior.

We could do more investigation to detect how and where the permissions aren't being set as desired. The functionality you're using, however, is largely deprecated.

I think the best way forward may be to explore what happens if using pip to install the package. What happens if you use `sudo pip install .` (or maybe `sudo python -m pip install .`) instead of `sudo python setup.py install`? Or alternately, `pip wheel .` followed by `pip install *.whl`?

If either of those approaches produce the outcome you would expect, I'd recommend using that instead and forget about setup.py install. Let me know how it goes.

**Comment by jaraco** [comment]
Closed due to inactivity.
