### ISSUE TITLE
Change in behavior for 'requires.txt' in 36.2.0

### ISSUE THREAD

**Issue by stephenfin** [pypa/setuptools#1307]
It seems `setuptools` v36.2.0 changed the behavior of `{package}.egg-info/requires.txt` generation. I suspect this was introduced by #1081. We saw this in `pbr` as it [broke our unit tests](https://launchpad.net/bugs/1758877). We have since [fixed this](https://review.openstack.org/#/c/556481/), but ideally this behavior shouldn't have changed in a *minor* release.

I don't want to revert that change but I also would like this behavior to remain as consistent as possible (for as long as `requires.txt` files are used, anyway). I can work on a test to ensure this is the case.

**Comment by pganssle** [comment]
@stephenfin Thanks for the PR adding a test for that.

**Comment by benoit-pierre** [comment]
I disagree, but it's already merged... There's no guarantee of a specific order, that's an implementation detail.

**Comment by pganssle** [comment]
@benoit-pierre Oh, I agree with that sentiment mind you, but setuptools cuts major versions so frequently that I didn't think it was really worth arguing the point.

I mainly merged the PR because I didn't see any other tests that actually test the behavior of multiple `python_requires` requirements, and I didn't think it would hurt to know if the particular behavior is changing.

**Comment by stephenfin** [comment]
> I disagree, but it's already merged... There's no guarantee of a specific order, that's an implementation detail.

In hindsight, I also agree. [dhellmann's fix for this in pbr](https://review.openstack.org/#/c/555808/) was far more elegant than mine. However, as @pganssle notes, this tests something that wasn't already tests so eh, what harm :smile:

**Comment by jaraco** [comment]
Well, the harm is this - if it's an implementation detail, something Setuptools does not wish to guarantee, then adding a test for it is confusing. If the behavior is meant to be guaranteed, then it should have a test, but if it's a detail that's subject to change, it probably shouldn't have a test.

In fact, if Setuptools' declared behavior is that the order of the details is not guaranteed, then the tests are in fact wrong and should instead assert that the values are present in any order (and not in a specific order).

Most importantly, this decision shouldn't be made lightly, locking in an implementation detail, simply because that's the current expectation.

It's not even clear to me that pbr should have had any expectation that there was deterministic ordering of these values. Just because their tests relied on it doesn't mean that it was a regression in Setuptools or that any package was right to rely on that behavior.

And since the guaranteed interface of Setuptools isn't rigorously defined, there may be no good answer to that matter, so it makes sense herein to rigorously define it one way or another. In the past, I would have leaned toward not providing deterministically-ordered output, but several tickets in the project since have specifically been working toward generating deterministic builds, suggesting this PR does make sense.

**Comment by pganssle** [comment]
@jaraco Sorry about the quick merge without discussion there, I probably should have realized it might be controversial since I *also* didn't think we should guarantee the interface.

That said, I think it's a good idea to have a test like this, which includes multiple metadata attributes. Would it be better if we modified the test so that it doesn't test that the output is re-ordered? (e.g. change it to the input order)

I am not sure there's a good way to both test this and convey that what order these things show up in is an implementation detail.

> In the past, I would have leaned toward not providing deterministically-ordered output, but several tickets in the project since have specifically been working toward generating deterministic builds, suggesting this PR does make sense.

With regards to this, I think there's a difference between guaranteeing deterministically-ordered output and guaranteeing what that ordering will be. Reproducible builds should only care that given a set of inputs, the outputs will be the same, not that given a set of inputs, there's a trivial algorithm for determining the outputs (e.g. "the outputs are always sorted").  That's why I'm a bit on the fence about #1305.

**Comment by benoit-pierre** [comment]
@pganssle: I was going to say the same thing about build order vs stable output.

**Comment by pganssle** [comment]
@benoit-pierre I guess the other side of this is that guaranteeing a specific order is probably in many ways easier than guaranteeing that the order is stable (since we can always re-order the outputs at the very end), and it's much easier to test for guaranteed-order than it is to test for stable-order.

@jaraco If you'd like I'm happy to write a new test that checks that this works in some order-independent way, though I'm warming up to the idea of "we should sort anything where we weren't guaranteeing order", for purposes of build reproducibility, in which case this test seems fine.

**Comment by benoit-pierre** [comment]
@pganssle: yes, it's easier, I have no problem with us implementing/testing it that way. The issue is with other projects doing the same.
