### ISSUE TITLE
UnicodeDecodeError when long_description is a file in a different encoding

### ISSUE THREAD

**Issue by lgh2** [pypa/setuptools#1311]
I was doing some testing the other day, and tried using a file in ISO/IEC 8859 encoding as the `long_description`.  I got the following error message: 

```
File "setup.py", line 9, in <module>
    long_description = f.read()
  File "/home/user/Python/Readme_GFM/venv/lib/python3.6/codecs.py", line 698, in read
    return self.reader.read(size)
  File "/home/user/Python/Readme_GFM/venv/lib/python3.6/codecs.py", line 501, in read
    newchars, decodedbytes = self.decode(data, self.errors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc2 in position 0: invalid continuation byte
```
I did a little research, and found that a fix for this was submitted [here](https://github.com/pypa/setuptools/pull/537/files), but it seems that the fix was removed [here](https://github.com/pypa/setuptools/pull/802/files#diff-81de4a30a55fcc3fb944f8387ea9ec94).  I'm not certain why it was removed.

My understanding is that [UTF-8 is the only text encoding supported in package metadata](https://packaging.python.org/specifications/core-metadata/?highlight=encoding#description-content-type-optional), but I may be wrong about this, especially since setuptools still has to support Python 2. 

I think that trapping the error and letting users know that their file is not in UTF-8 would be helpful. I'm happy to submit a patch for this, if you would like.

**Comment by pganssle** [comment]
@lgh2 That doesn't look like an error on the `setuptools` side, unless I'm reading the traceback wrong. Looks like the problem is when you call `f.read()`, you're failing to decode it.

I'm pretty sure the change you mentioned in the PKG-INFO writer would never have been hit by this anyway, but it's not clear what good it would do in this case anyway. The traceback you have still indicates pretty clearly where the problem was.

In fact, the [second change you mention](https://github.com/pypa/setuptools/pull/802/files#diff-81de4a30a55fcc3fb944f8387ea9ec94R1865) actually seems to make this *more lenient*. Now instead of just re-raising the error, the read will succeed (and write something with a bunch of error characters and/or [mojibake](https://en.wikipedia.org/wiki/Mojibake) in it, presumably) but warn the user rather than raising an error. This seems like a better behavior to me, since you probably don't want the whole operation blocked entirely just because someone sends some non-UTF-8 metadata.
