### ISSUE TITLE
Upload without password

### ISSUE THREAD

**Issue by floqqi** [pypa/setuptools#1323]
Currently it it not possible to upload using `setup.py upload -r myownpypi` without using an username + password in `.pypirc` (there is no auth required). Blank fields for `username` and `password` causes the script to ask for password. Shouldn't it prompt for a password first when the PyPi-Server reponds with `401 Unauthorized`?

**Comment by jaraco** [comment]
The password handling [happens in distutils](https://github.com/python/cpython/blob/04e82934659487ecae76bf4a2db7f92c8dbe0d25/Lib/distutils/command/upload.py#L173). The username and password are passed unconditionally. Setuptools [supplements this behavior](https://github.com/pypa/setuptools/blob/0e62448b2674b3b321be28496b87362bc76ebcd1/setuptools/command/upload.py#L11-L42) to allow the username/password to be solicited at runtime (from keyring or prompt). And an empty value is considered the same as a None value.

I'm not sure an empty value would be the appropriate signal for (authentication not needed). Regardless, why not simply supply "anything" for the username and password (in .pypirc)? Does that satisfy your use case? It's slightly clumsy, but not much more so that allowing passing of empty values.

**Comment by jaraco** [comment]
Also, I should say, the `upload` command is deprecated in favor of the [twine](https://pypi.org/project/twine). Have you tried Twine? I don't know if it has the behavior you seek, but if it doesn't, that's the place we'd support such a use case.

**Comment by johnthagen** [comment]
Related to #554. This is not working for me in `setuptools 0.54.1` either. [`twine upload`](https://twine.readthedocs.io/en/latest/#twine-upload) does work.

One of the reasons people might be lead down this path is that tools such as [Artifactory](https://jfrog.com/artifactory/) prescribe using `python setup.py upload` rather than `twine`.

**Comment by jaraco** [comment]
> One of the reasons people might be lead down this path is that tools such as [Artifactory](https://jfrog.com/artifactory/) prescribe using `python setup.py upload` rather than `twine`.

Then Artifactory should adapt.
