### ISSUE TITLE
Time for a new release?

### ISSUE THREAD

**Issue by jaraco** [pypa/setuptools#1339]
I see we have quite a few commits pending in master since the last release.

I'd like to allow the other maintainers to cut the release, and I'm happy to help guide the process. There is a [documented process] which should be up-to-date, though I haven't validated it.

Would @pganssle or @benoit-pierre care to cut the release? Ping me in Gitter or #pypa-dev or here.

**Comment by pganssle** [comment]
I'm kinda busy this week, @benoit-pierre do you want to take this one?

Otherwise I can do it next week if it can wait that long (I'm happy to get the next one).

**Comment by benoit-pierre** [comment]
I'll see if I can do it before next week.

Note:
* it's not possible to run the Python 3.3 tests with tox 3.0 (`ERROR: unknown environment 'py33'`), I have to downgrade my local version to 2.9.1.
* I think we should look into using [towncrier](`https://pypi.org/project/towncrier/`), like the pip project does, for managing `CHANGES.rst` and improve the workflow around it

**Comment by jaraco** [comment]
I’ve not set up town crier before but I’ve used it a couple of times and like it. I’d be delighted if someone implemented it for setuptools.

Also fine to drop support for Py33. Just need to make a backward incompatible release. Best to do that after releasing pending changes, even if they have to go out untested.

**Comment by pganssle** [comment]
I think we can rely on the CI for testing the Python 3.3 version, but I'm more or less fine dropping support as well.

The one thing is that I tend to prefer to have the "we support version X" be descriptive rather than proscriptive - do we have any changes in the wings that are just waiting for us to drop Python 3.3 support? Also, is there anything special we have to worry about if we drop it in `setuptools` since it's a lot harder to pin your `setuptools` version than it is to pin most other package versions?

**Comment by pganssle** [comment]
I set up a separate ticket for tracking the `towncrier` thing - #1341. I think there are a few policy questions about how we would use it to work out, only partially related to the actual configuration.

**Comment by benoit-pierre** [comment]
I released v39.1.0.
