### ISSUE TITLE
Spaces in file names make it impossible to package for Solaris 9 and 10

### ISSUE THREAD

**Issue by ghost** [pypa/setuptools#134]
Originally reported by: **automatthias (Bitbucket: [automatthias](http://bitbucket.org/automatthias), GitHub: [automatthias](http://github.com/automatthias))**

---

The `script template.py` file name causes packaging of setuptools to fail, because the Solaris 8, 9, and 10 package manager does not support file names with spaces: spaces are the column delimiter in its internal data files.
### References
1. http://docs.oracle.com/cd/E23824_01/html/821-1473/pkgmap-4.html
2. https://mail.python.org/pipermail/distutils-sig/2013-October/022803.html
3. https://gar.svn.sourceforge.net/svnroot/gar/csw/mgar/pkg/lang-python/pysetuptools/trunk/Makefile
4. https://gar.svn.sourceforge.net/svnroot/gar/csw/mgar/pkg/lang-python/pysetuptools/trunk/files/0001-Solaris-package-mge-does-not-handle-spaces.patch

---
- Bitbucket: https://bitbucket.org/pypa/setuptools/issue/134

**Comment by jayeye** [comment]
The purpose of any tool is to make life easier for the tool user, not to be a vehicle for the ego of its writer.

There is a tremendous number of Unix tools that do not handle spaces in filenames well. It would be far easier to remove the space from that file (which, btw, is the only filename with a space in the entire package).

**Comment by jaraco** [comment]
> There is a tremendous number of Unix tools that do not handle spaces in filenames well.

I acknowledge that many would just prefer to admit defeat and not support spaces in filenames. I think we can rise to the challenge and do better.

Thusfar, there have been two concrete reports of easily surmountable issues over the several years that this naming has been in place.

**Comment by aixtools** [comment]
Hello Jaraco,

Finally getting around to replying to your comment from https://github.com/pypa/pip/issues/3989#issuecomment-249711001

I scanned above - and shall give as short a reply as possible.

While an OS filesystem may support names with spaces it does not make them suddenly better than names without spaces.
Wonderful that setuptools supports installations that want to use that feature. But forcing it on all is dogma. It becomes your opinion of what is best for all becoming the law.

In - what I would call 'UserSpace' these may be useful (e.g., what the python developer is developing as a User application) - but for normal 'binary' packaging (what platform packagers are doing to make a language such as python more easily available) they may be undesired - aka a hindrance for normal systems administration.

In short, you forcing packagers and system admins to support spaces in all cases - meaning they must review and/or rewrite maintenance 'scripts'. Leaving the solution as a task of an individual packager only promotes non-uniformity (at best). In my case I just stopped trying. If you follow the path - I first contacted python who said, not my problem, try talking with 'pip' - and pip said you are the real owner.

IMHO - if you want to support portability and 'freedom' have 'spaces' as a default, but also demonstrate an option to either replace with an underscore, a dash, or remove and FirstLetterCapitalize. Let the 'user' of setuptools decide what is best for them.

For now:
a) there is not a simple solution
b) the easiest hack I can come up with is scan for files with 'unfortunate' characters (for the installer template format) and rename them. End result is that it never looks as documented.
c) Or, just do not package at all. setuptools becomes the show-stopper rather than as an asset to packaging and installing.

IMHO - it is about choice. I hope you will consider supporting a choice here.

**Comment by jaraco** [comment]
> End result is that it never looks as documented.

I agree. It's a bit ugly that on Solaris, one must get an install of Setuptools that appears "broken" with respect to the reference implementation.

In my opinion, though, that's the price a user of Solaris pays for using a package manager that's inherently hostile to otherwise valid characters. I'm pretty sure one could download/install pip or setuptools from source without any issues. There's no excuse in 2017 for a package manager not supporting all file names valid in the file system.

> if you want to support portability, demonstrate [another] option...

My understanding is that the maintenance scripts for Solaris packages already demonstrate this option and that this approach is viable and stable. What's the harm of the current approach? What would you suggest for this project to better support these package manager limitations?

**Comment by varder** [comment]
It is very bad the is space in files. It results multiple issue in Yocto build system.

**Comment by jaraco** [comment]
> It is very bad the is space in files. It results multiple issue in Yocto build system.

Condolences. I hope they fix the issues soon.

**Comment by kludgeaudio** [comment]
Wonderful.  Sarcasm.  We have systems that have backup issues because some Windows fool thinks that spaces in filenames are a good idea, and attempts to get this remedied result only in sarcasm.

**Comment by jaraco** [comment]
>  Sarcasm

I wasn't being sarcastic. Maybe a bit flippant. I'm genuinely sorry that people experiencing issues. I've been using spaces in filenames since 1993 on Unix systems and since 1995 on Windows, so it seems reasonable to me that systems dealing with files (such as a build system) should have such support, and I genuinely hope they do that sooner than later.

> some Windows fool

Please be mindful of the [Code of Conduct](https://github.com/pypa/.github/blob/main/CODE_OF_CONDUCT.md). Attacks and aspersions on individuals and groups aren't tolerated here.

> attempts to get this remedied result only in sarcasm

To the contrary, this issue has been adjudicated and revisited over the years, and it's still my position that we shouldn't bully projects into restricting the files they can use because a handful of tools don't support the full range of _commonly_ supported and demonstrably useful characters in the file systems.
