### ISSUE TITLE
Support `file:` for `[metadata]version` declarative config

### ISSUE THREAD

**Issue by warsaw** [pypa/setuptools#1358]
`[metadata]version` currently supports `attr:` and literal strings, but it would be super handy to support `file:` so that I can have a `mypkg/version.txt` file containing my version number.

**Comment by jaraco** [comment]
A bit more context. Obviously, one could put the version in `mypkg/version.py` and include it via `attr: mypkg.version`, _except_ if there's something in `mypkg.__init__` that's going to fail to import before the package's dependencies have been loaded.

@idlesign Any reason you can think the declarative config shouldn't support a `file:` for version number?

**Comment by jaraco** [comment]
In addition to the proposed solution, I can imagine another solution -- what if `attr: mypkg.version` loaded the version statically, without importing the module, but only be loading it and parsing out the value from the module directly, similar to how [rwt loads package names without executing the script](https://github.com/jaraco/rwt/blob/ea79922119de579b3767de221770f0bbc1c355f0/rwt/scripts.py#L87-L97)? Such an approach would only work if the attribute was always a literal string (and not a calculation like `__version__ = '.'.join(map(str, (1, 2, 0)))`; trust me [it happens](https://github.com/jazzband/inflect/blob/aa76dd67121494fbe7ff2bd956aa18ceb9c90ab1/inflect.py#L98-L103)).

**Comment by jaraco** [comment]
I suspect this issue would be a fairly accessible one, as it extends existing functionality to other existing fields.

**Comment by warsaw** [comment]
Not that it's entirely useful, but in the past I've used my [setuptools_helpers](https://gitlab.com/warsaw/setup_helpers/tree/master) script, which just reads a file and applies a regexp to dig out the version number.

**Comment by idlesign** [comment]
Hi,

> In addition to the proposed solution, I can imagine another solution -- what if attr: mypkg.version loaded the version statically [...]

On initial implementation I was thinking about a fallback for `ImporError` which ought to use pure parsing (something similar to https://github.com/idlesign/makeapp/blob/v0.12.1/makeapp/app_templates/__default__/setup.py#L19), but I resisted the temptation due to this parsing approach is too error prone for something that generic as `setuptools` (especially since we have a bunch of widely used approaches as where, how and what format to use to store version number).

> Any reason you can think the declarative config shouldn't support a file: for version number?

No, I think Barry's proposal it quite reasonable. Text files with just a single version line are quite common and can be easily generated by build tools. The only thing might be that in such a case the most reasonable way to get get version number will be using package data extraction facilities (which imposes some limitations).

**Comment by warsaw** [comment]
EIBTI!

**Comment by jmbowman** [comment]
#1359 has been merged, so I think it should be ok to close this.
