### ISSUE TITLE
.pypirc credentials get sent to redirect targets on third-party hosts.

### ISSUE THREAD

**Issue by kurtiss** [pypa/setuptools#1417]
My setup:
  - pypicloud, configured to redirect package links to signed S3 endpoints
  - .pypirc file, containing basic auth credentials to my pypicloud instance.

Credentials configured in .pypirc get added to package download requests in `package_index.py:open_with_auth`. My package server is configured to return a 302 with signed query parameters, pointing to a private s3 bucket. Because of the way setuptools configures its `urlopen(…)` call, the authorization header destined for my package server gets passed all the way to the signed s3 endpoint, which then responds with a 400, because there are now two authentication methods present.

It looks to me like a potential fix would involve either changing `request.add_header("Authorization", …)` to `request.add_unredirected_header("Authorization", …)` or a more extensive refactor making use of `urllib.request.HTTPBasicAuthHandler`.

**Comment by alkuzad** [comment]
this also happens with Artifactory and their "Direct Access" feature which does respond with 302 to S3.

**Comment by pganssle** [comment]
@alkuzad @kurtiss Can you clarify what commands you are using where this is happening? I don't think that we have any maintained (i.e. not deprecated) code that would communicate with an external server and send any credentials.

Is this something that happens with `setup.py upload`? If so, I recommend updating your `setuptools`, because `setup.py upload` was removed several versions ago, you should be using `twine` to upload your packages to PyPI or any mirrors.

**Comment by alkuzad** [comment]
@pganssle this will happen in both `python setup.py install` or `python setup.py test` for us. Fetching packages can fail for all or only some packages, because Artifactory does not respond to everything with 302, only these packages that are not cached locally (and cache expires after some time).

I do believe that `request.add_unredirected_header` will fix that but as JFrog disabled this feature for our server, I can no longer test it there. Simple HTTP server with 302 redirect to S3 could test this too.

**Comment by alkuzad** [comment]
@pganssle I actually got local setup with :

1. Flask server which returns static html for `/simple` with one package only - pip-tools link to `/packages/pip_tools-4.5.0-py2.py3-none-any.whl`. It responses with 302 to my own S3 with presigned link

2. os.getenv controlled if we use `request.add_unredirected_header` or not

unredirected_header manages to fetch package
standard one returns 400

We can do some quick call on weekend if you want to see it

**Comment by alkuzad** [comment]
@pganssle example code is here - https://github.com/alkuzad/setuptools-fix

**Comment by pganssle** [comment]
@alkuzad So I think this is a case where it's only affecting "unsupported" paths, because if I understand correctly using `pip install` should fix this (I'm a little surprised that `python setup.py install` is not *already* doing this, because I thought we replaced `easy_install` with `pip`), but the fix looks trivial, so I'm inclined to accept it.

The downside is that I'm about 85% confident that we will break existing peoples' workflow and there will be complaints if we do this, so I think we'll need to be sure that `pip install` actually works before we make such a change.

**Comment by alkuzad** [comment]
@pganssle what unsupported means ? Pip install indeed is working correctly, as it's using more advanced requests library.

Why is there difference with install and test if they both install dependencies ?

In both install.py and test.py I see only references to distutils commands or internal code using easy_install command. Pip is used in installer.py but I don't really know where it's methods are used. This is all using master code.

**Comment by jaraco** [comment]
The use of any package index from setuptools is deprecated and unlikely to be fixed. If this issue is still affecting users, it's an indication that they're reaching an unsupported codepath. Use pip or build to install or build. Use tox or similar to orchestrate tests.
