### ISSUE TITLE
Setuptools not installing buildtime dependencies specified in setup_requires

### ISSUE THREAD

**Issue by GMishx** [pypa/setuptools#1478]
In our Python project, we are using `setuptools` for building and installing the project. As per the [setuptools instructions](https://setuptools.readthedocs.io/en/latest/setuptools.html#configuring-setup-using-setup-cfg-files), I have used the `install_requires` and `setup_requires` to define the run time dependencies and build time dependencies. But when running
```bash
$ python setup.py build
```
The build time dependencies are not being installed before running the build script and my build fails.

If I install all the dependencies separately using `pip` and then run `python setup.py build` or `python setup.py install` it works. And the packages declared in `install_requires` are also installed separately while using the `install` command once everything is placed properly.

Where as if I run
```bash
$ pip install --user .
```
Every thing works as expected.

The project I am trying to build: https://github.com/fossology/atarashi/

**Comment by benoit-pierre** [comment]
From a quick look at your `setup.py`, you seem to be using a subprocess during the build (`atarashi/build_deps.py`, how do you ensure the `.eggs` directory (that's where setup requirements are installed) is added to the Python path? 

Please note that while it may seem like installing your package work when using pip (because `install_requires` dependencies are installed before your package), you should not rely on that behaviour. I suggest instead you look into using [PEP 518](https://www.python.org/dev/peps/pep-0518/) to declare your build time requirements.
