### ISSUE TITLE
Support environment markers for python_requires

### ISSUE THREAD

**Issue by anntzer** [pypa/setuptools#1570]
To my understanding, it is currently not possible to specify different values of python_requires that depend on environment markers.

An example use case is my mplcairo package (https://pypi.org/project/mplcairo/), which supports Py>=3.4 on Unices but Py>=3.6 on Windows (because its build requires a recent C++ compiler, namely MSVC2017 on Windows, but distutils is able to use MSVC2017 only since Py3.6.4 -- https://github.com/anntzer/mplcairo#windows).  Ideally, I'd like to specify something like
```
python_requires=[">=3.4; os_name == 'posix'", ">=3.6; os_name == 'windows'"]
```

From a quick look at PEP345, I guess this implies making the Requires-Python metadata field a multiple-use field with support for environment markers.

(Not sure if this belongs to the setuptools tracker or somewhere else.)

**Comment by pganssle** [comment]
I think this is best suited for https://github.com/pypa/packaging-problems since all the relevant packaging tools need to agree on this.

On its surface it seems reasonable to me. It's been a while since I've looked at the relevant PEP, but it may be worth looking into pinning to different versions depending on the interpreter used as well (pypy, jython, etc), if that's not already in there.

**Comment by pganssle** [comment]
Though also `python_requires` is a single string, not a list, I believe. How that affects the syntax I'm not sure.

**Comment by anntzer** [comment]
I'd switch it to a list, and support string meaning list-with-one-string.  Not the most elegant but heh.

**Comment by anntzer** [comment]
Moved discussion to https://github.com/pypa/packaging-problems/issues/209, thanks for the pointer.
