### ISSUE TITLE
Removal of easy_install breaks flatcam

### ISSUE THREAD

**Issue by dlsharp** [pypa/setuptools#1575]
I'm trying to install flatcam, and based on the error message, I need easy_install.  Per the instructions on https://setuptools.readthedocs.io/en/latest/easy_install.html , I am opening a ticket.

My use case is I want to use Flatcam.

The line that is breaking is:

easy_install -U distribute

If someone could provide an example of how to do the equivalent without easy_install, I'd be most appreciative.  I'm not a python developer, so my attempts to troubleshoot this via google have not been successful.

Thanks.

**Comment by benoit-pierre** [comment]
`easy_install` is not removed, it's deprecated. How do you install it? What's the exact command line? What is the error message? Please also provide your Python version and your operating system.

**Comment by dlsharp** [comment]
The OS is Ubuntu 64-bit 18.0.4.1.
The installation of flatcam went as follows:

git clone https://bitbucket.org/jpcgt/flatcam.git

cd flatcam

sudo ./setup_ubuntu.sh

This eventually fails with: 
./setup_ubuntu.sh: 17: ./setup_ubuntu.sh: easy_install: not found

The following page indicated that easy_install was removed from python-setuptools in version 39.0.1-2: https://askubuntu.com/questions/1040392/easy-install-command-not-found

Now that I'm thinking about it though, maybe this is something Ubuntu changed and they're shipping their own version of python-setuptools.

**Comment by benoit-pierre** [comment]
Yes, apparently Ubuntu stopped shipping the easy_install script. In any case, I would open an issue on the flatcam project tracker asking them to update their `setup_ubuntu.sh` script to use pip instead.

**Comment by codrcodz** [comment]
I already commented on the [LaunchPad](https://bugs.launchpad.net/ubuntu/+source/python-setuptools/+bug/1774419) bug report for this, but wanted to add something here as well.

Even if `easy_install` is deprecated, having `easy_install` available (or something similar) is likely an ongoing need for at least one reason very good reason.

If a Linux user wants to use upstream python packages that are either unavailable from their distro's repositories or not packaged at all by their distro, they will be required to somehow install `pip`. This leaves them with a couple of choices. They can either manually grab and install `pip` using something like `wget` or they can use their system package manager to somehow install it. One way to do this is to use their package manager to install a packaged version of `pip`, usually from `python-pip` or similarly named package (depending on the distro). This approach however, has a major flaw. If a user installs `pip` via this method they are forever stuck on a slightly older version of `pip`. If a user uses their system package manager to install `pip`, and then later wants to use newer `pip` features to install upstream packages on their file system, they are unable to `pip install -U pip` without stomping on files already installed via their package manager. If a user ever installs `pip` from their package manager, it is assumed that they are doing so because they want to install a python package from upstream, and not their distro's repositories, and since some newer packages may rely on new features in `pip`, it only makes sense to install `pip` from upstream, and not the system's package manager. 

So, how does one typically go about doing this?  Historically the preferred approach has been to install the `python-setuptools` package via their package manager and use `easy_install` to install `pip` straight from PyPi, and then from that point forward use `pip install -U pip` to keep it up to date. By installing `pip` with the `easy_install` binary installed via their package manager, they can safely keep `pip` on the latest version without worrying about `pip` and their package manager overwriting each other's `pip` package files every time one of them updates.

If the maintainers want to deprecate legacy software like `easy_install`, that makes perfect sense, but at a minimum, I would consider keeping around a bare bones version of it for bootstrapping `pip` and maybe throwing a deprecation warning/error if a user tries to use it for installing anything other than `pip`. This gets you the best of both worlds, people can use it to migrate to it's replacement and you can get the word out about it's deprecation a little better. 

I would keep an old copy of it available and tucked away in `setuptools` somewhere for a few more releases, but in the meantime, add a different script back into the python path in place of `easy_install` that will do only one of two things depending on how the user invokes it: 1) If the user runs `easy_install pip`, install pip from PyPi; or 2) If the user runs anything else, give the user a helpful error message to stderr letting them know it is time to migrate and that a copy of  the actual `easy_install.py` script is available in $location, but is no longer receiving updates and will be removed in $release_number.

During my short time searching for information about this bug I have seen numerous people complain about this issue due to the sheer amount of legacy software that depends on `easy_install`.  Coming from a system engineer/admin/operations background, I can tell you from experience that no matter how much you advertise the decommissioning of some system/software/service, someone will always complain so the best you can do is provide a deprecation warning as early and as loudly as possible.

**Comment by benoit-pierre** [comment]
The preferred way to get pip if you don't already have it is to use [get-pip.py](https://pip.pypa.io/en/stable/installing/#installing-with-get-pip-py).

**Comment by codrcodz** [comment]
Noted! I'll make the suggestion to the distro maintainers that they package this alongside python-pip to give the user the choice on how they install pip. Thanks for the information and responsiveness!
