### ISSUE TITLE
Please add --install_requires & --setup_requires or similar option (like --requires but for "install_requires" and "setup_requires"))

### ISSUE THREAD

**Issue by JonasT** [pypa/setuptools#1606]
I don't know what `--requires` does, but sadly it neither prints the contents "install_requires" nor of "setup_requires".

There is a suggested workaround to this (StackOverflow) to use "egg_info" and read the `requires.txt` generated in there, however, the egg_info can end up in a subdirectory if the pacakge_dir isn't in the root (for example `src/package_name.egg-info`), and the output isn't friendly for automatic parsing to get that path, so in the end it's just needlessly complicated as compared to a simple option that just outputs the requirements/dependencies.

Would you possibly be open to adding such an option?

Such an option would be very useful for the rare cases where such meta information could be required. If you're curious, my specific interest is for python-for-android which repackages Python 3 programs for Android phones, and therefore sometimes needs to know dependencies to install them beforehand in a different, Android-compatible way since upstream doesn't provide official support (e.g. patches) - so certainly not a normal use case, and I agree this option would probably not be used often, but in the rare cases it is useful it'd be quite nice to have.

**Comment by jaraco** [comment]
This project is working to limit the dependence on `setup.py (anything)`, mainly because with the introduction of PEP 517 and 518, it's no longer generally meaningful to rely on invocation of setup.py for package operations.

Probably your better bet will be to rely on something like [importlib_metadata](https://pypi.org/project/importlib_metadata), which is slated for inclusion in stdlib in Python 3.8 and which is seeking to provide a higher-level interface for any installed projects (including develop-installed).

In that project, there's an [open issue](https://gitlab.com/python-devs/importlib_metadata/issues/18) to provide a high-level function for returning the dependencies (and extra dependencies) in a structured form.

In the meantime, you can use `importlib_metadata` to query for the contents of that requires.txt file:

```
>>> import importlib_metadata
>>> requires_text = importlib_metadata.read_text('mypkg', 'requires.txt')
```

Does that help at all?

**Comment by JonasT** [comment]
Not much, because it doesn't seem to work:

```
$ python3
Python 3.6.7 (default, Nov 23 2018, 12:11:28) 
[GCC 8.2.1 20181105 (Red Hat 8.2.1-5)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import importlib_metadata
>>> import subprocess
>>> import sys
>>> package_name = subprocess.check_output([sys.executable, "setup.py", "--name"])
>>> package_name = package_name.decode("utf-8")
>>> requires_text = importlib_metadata.read_text(package_name, 'requires.txt')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jonas/.local/lib/python3.6/site-packages/importlib_metadata/api.py", line 146, in read_text
    return distribution(package).read_text(filename)
  File "/home/jonas/.local/lib/python3.6/site-packages/importlib_metadata/api.py", line 86, in distribution
    return Distribution.from_name(package)
  File "/home/jonas/.local/lib/python3.6/site-packages/importlib_metadata/api.py", line 52, in from_name
    raise PackageNotFoundError(name)
importlib_metadata.api.PackageNotFoundError: Shrugger's Pen```

Does this only work for installed packages? Also, what happens if the package is installed, will the local folder version take precedence?

If the answer to any of these two questions is true, then it's really not helpful for this use case, sadly

**Comment by jaraco** [comment]
> Does this only work for installed packages? 

Yes 

> will the installed version in site-packages take precedence over the local folder version?

That's a good question. I think importlib_metadata assumes that only one version of a package is ever installed (because Python/pip doesn't support multiple distributions of the same package being installed). So I suspect `importlib_metadata` would crash in that situation.

> it's not really helpful for this use-case.

I think I agree. Your use-case is to identify metadata about a package that's not installed. I think in that case, you probably do need something that's in the build system to supply the necessary information. The problem is, it's not sufficient to add this functionality to setuptools as what you need more generally is something that would work with packages not built by setuptools.

Also, `setup_requires` is soft-deprecated. The PEP-518 build dependency declarations are intended to supersede and obviate `setup_requires`.

To get the setup_requires, you'll want to have a tool that can read a project's `pyproject.toml` file to extract those requirements. And from there, you should be able to use something like `pip wheel` to build the project and then use a tool like importlib_metadata or pkginfo (as [illustrated here](https://stackoverflow.com/a/50214191/70170)) to extract the requirements from that build. Such a technique should be more future-proof and work with any package and not rely on setuptools-specific behavior.

But thinking about this specific use-case, where you wish to get some details about the build from a known setuptools project, I had once worked on a project that was designed to do what you need. It's the [show command in jaraco.packaging](https://jaracopackaging.readthedocs.io/en/latest/#jaraco.packaging.info.Show), which is intended to allow retrieval of arbitrary metadata from a package not yet built. It currently has the same problem as you're having, that it will report `Requires` (metadata 1.1) but not `Dist-Requires` (metadata 1.2). So I've gone ahead and [added support for retrieving arbitrary attributes on the Distribution object](https://github.com/jaraco/jaraco.packaging/commit/fc08a45fc340e193e6798dc9f8bf0a8cff288925). If you install `jaraco.packaging>=5.2`, you should now be able to run `python setup.py show -a install_requires` to get the install requirements.

Note, this technique is brittle and ugly, but maybe it's enough to paper over the issue for now. Let me know what you find.

**Comment by JonasT** [comment]
> I think I agree. Your use-case is to identify metadata about a package that's not installed.

Correct!

> I think in that case, you probably do need something that's in the build system to supply the necessary information. The problem is, it's not sufficient to add this functionality to setuptools as what you need more generally is something that would work with packages not built by setuptools.

Isn't there any chance to get something official for this? I don't mind going to another bugtracker if you have a good idea where this could be put, I'm just not familiar enough with different approaches of packaging things. What's the common alternative to setuptools, distutils? Is there no sort of cooperation between the projects about what basic options a `setup.py` should support? After all, all the usual projects also support for example `install`.

As for your personal attempt, I haven't tried it but if I'm not misreading the code entirely, it seems to expect a "show" verb to work, and at least my pure setuptools setup.py doesn't have that:

```
$ python3 setup.py show
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'show'
```

**Comment by JonasT** [comment]
I poked around `--help` some more and can't find a way to get the `.egg` path out of it either. The only other semi-reliable approach I could think of is to monkey-patch setuptool's setup() function to report the contents to me, then import the user `setup.py` after that (and do the same for distutils and other often-used variants). But that's super ugly, obviously. But so is scanning around blindly for random `.egg` folders

**Comment by JonasT** [comment]
It also seems like a kind of half-disaster that `importlib_metadata` doesn't take a file path, so who knows what I end up with if another, different version of this package is already installed. Basically this seems to qualify as "maybe works for 95%" of cases", but not any solution I'd be happy with in the long term

**Comment by JonasT** [comment]
For what it's worth, there is now a ticket here: https://github.com/pypa/packaging-problems/issues/247

Also, there's the related one here: https://github.com/pypa/packaging-problems/issues/224

And I wrote code based on `pep517` to do this, so far not in any independent library but trivial to split out, so if anyone wants it poke me

(I didn't use `importlib_metadata` because it needs packages to be installed in all cases - pep517 doesn't with its metadata for build wheel hook, it's based directly on pep517, `venv` and a `pip` call for downloading)

So I'll close this ticket here since this is not really a `setuptools` issue
