### ISSUE TITLE
setup_requires="string" not handled by PEP 517 backend

### ISSUE THREAD

**Issue by cjerdonek** [pypa/setuptools#1682]
Does this need to be fixed in setuptools rather since the PEP says the return value needs to be a list of strings? https://www.python.org/dev/peps/pep-0517/#get-requires-for-build-wheel

It looks like here is the setuptools code: https://github.com/pypa/setuptools/blob/cdb5eeae678d8ccc90bf7d4348013a294f11be75/setuptools/build_meta.py#L138

_Originally posted by @cjerdonek in https://github.com/pypa/pip/issues/6255#issuecomment-462468517_

**Comment by pganssle** [comment]
So my instinct here is to say that `setup_requires` is deprecated, because generally speaking the stuff you put in there is what needs to be installed *before `setup.py` is invoked* (and `setup.py` is where you get `setup_requires` from). It should be replaced by the `build-system.requires` key in `pyproject.toml`.

The biggest downside I see to doing this is that it would make `setup_requires` the most convenient place to "single source" your setup requirements, since builds that want to do "best effort" support for pre-PEP 518 build systems may want to specify `setup_requires`. Right now they have to duplicate the information, but if we add support in `setup_requires` in the PEP 517 backend, they would be able to omit the information from `pyproject.toml` in the interest of having a single canonical source for the build information - the opposite of what we want happening.

The biggest upside is that if we do this, PEP 517 builds are much more likely to "just work" out of the box, and I believe it means that for PEP 517 builds we will have *eliminated* the `easy_install` code path, which is very attractive. In this case, it might make sense to use this *only* for the `setuptools.build_meta:__legacy__` backend, since it's actually a compatibility mode enhancement. I'm mildly reluctant to do it that way, though, because I don't want to give people *more* reasons to explicitly use `setuptools.build_meta:__legacy__`.

**Comment by pganssle** [comment]
Hm, I guess I misunderstood this issue, I didn't realize that we're *already* translating `setup_requires` requirements into build requirements in the build requirements hooks.

That's mildly embarassing. I am going to hide my previous post as irrelevant, feel free to read it if you want to know how I would have responded if I had been around when we first added this feature.

To respond to the actual issue, yes, this seems to be supported in the old system and I see no good reason to drop support for it now.

**Comment by pganssle** [comment]
I think this is decently simple to fix, I think the one thing I'd like to avoid is duplication of the logic that handles `setup_requires` strings, so whoever fixes it please try and make it so that the `setuptools.build_meta` code receives the list of missing requirements in a consistent format.

Minimum cases to handle:

- `setup_requires=["foo"]`
- `setup_requires="foo"`
- `setup_requires="foo\nbar"

Please add tests to `setuptools/tests/test_build_meta.py`, and if you are feeling ambitious, I think there are also no tests for this "newline-delimited requirements string" format in the general test suite.
