### ISSUE TITLE
Use of pkg_resources.resource_filename() without a resource_name

### ISSUE THREAD

**Issue by lkollar** [pypa/setuptools#1686]
The new validation in #1640 broke some of our applications which relied on setting `resource_name` to `None` to look up the path to the package.

Example:

```python
SCHEMA_PATH = pkg_resources.resource_filename('application.schemas', None)
```
Replacing this with `pkg_resources.resource_filename('application.schemas', '')` fixes the issue.

Is this acceptable `resource_filename` usage? Can we depend on the empty string as resource name?

**Comment by pganssle** [comment]
@jaraco I'll leave this to you if you want to consider other false-y values of `resource_filename` to be in or out of scope.

Based on [this code block](https://github.com/pypa/setuptools/blob/cdb5eeae678d8ccc90bf7d4348013a294f11be75/pkg_resources/__init__.py#L1471-L1474), I assume that it was always intended that we would support an empty `resource_filename`, and it would be pretty simple to move the `self._validate_resource_path` call into the `if` block, since the validation only applies to the resource name not the base.

We could also raise a warning in the event that someone passes a false-y non-string, though that seems a bit like rearranging deck chairs on the titanic. While I think `pkg_resources.resource_filename` is kinda fundamentally broken because of the "extract to a temporary file that we then clean up" problem, I'm leaning towards not changing the semantics accidentally like this. I don't feel terribly strongly about it either way.

**Comment by jaraco** [comment]
> Is [an empty string for resource_filename] acceptable `resource_filename` usage? Can we depend on the empty string as resource name?

Yes and no (to both). I believe [the documentation](https://setuptools.readthedocs.io/en/latest/pkg_resources.html#basic-resource-access) by stating that the `resource_name` is interpreted relative to the base does strongly imply that the empty string should be supported. And there is usage in the tests that exercises the empty string (`resource_listdir('')` calls into `_fn` with `resource_name==''`)... but this particular usage is neither explicitly documented nor directly tested. I'd feel better if the code were explicit about this usage.

> The new validation broke some of our applications

Sorry about that - it wasn't expected that any code was relying on the `None` value (though also not unreasonable to think that it might). Since you haven't asked to retain compatibility, and your focus has been on what interface _your_ code can rely on (thanks for that), I'll defer restoring compatibility for `None` values unless someone requests it.

**Comment by jaraco** [comment]
in ad98fcb, I've made explicit the expectations. Let me know if restoring support for `None` values is something you need/desire.
