### ISSUE TITLE
No obvious way to get installation path during installation

### ISSUE THREAD

**Issue by VasLem** [pypa/setuptools#1693]
How is it possible to get the installation path from inside `setuptools.command` classes during installation? I need to edit a configuration file after installation, given input arguments. I know that I could ask it in stackoverflow but this is more like missing documentation problem.

**Comment by pganssle** [comment]
@VasLem This is probably not something we're going to support, if it's at all possible, because  installations are supposed to first be built as a wheel, and then installed from the wheel. Even when installing an `sdist` directly, the first stage is building a wheel.

I think this is likely an [XY problem](https://meta.stackexchange.com/questions/66377/what-is-the-xy-problem) and asking how to achieve what you're trying to use this to achieve *without* the installation path on SO would probably be productive.
