### ISSUE TITLE
Querying Requested Extras in build_ext

### ISSUE THREAD

**Issue by ax3l** [pypa/setuptools#1712]
Hi,

I am building an external CMake extension with

```py
from setuptools import setup, Extension
from setuptools.command.build_ext import build_ext


class CMakeExtension(Extension):
    def __init__(self, name, sourcedir=''):
        Extension.__init__(self, name, sources=[])
        self.sourcedir = os.path.abspath(sourcedir)


class CMakeBuild(build_ext):
    def run(self):
        # ...

        for ext in self.extensions:
            self.build_extension(ext)

    def build_extension(self, ext):
        # ...

# ...
setup(
    # ...
    ext_modules=[CMakeExtension('openpmd_api')],
    extras_require={
        'mpi': ['mpi4py'],
    },
    # ...
)
```

and would like to query the user-requested `extras` during the `build_extension` step, in order to find out if the extra `'mpi'` was requested (via `pip install .[mpi]`) or not. Is there a way to query this?

Full example: [setup.py](https://github.com/openPMD/openPMD-api/blob/dev/setup.py)

**Comment by pganssle** [comment]
I may be displaying my ignorance of how this all works here, but I think the specified extras are not intended to be build flags, but optional *install time* dependencies. I'm not sure that `setuptools` ever *gets* that information, much less uses it for anything. I think extras are basically just install-time metadata about additional features that can be enabled in the project, not build-time flags.

I think the most "standard" way to do this sort of thing (and I admit it's not great UX) is to factor out the things that have your extra (e.g. `mpi`) as a build-time dependency into their *own* packages that install into your project's namespace. So the `[mpi]` extra introduces a dependency on `mypkg.mpi_extension`, which has a *hard* build dependency on `mpi`.

**Comment by ax3l** [comment]
Thanks for the help! Urgh, I feared that when checking the `self.__dict__` of `setuptools.Extension` and found no traces... It would be really complicated and verbose to implement your suggested work-around in my case...

Can I maybe hook into some call inside `setup()` to set a global before building the extension or so?

**Comment by pganssle** [comment]
@ax3l I do not think that "extras" are intended to control additional functionality in the *build*, they are intended to allow you to specify dependencies for optional *runtime* features (see the [documentation](https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies)). I could certainly be wrong because I don't know much about the history of the "extras" feature, but it's really about declaring metadata *for the front-end*.

At least the way the build tools *currently* work, the idea is that at build time you would build *everything you support*, and at install time those features would only actually be usable if you had specified the extra options. This means that either you make a hard build-time requirement of `mpi`, regardless of the extra options, but make it optional at install time, or you separate out the parts that require `mpi` into a separate package that itself has a hard requirement of `mpi`.

**Comment by ax3l** [comment]
> "extras" are intended to control additional functionality in the build, they are intended to allow you to specify dependencies for optional runtime features

I agree, looks the same to me. Unfortunately, "everything can be checked at runtime" is a very pythonic viewpoint and doesn't work well with all the binary (e.g. C)-extensions that get lot of their features through build-time configuration.

Anyway, that just means I can't currently express build-time variants in the pip/setuptools canon. I will control my build with environment variables instead. Popular projects have done this for the same reasons since a long time, e.g. [h5py](http://docs.h5py.org/en/stable/build.html#custom-installation) and I will just do the same.

Thanks for your help still, too bad extras are not deeper integrated to allow such workflows :)

**Comment by jaraco** [comment]
Here's my (late) response as posted in the [Gitter inquiry](https://gitter.im/pypa/setuptools?at=5c7c0a4fd2d62067b7396b61) (I haven't read the thread above).

> That’s not possible as far as I know. If the current project depends on it to decide how to build itself, then it’s not really an extra (as intended). Extras are intended for install-time dependency resolution, not build-time. You’ll want to structure your project so it can support running with and without the extras at run-time… maybe that means building with and without the libs the extras might require, or maybe it means pushing that functionality into the extras themselves.

**Comment by pganssle** [comment]
Closing as out of scope.
