### ISSUE TITLE
packages=find: doesn't work with native namespace packages (PEP-420)

### ISSUE THREAD

**Issue by reece** [pypa/setuptools#1778]
With setuptools 41.0.1, `packages=find:` does not find packages that use [native namespace packages](https://packaging.python.org/guides/packaging-namespace-packages/#native-namespace-packages). 

In my case, the tree is:
```
ga4gh/
    core/
       __init__.py
    vr/
       __init__.py
```

When building a wheel (using `python setup.py wheel`), the package is empty. If I add an `__init__.py` under `ga4gh/`, all .py files are found as expected.

Expected behavior: `ga4gh/__init__.py` should not be required.

There are no other ga4gh packages installed, so this is not a case of mixing multiple namespace styles.

**Comment by pganssle** [comment]
@reece Correct, you should use [`find_namespace`](https://setuptools.readthedocs.io/en/latest/setuptools.html#options).

I will warn you, this is a very dangerous option to use if you are not using it in combination with a [src/ layout](https://setuptools.readthedocs.io/en/latest/setuptools.html#using-a-src-layout) (one reason why it is not the default). Because with PEP 420 namespace packages, pretty much any folder that has python files in it can be a namespace package, which means you are very likely to install a package called "tests" or "examples" or "ci_scripts" or something like that.

**Comment by reece** [comment]
@pganssle : Awesome. Worked like a charm. (Yes, using a src/ layout.) Thanks!
