### ISSUE TITLE
python2.7 easy-install.pth contains lib_pypy

### ISSUE THREAD

**Issue by ghost** [pypa/setuptools#179]
Originally reported by: **keturn (Bitbucket: [keturn](http://bitbucket.org/keturn), GitHub: [keturn](http://github.com/keturn))**

---

I installed PIP with pypy, and the file $HOME/.local/lib/python2.7/site-packages/easy-install.pth ended up with "/usr/lib/pypy/lib_pypy" in it.

That pretty well broke cpython 2.7 when it tried to load things from lib_pypy instead of cpython paths.

---
- Bitbucket: https://bitbucket.org/pypa/setuptools/issue/179

**Comment by abravalheri** [comment]
Hello, since support for Python 2.7 was dropped a while ago (and `easy_install` itself is deprecated), I believe we should be able to able to close this issue...

If anyone would like to reopen this issue, please feel free to write a new comment with more information or other use cases that we might be missing 😄.
