### ISSUE TITLE
pip show gives Licence UNKNOWN

### ISSUE THREAD

**Issue by GadgetSteve** [pypa/setuptools#1797]
I believe that adding a `licence` entry to setup.py/pyproject.toml/equivelent would resolve this - it would remove the step of visiting the repository to check the licence type for those that have to worry about such things.

**Comment by jaraco** [comment]
Except that's against the [recommended practices https://github.com/pypa/packaging-problems/issues/41]. The issue is seemingly that the `License` reported by pip is only the the free-form `License` in the metadata and doesn't reflect a license file or trove classifiers. I'd like to avoid triplicately indicating the license, especially since making this change would imply that all projects should do the same. That should only happen if a new standard is adopted with a different recommended practice.

Thanks anyhow for the suggestion.
