### ISSUE TITLE
Provide option `docs_require` to specify requirements for documentation building

### ISSUE THREAD

**Issue by theHamsta** [pypa/setuptools#1820]
Build commands like `sphinx.setup_command.BuildDoc` could profit from an official option to install requirements for documentation building. Similar to `tests_require`, `extras_require`.

An alternative would be to provide an easy possibility to make build command to depend on a specific extra with an `extras_require`.

I have no experience with the code base of setuptools. So please forgive me if I was overlooking something.

The speficied issue is related to:
https://github.com/pyscaffold/pyscaffold/issues/250

**Comment by pganssle** [comment]
@theHamsta I think it is unlikely that we are going to do this. We're trying to move away from invoking `setup.py` entirely, because it is in some ways fundamentally broken to try to install new dependencies after you have invoked `setup.py`. For builds, this is the motivation behind [PEP 518](https://www.python.org/dev/peps/pep-0518/). I'll also note that we're trying to move away from `tests_require` and `setup_requires` because they go through a deprecated code path (deprecated in favor of `pip`, which we cannot add a dependency for). For more information, see for example [this thread on deprecating the test command](https://github.com/pypa/setuptools/issues/1684).

If you want something that will execute arbitrary commands for you in a specified virtual environment, I can strongly recommend [tox](https://tox.readthedocs.io/en/latest/), which can be used for things other than tests and should meet all your requirements. You can note that you can manage your dependencies however you want - in a `docs` extra, `requirements-docs.txt`, `docs/requirements.txt`, however you want.
