### ISSUE TITLE
build meta wheel does not respect metadata_directory per PEP-517

### ISSUE THREAD

**Issue by gaborbernat** [pypa/setuptools#1825]
From https://www.python.org/dev/peps/pep-0517/#build-wheel:

> If the build frontend has previously called prepare_metadata_for_build_wheel and depends on the wheel resulting from this call to have metadata matching this earlier call, then it should provide the path to the created .dist-info directory as the metadata_directory argument.

https://github.com/pypa/setuptools/blob/master/setuptools/build_meta.py#L208 though ignores the passed in ``metadata_directory`` argument and goes to regenerate this information in the root of the project.

```python
    def build_wheel(self, wheel_directory, config_settings=None,
                    metadata_directory=None):
        return self._build_with_temp_dir(['bdist_wheel'], '.whl',
                                         wheel_directory, config_settings)
```

**Comment by gaborbernat** [comment]
> IMO the passed directory is not necessary. It will certainly match the recently generated one.

First and foremost it's mandated per PEP-517, so you MUST conform to that expectation.

Second, you can't really make the assumption that it will match. For example, the user might have invoked manually (aka via ``python setup.py``, and then the metadata directory defaults to the default location (in-place of the source tree at the moment); while frontends may want to move the metadata directory out of the source tree into a frontend specific folder (such as `.tox`). So I'm not sure how you can make that `certainly` assumption, without causing headaches and subtle bugs.

**Comment by dholth** [comment]
I think the current backends always rebuild dist-info as part of the wheel build. The newly rebuilt dist-info is very likely to match the one built moments earlier by the other hook

**Comment by gaborbernat** [comment]
> The newly rebuilt dist-info is very likely to match the one built moments earlier by the other hook

I'm not sure I follow how this is related to the fact that this hook should take and use the `metadata_directory`, maybe the frontend wants to use the content of the folder afterward, not?

**Comment by pradyunsg** [comment]
Updated OP's post to a permalink: https://github.com/pypa/setuptools/blob/2878bad0df158243d1e6601110ec12868e201d81/setuptools/build_meta.py#L214

**Comment by uranusjr** [comment]
This is also discussed in pypa/build#217. Although setuptools is free to rebuild dist-info in `build_wheel` (instead of using the content of `metadata_directory`), it should at least *verify* the built wheel indeed contains identical metadata to those provided in `metadata_directory`. #2529 is a concrete example of setuptools failing expectations due to this nonconformance.

This has also been raised to flit (takluyver/flit#389) and poetry (python-poetry/poetry#1078).

**Comment by dholth** [comment]
Would it be easier to remove this requirement from the specification since no backend found it worthwhile

**Comment by uranusjr** [comment]
But then what happens if a backend return different things from `build_wheel` and `prepare_metadata_for_build_wheel`? It is certainly possible to remove the requirement for backend to make use of the `metadata_directory` argument, but the backend should still somehow return consistent things from the two hooks. Otherwise the frontend would be stuck and can’t proceed. The discussion needs to be moved to discuss.python.org if you want to do that so frontend authors can join the conversation.

**Comment by wimglenn** [comment]
[setuptools-ext](https://github.com/wimglenn/setuptools-ext) is a thin wrapper around `setuptools.build_meta` allowing to specify some more metadata fields such as _Requires-External_, which aren't otherwise supported by setuptools. Passing around the `metadata_directory` ([ref](https://discuss.python.org/t/nobody-is-following-the-metadata-directory-promise-in-pep-517/6964)) would have been really useful to rely upon.

If setuptools correctly followed PEP 517 (i.e. does not just [ignore the `metadata_directory`](https://github.com/pypa/setuptools/blob/1b25c061e54714dbea68c5194b74f09191ce6381/setuptools/build_meta.py#L242)), we could simply call `prepare_metadata_for_build_wheel` before dropping in some additional files, or modify existing ones, under `.dist-info` subdir, and then call build wheel.

However since that didn't work, instead `setuptools-ext` has to call `build_wheel`, and then completely [rewrite the result](https://github.com/wimglenn/setuptools-ext/blob/d460fa347615bd4a3fbbb43e37d6fc707ee32892/setuptools_ext.py#L59), which is a lot more complicated (considering that modifying the METADATA file also invalidates the RECORD file!)

This "tweaking" of the build by wrapping the hooks is apparently an expected usage because it's documented as a way for an in-tree build backend to augment the build dependencies [here](https://setuptools.pypa.io/en/latest/build_meta.html#dynamic-build-dependencies-and-other-build-meta-tweaks). It's unfortunate that we can't reliably use a similar technique for `prepare_metadata_for_build_wheel` and `build_wheel`.

**Comment by pelson** [comment]
I just encountered exactly the same thing as seen by ``setuptools-ext`` - modifying the metadata in ``prepare_metadata_for_build_wheel`` would be super useful (and PEP-517 spec compliant). 

I'm guessing it isn't already easy to build using an _existing_ ``dist_info`` directory with ``setuptools``, hence the reason for not having implemented this already?

**Comment by abravalheri** [comment]
> I'm guessing it isn't already easy to build using an existing dist_info directory with setuptools, hence the reason for not having implemented this already?

Precisely. Things are complicated because of the division between the `setuptools` and `wheel` packages.

Right now the `METADATA` file should be similar to the `PKG-INFO` considering that there is no other packaging wrapping setuptools. So setuptools/wheel kind of try[^1] to comply with the PEP requirements[^1] as long as there is no other "man-in-the-middle" modifying the files. I believe other backends also adopt the approach of re-generating the file.

[^1]: Tries but probably fails in some edge cases, because it is a difficult problem.
[^2]: The PEP does not necessarily excludes the possibility of re-generating the files, but it requires them to a "non-modified" version of each other...
