### ISSUE TITLE
pkg_resources does not include RequirementParseError in `all`

### ISSUE THREAD

**Issue by TansyArron** [pypa/setuptools#1831]
This causes mypy type checks of code importing RequirementParseError as a 3rd party library to fail with:
```
error: Module has no attribute "RequirementParseError"
```

eg:
in some other python project, in a new file:
```
from pkg_resources import RequirementParseError
```

run mypy and watch it choke with
```
error: Module has no attribute "RequirementParseError"
```

**Comment by jaraco** [comment]
Thanks for the report. That's great to hear that mypy is helping enforce the convention that only names exposed through `__all__` are public. Until today, I was unaware that was one of its features.

Since this attribute was never exposed, I'm wondering if the project wants to support exposing that exception, or if perhaps there's another way to go. In #2137, I propose removing that exception.

Can you elaborate on the projects that are importing and using the `RequirementParseError` so we can assess what's the best way to support that use-case?

**Comment by jaraco** [comment]
Let's instead aim to remove this deprecated value. It sounds like mypy is doing its job and letting users know they're using an unsupported name.
