### ISSUE TITLE
Allow extras_requires to exclude instead of include packages

### ISSUE THREAD

**Issue by Helveg** [pypa/setuptools#1875]
I've seen some [StackOverflow questions](https://stackoverflow.com/questions/53376135/install-by-default-optional-dependencies-in-python-setuptools) for the same feature, and it seems almost trivially easy to implement, but could we instead of including additional packages in `extras_requires` also exclude packages? A simple conventional notation would be to prefix the package name with an `!`.

For example if we'd like to by default ship with `pdf` functionalities but optionally allow for a leaner install without pdf packages:
```
  ...
  install_requires = [
    'pdf-package>= 4.0.0'
  ],
  extras_require = {
    'without-pdf': ['!pdf-package']
  }
  ...
```

Is this feature feasible or is there already a better way to do it? It seems like a very elegant tiny addition that serves a lot of use cases.

**Comment by abravalheri** [comment]
Hi @Helveg, thank you very much for bringing up this topic!

I think the best place to discuss this idea would be https://discuss.python.org/c/packaging/14
(Unfortunately it is not trivial that setuptools can implement it alone -- some standardisation effort is needed, since it potentially would require changing the Core Metadata spec and what has been stablished in PEP 621).
