### ISSUE TITLE
Distribution attributes specified in a setup.cfg are not set in the setup_keywords extension callback

### ISSUE THREAD

**Issue by Rezzie** [pypa/setuptools#1914]
This applies to 41.6.0.

When using a `setup.cfg` file to specify package metadata instead of inline via `setup.py:setup()` arguments, none of the values from the configuration file are reflected in the `Distribution` object passed into the validation function of a [`setup_keywords` extension](https://setuptools.readthedocs.io/en/latest/setuptools.html#adding-setup-arguments).

For example, with a custom keyword `my_keyword` defined as such:
##### `my_keyword_ext.py`
```python
def validate_my_keyword(dist, attr, value):
    print(f'name: {dist.get_name()}')
```
Using the following:
##### `setup.py`
```python
from setuptools import setup
setup(name='example', my_keyword='value')
```
...prints `name: example` when the project is processed. However, moving the name argument to a configuration file:
##### `setup.py`
```python
from setuptools import setup
setup(my_keyword='value')
```
##### `setup.cfg`
```
[metadata]
name = example
```
...prints `name: UNKNOWN` when the project is processed. Inspecting the `dist` parameter of my extension reveals *none* of the attributes from the configuration file have been applied at the time of the callback.

I would expect the configuration file attributes to have been processed and reflected in the `Distribution` and made available to my extension. My workaround is to move any attributes I require back into the `setup.py`, but I would prefer to keep everything in the configuration file for consistency.

**Comment by abravalheri** [comment]
Hi @Rezzie thank you very much for bringing this up.

Currently setuptools parses both [`setup_keywords`](https://github.com/pypa/setuptools/blob/d3124ac33e1407ced092deb2e8854471773786d4/setuptools/dist.py#L457) and [`finalize_options`](https://github.com/pypa/setuptools/blob/d3124ac33e1407ced092deb2e8854471773786d4/setuptools/dist.py#L821) extensions during object initialisation, while the configurations from `setup.cfg` files are parsed much later in [`parse_config_files`](https://github.com/pypa/setuptools/blob/d3124ac33e1407ced092deb2e8854471773786d4/setuptools/dist.py#L797). Changing that would be very complex, specially in a backwards compatible way.

Therefore I would say there are no plans to support this (so far)...

Of course we are always open to reviewing any PR if you want to create one. However it would be nice to discuss any proposals you might have before an implementation.

Please let me know if you would like to pursue this idea, otherwise I think we can close this issue.

**Comment by abravalheri** [comment]
Hi @Rezzie, I think I will close this issue for now, but please let us know if you would like to propose a PR and discuss and implementation proposal.
