### ISSUE TITLE
DeprecationWarning in Python 3.6 and 3.7

### ISSUE THREAD

**Issue by uri-rodberg** [pypa/setuptools#1933]
I receive a DeprecationWarning when using setuptools on Travis CI.

`DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses`

https://travis-ci.org/speedy-net/speedy-net/builds/620458854

https://travis-ci.org/speedy-net/speedy-net/builds/514284524

https://travis-ci.org/speedy-net/speedy-net/builds/514595887

**Comment by jaraco** [comment]
What version of Setuptools? In #1855, released as v41.6.0, the deprecated behavior should be removed.

**Comment by jaraco** [comment]
Now that I look at the tracebacks for the errors in those builds, Setuptools is not implicated. Instead, the 'import imp' calls were happening with `distutils/__init__.py`.

What I don't yet understand is that although those runs look like they're using Python 3.7.1, if I look at the code for Python 3.7.1, the `distutils/__init__.py` doesn't import `imp`. So I really don't know what's going on. Regardless, this issue was addressed in Setuptools.

If you think there are outstanding issues with Setuptools with regards to imp, please don't hesitate to re-open or comment and ping me so we can investigate further.
