### ISSUE TITLE
setuptools 45.0.0 gets installed on a python 2.7 virtualenv

### ISSUE THREAD

**Issue by romaingz** [pypa/setuptools#1964]
Hello,

I have a CI job that creates a virtualenv from an old version (relying on `pip==8.1.2`) with python 2.7.

I then ask `pip` to update `setuptools wheel pip`.
In the process it installs `setuptools==45.0.0` and updates `pip==19.3.1`.

The rest of the CI fails because `pip` refuses to install the other dependencies due to `setuptools` incompatibility with python 2.7.

I believe that this could be avoided by removing:
```cfg
[bdist_wheel]
universal = 1
```
from `setup.cfg`.

What is the reason for keeping this option in the cfg?

**Comment by hugovk** [comment]
The new setuptools 45 includes `python_requires = >=3.5`, so it shouldn't be installed on Python 2, and it should find the previous setuptools 44 which matches.

* https://github.com/pypa/setuptools/blob/v45.0.0/setup.cfg#L50

However, you need pip 9+ to use the `python_requires` metadata, and you have pip 8.

I suggest first upgrading pip, and then upgrading other packages after that. For example:

```
pip install -U pip
pip install -U setuptools wheel
```

**Comment by bbugyi200** [comment]
> The new setuptools 45 includes `python_requires = >=3.5`, so it shouldn't be installed on Python 2, and it should find the previous setuptools 44 which matches.
> 
> * https://github.com/pypa/setuptools/blob/v45.0.0/setup.cfg#L50
> 
> However, you need pip 9+ to use the `python_requires` metadata, and you have pip 8.
> 
> I suggest first upgrading pip, and then upgrading other packages after that. For example:
> 
> ```
> pip install -U pip
> pip install -U setuptools wheel
> ```

@hugovk This didn't seem to work for us. Our current workaround is to run
```python
pip install -U pip
pip install setuptools==44.0.0
```
before installing the rest of our dependencies.

**Comment by exarkun** [comment]
> 
> @hugovk This didn't seem to work for us. Our current workaround is to run
> 
> ```python
> pip install -U pip
> pip install setuptools==44.0.0
> ```
> 
> before installing the rest of our dependencies.

I also had to ask for `setuptools==44.0.0` explicitly.  There is already a setuptools installed in the virtualenv, by the older version of pip, and I guess pip won't downgrade to a working version if you only do `pip install -U setuptools`.

**Comment by fungi** [comment]
bdist_wheel.universal=1 is still a problem though, because it results in a py2.py3 wheel, which inherently means the file is expected to work with at least some Python 2 interpreter. If this file winds up in a local wheelhouse or a remote one served with an unintelligent index rather than PyPI itself (e.g., Apache mod_autoindex) then pip on Python 2.7 will attempt to install it anyway rather than selecting an older version.

**Comment by pganssle** [comment]
> bdist_wheel.universal=1 is still a problem though, because it results in a py2.py3 wheel, which inherently means the file is expected to work with at least some Python 2 interpreter.

This is an odd situation because `setuptools == 45` *is* intended to work, but `pip` will hard fail when installing it because of `python_requires`. The latest version of `setuptools` actually does support Python 2, it just says otherwise. This was supposed to be a "soft drop" of Python 2 support, but that's not the actual failure mode most people are seeing (as far as we can tell).

**Comment by Phzytaylor** [comment]
Broke my virtualenv as well. I can't get it to run even with previous versions.

**Comment by gokuatkai** [comment]
The wheel name of new setuptools is `setuptools-45.0.0-py2.py3-none-any.whl` is should not contain py2 is it doesn't support python2.x

**Comment by sagalovsky** [comment]
For us this "setuptools v45.0.0 on python 2" issue broke the ```virtualenv``` creation itself. 
Added the ```--no-setuptools``` flag to the ```virtualenv``` call as a workaround (looks like we didn't really need ```setuptools``` besides the part vendored in ```pip```):
`virtualenv --no-wheel --no-setuptools --system-site-packages foo_env`

**Comment by romaingz** [comment]
@jaraco could you maybe explain the reason for keeping a py2-py3 wheel even though it declares itself as requiring Python3?

**Comment by jaraco** [comment]
Here's how to replacate the OP's issue:

```
~ $ python2.7 -m virtualenv --no-setuptools env
~ $ env/bin/pip install --ignore-requires-python setuptools==45                                                                         
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting setuptools==45
  Downloading https://files.pythonhosted.org/packages/af/e7/02db816dc88c598281bacebbb7ccf2c9f1a6164942e88f1a0fded8643659/setuptools-45.0.0-py2.py3-none-any.whl (583kB)
     |████████████████████████████████| 593kB 3.8MB/s 
Installing collected packages: setuptools
Successfully installed setuptools-45.0.0
~ $ env/bin/pip -V                                                                                                                      
pip 19.3.1 from /Users/jaraco/env/lib/python2.7/site-packages/pip (python 2.7)
~ $ env/bin/pip install twine                                                                                                           
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting twine
  Downloading https://files.pythonhosted.org/packages/23/0e/9e833399b84e9232a7f86a8f4351d6687dbab0b03a2a6e352d431463fa68/twine-1.15.0-py2.py3-none-any.whl
Collecting requests-toolbelt!=0.9.0,>=0.8.0
  Using cached https://files.pythonhosted.org/packages/60/ef/7681134338fc097acef8d9b2f8abe0458e4d87559c689a8c306d0957ece5/requests_toolbelt-0.9.1-py2.py3-none-any.whl
Requirement already satisfied: setuptools>=0.7.0 in ./env/lib/python2.7/site-packages (from twine) (45.0.0)
ERROR: Package 'setuptools' requires a different Python: 2.7.16 not in '>=3.5'
```

> could you maybe explain the reason for keeping a py2-py3 wheel even though it declares itself as requiring Python3?

I aimed to limit the changes to setuptools 45 except dropping the _declared_ support for Python 2 (by way of `python_requires`). It is still a universal wheel and installable on Python 2 with `pip install --ignore-requires-python` is used.

> I also had to ask for setuptools==44.0.0 explicitly.

If pinning is necessary, I would recommend `setuptools<45` instead (to continue to get features/updates in 44.x).

> I believe that this could be avoided by removing [universal wheel]

I'm not so sure. I'm pretty sure pip would still install setuptools 45 from sdist.

```
~ $ env/bin/pip install --ignore-requires-python --no-binary=:all: setuptools==45                                                       
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting setuptools==45
  Downloading https://files.pythonhosted.org/packages/fd/76/3c7f726ed5c582019937f178d7478ce62716b7e8263344f1684cbe11ab3e/setuptools-45.0.0.zip (859kB)
     |████████████████████████████████| 860kB 3.7MB/s 
Skipping wheel build for setuptools, due to binaries being disabled for it.
Installing collected packages: setuptools
    Running setup.py install for setuptools ... done
Successfully installed setuptools-45.0.0
```

> I have a CI job that creates a virtualenv from an old version (relying on pip==8.1.2) with python 2.7.

I'm unable to replicate the issue with the latest virtualenv.

```
~ $ python2.7 -m pip-run virtualenv -- -m virtualenv env                                                                                
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting virtualenv
  Using cached https://files.pythonhosted.org/packages/05/f1/2e07e8ca50e047b9cc9ad56cf4291f4e041fa73207d000a095fe478abf84/virtualenv-16.7.9-py2.py3-none-any.whl
Installing collected packages: virtualenv
Successfully installed virtualenv-16.7.9
New python executable in /Users/jaraco/env/bin/python
Installing setuptools, pip, wheel...
done.
~ $ env/bin/pip -V                                                                                                                      
pip 19.3.1 from /Users/jaraco/env/lib/python2.7/site-packages/pip (python 2.7)
~ $ env/bin/easy_install --version                                                                                                      
setuptools 44.0.0 from /Users/jaraco/env/lib/python2.7/site-packages (Python 2.7)
```

Perhaps upgrading virtualenv in your stack is the best solution?

It sounds like the `virtualenv --no-setuptools` option is a also suitable workaround for the reported issue.

Please confirm your concerns are addressed.

**Comment by jaraco** [comment]
> bdist_wheel.universal=1 is still a problem though

If you believe this is an issue, please file a separate issue for it. Thanks.

**Comment by exarkun** [comment]
> If pinning is necessary, I would recommend setuptools<45 instead (to continue to get features/updates in 44.x).

In this case `setuptools~=44` (any 44.x) is probably better, then.  `<45` may leave you with setuptools 36 or something else highly undesirable.

**Comment by fungi** [comment]
> > bdist_wheel.universal=1 is still a problem though
> 
> If you believe this is an issue, please file a separate issue for it. Thanks.

I don't feel strongly about it since we worked around the problem by explicitly excluding setuptools from our wheelhouse caches. Maybe others do, I won't speak for them. The reason I mentioned it within this issue is that we wouldn't have ended up attempting to install it in our Python 2.7 virtualenvs if it had been built as py3-only (consistent with its python_requires value) rather than universal.

**Comment by laurent-laporte-pro** [comment]
> Added the `--no-setuptools` flag to the `virtualenv` call as a workaround (looks like we didn't really need `setuptools` besides the part vendored in `pip`):
> `virtualenv --no-wheel --no-setuptools --system-site-packages foo_env`

**note:**

The `--no-setuptools` options is available since [virtualenv v1.9](https://virtualenv.pypa.io/en/latest/changes/#v1-9-2013-03-07) which was released on 2013-03-07.
- If you have an old version of Python 2.7, for instance 2.7.3, you may not have virtualenv v1.9.
- Around the same date, [pip v1.3](https://pip.pypa.io/en/stable/news/#id264) was released. This version doesn't support the `python_requires` flag. You need to wait for the 9.0.0 version which was released on 2016-11-02.

So, old Python installations (before 2016-11-02), which use pip < 9 don't understand the flag `python_requires >=3.5` and install setuptools v45.0.0 anyway!

Do you have any suggestion ? Should we upgrade virtualenv ? Or install a recent version of Python 2.7 ?

**Comment by jaraco** [comment]
I don't think upgrading Python will help. If you have an old version of virtualenv which pulls in an old version of pip and doesn't have the no-setuptools option, then yes, I recommend upgrading virtualenv. Is that a reasonable proposition?

**Comment by romaingz** [comment]
@jaraco Thank you for your answer.

To be clear, I have fixed my problem the day I opened this issue since I have access to my CI.

But working in an industrial environment I know that not everyone has the same level of freedom, and some might get stuck with old dependencies or tools that they cannot update easily.

I was wondering if `setuptools` was okay with this philosophy of breaking CIs that were working prior to 45.0, and if it was the case I was curious to know why.

> > I believe that this could be avoided by removing [universal wheel]
>
> I'm not so sure. I'm pretty sure pip would still install setuptools 45 from sdist.

Since I am not sure if this is the case (and unfortunately do not have the time to check) I won't open a separate issue for it either.

**Comment by jaraco** [comment]
> I was wondering if `setuptools` was okay with this philosophy of breaking CIs that were working prior to 45.0, and if it was the case I was curious to know why.

Setuptools is definitely not okay with breaking environments. It's a regrettable breakage and might even warrant reverting the change, depending on impact. My expectation in this change was that installations with pip 9 and later would be protected against setuptools 45 and other environments would end up with setuptools 45 (but compatibility would be retained with a warning).

What I was not anticipating was this pathway through virtualenv where users have a limited control over the environment creation, and so I'm grateful for the civil and respectful tone as we explore this aspect of the landscape.

My hope is that this use-case is rare enough and easy enough to work around that we (our users) can bear the pain in the short term in order to move forward with the plans toward the future.

I'm going to close this issue, but please comment or re-open if there are additional use-cases or considerations not addressed above.
