### ISSUE TITLE
The setuptools 45 wheel has an incorrect py2.py3 tag

### ISSUE THREAD

**Issue by sbidoul** [pypa/setuptools#1974]
Arriving from https://github.com/pypa/pip/issues/7610.

The wheel for setuptools 45 on PyPI has the `py2.py3` tag in its file name.

Since that version does not support python 2 it should have the `py3` tag.

**Comment by jaraco** [comment]
I have several concerns with the proposed solution (#1977, #1978) to remove the 'universal' indicator.

- The indicator is meant to indicate the applicability of the package to the wheel to the target platform, and since this wheel does still have Python 2 compatibility in the source, it's technically still correct to advertise the wheel as universal.
- The fact that pip happens to use this setting as a proxy for applicable packages in `find-links` (and ignores `python-requires`) feels like a bit of a hack.
- This package does correctly declare its Python support in two ways (through Requires-Python and through Trove classifiers), so this is a third way to declare the package's Python support.

And if you loop in #1972, this requirement demands that moving a package from Python 2/3 support to Python 3-only support requires many changes:

- update python_requires
- remove Python 2 from Trove classifiers
- add Python 3 Only to Trove classifiers
- drop universal wheel

That seems like a awful lot of (redundant) steps for a single operation. It's enough work with enough opportunities to get it wrong that it probably demands some documentation. I'll implement these changes in my jaraco/skeleton project to apply to the other projects I maintain that have dropped Python 2 support.

**Comment by jaraco** [comment]
Fixed with #1978.
