### ISSUE TITLE
setup_requires deprecated

### ISSUE THREAD

**Issue by YoSTEALTH** [pypa/setuptools#1989]
If ``setup_requires`` has been deprecated, it should have been made clear in the documentation.

https://setuptools.readthedocs.io/en/latest/setuptools.html

People aren't magically going to know this.

I wasted a lot of time trying to get ``setup_requires`` to work, just to find out it does NOT work!!!

**Comment by pganssle** [comment]
The situation is more complicated than that, really, but it's definitely true that the documentation on many aspects of this project, and the communication around it, needs improvement.

I have closed this issue because it appears to be a complaint about our prior behavior rather than an action for us to take.
