### ISSUE TITLE
EntryPoint doesn’t support all module names

### ISSUE THREAD

**Issue by NorbertLindenberg** [pypa/setuptools#2012]
The regular expression for entry point definitions (EntryPoint.pattern) is too restrictive with regards to module names. It uses `[\w.]+`, which according to the [re module description](https://github.com/python/cpython/blob/3.8/Lib/re.py) means “the range of Unicode alphanumeric characters (letters plus digits plus underscore)”. [Python identifiers](https://docs.python.org/3/reference/lexical_analysis.html#identifiers) allow several additional Unicode categories, in particular nonspacing marks and spacing combining marks. Several of the world’s most widely used languages, such as Hindi and Bengali, cannot be written without such marks.

**Comment by abravalheri** [comment]
Hi @NorbertLindenberg, thank you very much for bringing this issue up.

Since this is part of a [packaging spec](https://packaging.python.org/en/latest/specifications/entry-points/), it would be necessary to discuss this issue in https://discuss.python.org/c/packaging/14 (so all the tools involved in the process, e.g. pip/build, can also be updated).

Could you please start a conversation about this topic there?

**Comment by abravalheri** [comment]
(Please correct me if I understood something wrong here, if this is a setuptools specific problem, could you please provide an reproducible example that we can verify? I would be more than happy to re-open the issue)
