### ISSUE TITLE
Invoking build via the API

### ISSUE THREAD

**Issue by RDIL** [pypa/setuptools#2021]
So recently, I have wanted to be able dynamically generate and run a `setuptools.setup` build without having to write a setup file, and invoking `python3 setup.py sdist bdist_wheel`, and I think if it was possible to just do something like
```python
setuptools.setup(
    formats="sdist bdist_wheel"
    # other meta
)
```
to simplify the process, it would be a huge help.

If this is possible, please let me know.

**Comment by pganssle** [comment]
@RDIL Can you clarify exactly what you are asking for here? You can already invoke a build programatically with `setuptools.build_meta`, which exposes a [PEP 517-compatible build backend](https://www.python.org/dev/peps/pep-0517/).

There's a library, [pep517](https://pypi.org/project/pep517/), that makes it easy to build a PEP 517 frontend, and you can even invoke the builds directly with `python -m pep517.build`, see [this tox env](https://github.com/matplotlib/grid-strategy/blob/35587d59cf3880dd5c240ad3f2301c5c4e41da86/tox.ini#L50-L57).

It's not really clear what you mean by "without having to write a setup file", since you seem to be suggesting the addition of a key into the `setup` keyword in the `setup.py` file...

**Comment by RDIL** [comment]
Well so right now I am taking a bunch of options and generating a "setup.py" using a lot of string joining with those options, and I was wondering if there was an easy way to invoke the `setuptools.setup` without having to write it to a file and then run that file with the `sdist bdist_wheel` arguments, so I'll take a look at what you linked.
