### ISSUE TITLE
Support the subdirectory=... fragment in dependency_links

### ISSUE THREAD

**Issue by pschanely** [pypa/setuptools#2027]
Apologies in advance for this naive feature request - I am blissfully ignorant about a lot of the  infrastructure here.

Pip supports a url fragment with something like `#subdirectory=...` to express that the package should be installed from somewhere other than the root. 

When searching `dependency_links`, it looks like setuptools [matches on the entire URL fragment](https://github.com/pypa/setuptools/blob/24fa288a98a14e6ec57b996b151a48203322c936/setuptools/package_index.py#L32) for an `egg=...` bit, which means that we cannot have dependencies that use the `subdirectory` option too. Would we be willing to support such a feature?

**Comment by fernandoTB** [comment]
i'm facing the same problem, it would be great to have this feature.

**Comment by abravalheri** [comment]
Hi @pschanely and @fernandoTB, I am afraid the usage of setuptools as an installer (e.g. via `easy_install`) is deprecated, and therefore it would make very little sense to implement this feature :(

But since you have mentioned that `pip` supports the fragments, would it make sense for you to use `pip` instead?
