### ISSUE TITLE
Support for interpreter argument in console_scripts.

### ISSUE THREAD

**Issue by ghost** [pypa/setuptools#204]
Originally reported by: **nilp0inter (Bitbucket: [nilp0inter](http://bitbucket.org/nilp0inter), GitHub: [nilp0inter](http://github.com/nilp0inter))**

---

HI

Is there any way of adding custom arguments to the shebang of the console_scripts generated?

If it's not possible, I'd like to propose the addition of such feature.

We are experiencing problems using some libraries (like wsgiref) that are doing "assert" internally. It is impossible to desactive them unless you use the "-O" parameter in the interpreter.

Thank you.

---
- Bitbucket: https://bitbucket.org/pypa/setuptools/issue/204

**Comment by abravalheri** [comment]
Since the Python package ecosystem has moved towards standardisation in the last years, I think it would be better to discuss this proposals in https://discuss.python.org/c/packaging.

It would probably need a PEP, because it requires changing existing standards (https://packaging.python.org/en/latest/specifications/entry-points/).

I think the best would be closing this issue in the context of setuptools, for the time being.
If the community reaches consensus in the packaging forum I would be glad to continue with this conversation in a future proof of concept or PR 😄
