### ISSUE TITLE
I want to start the ROS but always get Error when type catkin_make , I can't fix it...

### ISSUE THREAD

**Issue by Huang-TsungHsuan** [pypa/setuptools#2045]
Base path: /home/design/catkin_ws
Source space: /home/design/catkin_ws/src
Build space: /home/design/catkin_ws/build
Devel space: /home/design/catkin_ws/devel
Install space: /home/design/catkin_ws/install
####
####
CMake Error at CMakeLists.txt:20 (message):
  Search for 'catkin' in workspace failed (catkin_find_pkg catkin
  /home/design/catkin_ws/src): Traceback (most recent call last):

    File "/home/design/anaconda3/bin/catkin_find_pkg", line 3, in <module>
      import re
    File "/home/design/anaconda3/lib/python3.7/re.py", line 143, in <module>
      class RegexFlag(enum.IntFlag):

  AttributeError: module 'enum' has no attribute 'IntFlag'

-- Configuring incomplete, errors occurred!
See also "/home/design/catkin_ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/design/catkin_ws/build/CMakeFiles/CMakeError.log".
Makefile:3370: recipe for target 'cmake_check_build_system' failed
make: *** [cmake_check_build_system] Error 1
Invoking "make cmake_check_build_system" failed

I tried a lot of ways on the internet but still....plz help me :(

**Comment by abravalheri** [comment]
Hi @Huang-TsungHsuan, I am afraid I cannot see how this example is related to setuptools... Do you have more information about how setuptools is being used here? (It seems that everything uses cmake instead...)

Given the error you are seeing, I guess your computer might have an old 3rd party [`enum`](https://pypi.org/project/enum/) package installed that is shadowing the `enum` module in the stdlib? Would that be the case? (If that is the case you could try uninstalling the 3rd party `enum`...)

For the time being I will close this issue, since it seems unrelated. But please feel free to re-open it if you have more information that relates the problem to setuptools.
