### ISSUE TITLE
Add a way to specify options passed to python executable for `console_scripts`

### ISSUE THREAD

**Issue by jack1142** [pypa/setuptools#2049]
I would like to be able to have entry points (`console_scripts`) use `-O` flag so that `assert` statements won't run in entry point as the entry point is intended for end users not developers. Adding a way to specify interpreter flags for entry points would allow that.

I'm looking specifically for an option that I could pass to package's `setup()` which would make entry points (`console_scripts`) use `-O` flag by default (so that for example, simple `python -m pip install -U package_name` would install the package's entry points with optimizations enabled)

**Comment by pganssle** [comment]
Unless I'm wrong, I don't think we actually generate the entry points anymore, that's something that `python setup.py install` was doing, and I do *not* recommend using that method, since those entry points are not very good.

It looks like what we do is generate an `entry_points.txt` file, and `pip` generates a script for you.

I more or less agree that this is a useful feature, but it might be a kind of big standardization issue to get it to work (since the natural place to specify it would be in the `entry_points.txt` file).

I think there may be a workaround where you don't use the "entry points" feature and instead generate and ship your own scripts, but that may have other issues and could be harder to maintain.

**Comment by jack1142** [comment]
I thought that `python setup.py ...` just runs `setup.py` in current directory and usually that file contains something like:
```py
from setuptools import setup

setup(...)
```
Which would mean that `setup()` is imported from setuptools.

**Comment by pganssle** [comment]
@jack1142 Yes, but you shouldn't be calling `python setup.py install` (and you aren't in this case). You can see how this works by creating a wheel for your project and inspecting it (it's just a zip file). If you do `pip wheel --no-dependencies -w dist/ .` in your project's directory, the wheel file you generate should be a zip file with a folder {myproject}-{version}.dist-info/ at the top level with an `entry_points.txt` file in it that looks something like this:

```
[console_scripts]
entry_point = myproject.__main__:main
```

If you then do `pip install path/to/wheel -t tmp` instead and inspect `tmp/bin/`, you'll see a script with your entry point installed there, which looks something like this:

```python 
#!/full/path/to/python
# -*- coding: utf-8 -*-
import re
import sys
from myproject.__main__ import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```

`setuptools` is only involved in the *first* step (creating the wheel). Whatever you use to do the installation (`pip`) needs to generate the scripts for the entry points. I don't think there's anything we can do to influence the form that that script takes, though.

**Comment by abravalheri** [comment]
Hi @jack1142, given @pganssle explanation I think we can close this issue for now right? (`pip` is the one generating the script wrappers, so the changes would have to implemented there... however this would need a standardisation effort to change the [entry-points specification](https://packaging.python.org/en/latest/specifications/entry-points/))
