### ISSUE TITLE
Setuptools started installing .egg files in site-packages that won't import 

### ISSUE THREAD

**Issue by bwllc** [pypa/setuptools#2059]
Hello everyone:

Two or three days ago, I started having issues with building packages using setuptools.  My problem is occurring in both an Anaconda environment on Windows, and in a Linux environment with no virtual environment in use.  I'm on the Linux system right now.  The configuration is Ubuntu 19.10, Python 3.7.5, and setuptools 43.0.0.

I have two modules of Python source code that I am developing.  I regularly change this code and "distribute" it to myself using setuptools.  From the command prompt in the module's base folder, I execute:

```
python3 setup.py sdist
sudo python3 setup.py install
```

That process has worked for me for years.  But after recent rebuilds, changes to my source code were not showing up when I imported the module. 

I looked in `/usr/local/lib/python3.7/dist-packages`.  My two packages appeared twice each: once as normal sub-folders, and those sub-folders were old.  Newer versions were also present, however, they had the .egg extension at the end of their file names.  Oddly, one of the two modules is a single .egg archive file, and the other is a normal folder with folders inside it, despite the .egg extension in the name.

I tried deleting the working, but obsolete versions of my modules in site-packages.  After doing that: when I tried to import those modules in Python, I got ModuleNotFoundErrors.  The .egg files and/or folders that have been placed in my site-packages folder are not importable as-is.

I tried importing other modules that were listed in site-packages.  The folder names do not have the .egg extensions.  They were mostly installed by pip3.  These packages work fine.  A third software package of my own design appears as a normal sub-folder within dist-packages, and it also imports correctly.  I did build this package using setuptools, just not recently.  The last build was on January 23.

I hope you can help me to understand why setuptools appears to have changed its installation behavior, and how to correct it.  Thanks!

**Comment by jaraco** [comment]
@bwllc : First, I would note that if you're using Setuptools 43, that was released in December, so it's unlikely that it was something that setuptools changed that triggered this recent degradation.

Most likely what's happening is your eggs are not ending up on Python's sys.path. When setuptools/easy_install installs a package as an egg, it adds a reference to the egg to a file called `easy-install.pth` and as long as `easy-install.pth` is considered a site directory ([details here](https://docs.python.org/3/library/site.html)), those eggs (which are just zip files) will be added to `sys.path` during startup. If they're not added to `sys.path` at startup, you'll get the behavior you observe (packages appear not to be installed).

To figure out which directories are your site packages:

```
>>> import site
>>> site.getsitepackages()
['/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages']
```

If `/usr/local/lib/python3.7/dist-packages` is not there, that's probably the source of your problem. You may want to investigate deeper to find out why/how that might have changed recently.

Right now, the problem you describe is local to your environments. If you can provide instructions on how to replicate the issue in a clean environment (such as with a Dockerfile), we may choose to investigate, though probably not because...

Most importantly, however, is that the technique you're using (`setup.py install`) is discouraged. You should instead use the recommend procedure of `pip install .`. That will install your package using a supported mechanism and bypass the gnarly details about `.pth` files and eggs.

I hope that helps.
