### ISSUE TITLE
Support for custom interpreter flags in entry_points console scripts

### ISSUE THREAD

**Issue by ghost** [pypa/setuptools#212]
Originally reported by: **chadrik (Bitbucket: [chadrik](http://bitbucket.org/chadrik), GitHub: [chadrik](http://github.com/chadrik))**

---

I need to be able to set custom interpreter options in my scripts (e.g. `#!python -E`) for a package I'm developing. If these flags are specified in the first line of a script they will be preserved by setuptools when the interpreter is expanded during installation, which is great.  However, I would like to use setuptools' entry_points/console_scripts feature to generate .exes on windows, and AFAIK interpreter flags are not supported by entry_points.

I was thinking it could be possible to use the extras data parsed by `pkg_resoruces.EntryPoint` class to provide this information. e.g.:

```
#!python

setup(
    entry_points={'console_scripts':['myscript=mymodule:main [-E,-S]']
    ...
)
```

Setuptools would need to be modified to preserve those extras through to the script building functionality.

---
- Bitbucket: https://bitbucket.org/pypa/setuptools/issue/212

**Comment by jhhcs** [comment]
I would be very interested in this in order to install console scripts that run with the `-O` flag enabled to remove costly assertions.

**Comment by abravalheri** [comment]
Hi chadrik and jhhcs, since the Python package ecosystem has moved towards standardisation in the last years, I think it would be better to discuss these proposals in https://discuss.python.org/c/packaging, and they would probably need a PEP.

Since these 2 proposals (identifying editable installs and default flags for scripts) sound like amendments in (or are at least related to) 2 existing standards (https://packaging.python.org/en/latest/specifications/entry-points/ and PEP 660), I think the best would be closing this issue in the context of setuptools, for the time being.

If the community reaches consensus in the packaging forum I would be glad to continue with this conversation in a future proof of concept or PR 😄
