### ISSUE TITLE
Incompatible install in (You are running Setuptools on Python 2, which is no longer supported and >>> SETUPTOOLS WILL STOP WORKING <<< in a subsequent release (no sooner than 2020-04-20). Please ensure you are installing Setuptools using pip 9.x or later or pin to `setuptools<45` in your environment. If you have done those things and are still encountering this message, please follow up )

### ISSUE THREAD

**Issue by jaswanthraghu007** [pypa/setuptools#2132]
## Prerequisites

- [x] Python 2 is required for this application.
- [x] I maintain the software that installs Setuptools (if not, please contact that project).
- [x] Setuptools installed with pip 9 or later.
- [x] Pinning Setuptools to `setuptools<45` in the environment was unsuccessful.

## Environment Details

- Operating System and version:
- Python version:
- Python installed how:
- Virtualenv version (if using virtualenv): n/a

Command(s) used to install setuptools (and output):

```
```

Output of `pip --version` when installing setuptools:

```
```

**Comment by McSinyx** [comment]
@pganssle, since both you and @jaraco agree that these should be closed and flagged as invalid, should I stop commenting [Could you please provide further details?](https://github.com/pypa/setuptools/search?q=Could+you+please+provide+further+details%3F&type=Issues) and could you please close these issues since none of them ever responded?

**Comment by pganssle** [comment]
@McSinyx I probably would stop, yeah. We should probably get rid of this template and whatever is encouraging people to submit it blank.

**Comment by McSinyx** [comment]
Thanks, and for the context, as per GH-2094, it seems that users (mistakenly) use the template to report that *they've encountered the warning*.  I found 734eec6e3fca725c6b18cad2fffbd1f3e3a56fa7 but couldn't find the discussion behind it.

**Comment by jaraco** [comment]
Right - I made that change (summarily, without discussion), in the hopes of ferreting out any more details about users encountering the warning. As it turns out, the type of user who is encountering these errors appears to be users inexperienced with open source and incapable of reading [the directions](https://github.com/pypa/setuptools/blame/master/.github/ISSUE_TEMPLATE/setuptools-warns-about-python-2-incompatibility.md#L12).

I do believe it's time to drop support for Python 2 (break the users), but I'll first want to update that bit.ly link to point to some page giving users guidance on what to do if they encounter the warning (now) or the error (after dropping support).
