### ISSUE TITLE
install_requires pulls in Py3-only package when Py2-compatible is available

### ISSUE THREAD

**Issue by neirbowj** [pypa/setuptools#2275]
# Scenario

Installing under Python 2. The dependency has dropped support for Python 2 upstream, but a version is still available that is Python 2-compatible.

# How to reproduce

```
#!/usr/bin/env python

from setuptools import setup

setup(
    name='completely_different',
    version='0.1.0',
    install_requires=['zipp']
)
```

```
$ python2 -m virtualenv venv-setuptools
$ venv-setuptools/bin/python setup.py install
```

# Expected behavior

Got zipp<2.0.0, when zipp dropped support for Python 2.

# Observed behavior

Got zipp==3.1.0, which is latest as of this moment.

# Notes

```
$ python2 -m virtualenv venv-pip
$ venv-pip/bin/pip install zipp
```

Installs zipp 1.2.0.

I think I have isolated the responsible code to somewhere in `pkg_resources` but get lost trying to go further.

Yes, I know Python 2 is EOL. No, I don't want to still be maintaining software that depends on it either.

**Comment by pganssle** [comment]
@neirbowj We dropped support for Python 2 some time ago, so it's not really possible for us to fix this upstream at this point.

It is also recommended to *not* invoke `setup.py install`. Instead you should use `pip install`, which will properly respect the `Python-Requires` attribute. We're having some trouble properly deprecating `setup.py install` because it's used in a few valid places and we haven't had the resources to properly start emitting deprecating warnings quite yet. Sorry about that.

Closing this as there's not really any action we can take and even if we could this can be fixed by using `pip`.

Thanks for the report, sorry if it is a disappointing outcome.

**Comment by neirbowj** [comment]
@pganssle "It is also recommended to not invoke setup.py install" Oh? Good to know. Any way to put that in a deprecation warning that shows up when somebody runs `setup.py install`?

**Comment by pganssle** [comment]
> Any way to put that in a deprecation warning that shows up when somebody runs `setup.py install`?

Like I said, this is trickier than it seems, because some supported paths invoke `setup.py install` under the hood, and it requires a bit of coordination to properly deprecate it.

**Comment by neirbowj** [comment]
Oof. That's rough. OK, thank you for the advice.
