### ISSUE TITLE
Obsolete error message when MS Visual C++ Build Tools missing

### ISSUE THREAD

**Issue by arencambre** [pypa/setuptools#2302]
**Environment**

* pip version: 20.2.1
* Python version: 3.8.3
* OS: Windows 10 (fully patched, on latest release)

**Description**

When installing a module that needs Microsoft's Visual C++ Build Tools, and these tools are not present, this message is displayed:
`error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/`

This message is erroneous for a few reasons:

- There is no such product at https://visualstudio.microsoft.com/downloads/. I think https://visualstudio.microsoft.com/visual-cpp-build-tools/ is the correct URL.
- Version 14 probably not required. It may be a minimum requirement, not absolute. That should be validated before updating the language.
- People who already have Visual Studio installed probably should [modify their installation](https://docs.microsoft.com/en-us/cpp/build/vscpp-step-0-installation) instead of downloading build tools. The warning message doesn't say that. If you install build tools along with Visual Studio, you may [run into issues](https://stackoverflow.com/questions/40504552/how-to-install-visual-c-build-tools).

In my case, I no longer got this error after adding C++ support to my Visual Studio 2017 installation per the link above. That validates that:

1. the build tools can be installed as a component of Visual Studio instead of separately
2. version 14 is not strictly required (Visual Studio 2017 = version 15.9.25)

**Expected behavior**

Error message wording should be accurate and not encourage undesirable choices.

**How to Reproduce**

Install a package that needs to be compiled with C++. For example: `python -m pip install wordcloud`

**Output**

The output ends with this:
```
error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
```

**Comment by jaraco** [comment]
Feel free to send a PR. The [code is here](https://github.com/pypa/setuptools/blob/f991fbb3c9d0e10a0a78ae2b508b3fd99f9cdef2/setuptools/msvc.py#L361-L362).

**Comment by arencambre** [comment]
Done! PR ready.

Thinking ahead--is Python's documentation an appropriate place for this info? The links, version requirements, etc. are volatile, so I wonder if the code should just have a link to the appropriate Python doc URL?

**Comment by BoarGules** [comment]
The remark "version 14 is not strictly required" is quite untrue in practice.

Method `MSVCCompiler.query_vcvarsall()` determines if there is a compiler installed by searching for the file `vcvarsall.bat`, which exists in 14.2. Failing that, it then recommends the user download Visual C++ 14.2) which is no longer readily available. It _can_ be downloaded, but only if you have a paid subscription. The link in the error message points to `https://visualstudio.microsoft.com/downloads/` which does indeed work, but the only compiler available free from that page is Visual Studio 2019 (a.k.a. version 16). That compiler does not satisfy the `query_vcvarsall()` test because the counterpart of `vcvarsall.bat` in 16.0 is `VsDevCmd.bat`. 

In fact even if you have VC++ 14.2, `distutils` still gets things wrong, presumably holdovers from earlier versions of VC++.
First one must work out the correct values for environment variables LIBPATH and INCLUDE. After that, to make a compile work using the command lines that `distutils` issues, it is also necessary to copy the contents of `C:\Program Files (x86)\Windows Kits\10\Lib\10.0.10240.0\ucrt\x64` and  `C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\lib\amd64` to a new folder `Pythonxx\PCBuild\amd64` which `distutils` puts as a LIBPATH parameter to `link.exe` but which does not actually exist. Likewise it is necessary to copy `C:\Program Files (x86)\Windows Kits\10\bin\x64\rc.exe` to an existing folder `C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64` because `distutils` knows the executable is there but Microsoft reckons otherwise.

All of this probably a doddle if you are a seasoned MSC programmer, but (I speak from experience) painful to someone who switched from Python around the time when Visual C 3 came out. And quite out of reach for a Python beginner who gets this message from PIP when he tries to install `numpy`. That happened [today](https://stackoverflow.com/questions/64237904/numpy-installation-for-python-ver-3-9/64260883#64260883).

So it is not just the message that is obsolete: the whole of `distutils.msvc9compiler` needs attention paid not just to what it says but to what it does. It is of course entitled to insist on one and only one MS compiler to do what it does, but it must be one that is readily available, and the command lines it issues should work on a vanilla installation of that compiler, without the user having to modify the folder layout to put files where `distutils` expects them to be.

**Comment by arencambre** [comment]
@BoarGules great observations. You may be right, and if so, the wording change I suggested may need further revision.

This confirms what I wrote in https://github.com/pypa/setuptools/issues/2302#issuecomment-674564732, that this really needs to be documented in web documentation, and Python merely include a link to that document. Then further revisions just need a web edit instead of a new build.

**Comment by dofuuz** [comment]
Maybe it would be better to link https://aka.ms/vs/15/release/vs_buildtools.exe directly if VS 2019 is not supported.
(It's direct link for MS VS 2017 Build tools https://docs.microsoft.com/en-us/visualstudio/install/build-tools-container?view=vs-2017)

**Comment by BoarGules** [comment]
@dofuuz I believe that all of my remarks have been addressed because it seems to me that recent versions of `pip` are no longer picky about the version of the C compiler. The message about 14.2 still appears when new users try to install `numpy` for older versions of Python. There is unfortunately not much to be done about old wheels.

**Comment by jacalata** [comment]
@arencambre I think this issue is fixed and can be closed?
