### ISSUE TITLE
Systematic error when running vcvarsall.bat on Windows 10

### ISSUE THREAD

**Issue by MilanSkocic** [pypa/setuptools#2307]
I'm dealing with a systematic error when building an C extension with the Microsoft compiler. I systematically get this error:

`error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com downloads/`

However, Visual Studio 2019 is installed and works properly.

I tried to track down where the error is raised. The exception is raised in the `msvc.py` file in the function  `_msvc14_get_vc_env(plat_spec)`.  I put print statements in order to see if the `vcvarsall ` and `vcruntime` paths where correct and seems that they are according to the output I got:
```
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\vcvarsall.bat
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\..\..\redist\MSVC\14.27.29016\onecore\x64\Microsoft.VC142.CRT\vcruntime140.dll
```

I found that the call to `vcvarsall.bat` through `subprocess.check_out` systematically returned non zero.
The message from the `_augment_exception `function gives the following putput:
Error executing cmd /u /c "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64 && set

When I put the ` cmd /u /c "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64 && set` directly in a *.bat script it works properly.

Does anyone has an hint what might be wrong in my installation settings (Visual Studio and/or Python)? (I also have Intel Parallel Studio installed).

PS:
Running Python
3.8.5 | packaged by conda-forge | (default, Jul 31 2020, 01:53:45) [MSC v.1916 64 bit (AMD64)]

**Comment by sound-fx** [comment]
`vcvarsall.bat` calls `..\..\..\Common7\Tools\vsdevcmd.bat`, which returns an error code 1 for any of a variety of reasons, most of which are harmless for our purposes.

It returns error code 1, and writes a warning about
```*** VsDevCmd.bat encountered errors. Environment may be incomplete and/or incorrect. ***```
when it fails to set up the environment for any of a number of components that I'd consider optional, including (from a perhaps too-cursory look) Team Explorer, .NET, IntelliCode, Performance Tools, Roslyn, Ninja, etc.

I don't see a clean way for the function `_msvc14_get_vc_env(plat_spec)` to distinguish worrisome errors from harmless ones (since the error code seems to always be 1 for any and all problems).  It could parse `exc.stdout.decode('utf-16le', errors='replace')` in the `except` block for worrisome error messages, or maybe check that the essential environment variables seem to be all in order, but those approaches seem precarious.

For now, I'm using a fragile work-around.  After confirming, as you did, that despite the error codes, `vcvarsall.bat` is preparing a sufficient and perfectly workable environment, I doctored the `msvc.py` code as shown below to simply ignore all error codes equal to 1 (which, alas, is the only error code value ever returned, so this temporary "fix" will also quietly ignore important errors).

```
    try:
        out = subprocess.check_output(
            'cmd /u /c "{}" {} && set'.format(vcvarsall, plat_spec),
            stderr=subprocess.STDOUT,
        ).decode('utf-16le', errors='replace')
    except subprocess.CalledProcessError as exc:
      # >>> Ignore all errors for now. >>>
      #     I've manually confirmed that, on my system, the 
      #     environment at this point is good enough to proceed.
      if exc.returncode == 1:
          out = exc.stdout.decode('utf-16le', errors='replace')
      else:
      # <<< Ignore all errors for now. <<<
        raise distutils.errors.DistutilsPlatformError(
            "Error executing {}".format(exc.cmd)
        ) from exc
```

**Comment by MilanSkocic** [comment]
Thanks! The work-around worked! 

I also tried to reinstall everything i.e. VS2019, Intel Parallel Studio and Python and the same issue still persists.  I don't really understand what goes wrong in `VsDevCmd.bat` 

Thanks again for your help.

**Comment by sound-fx** [comment]
I not only don't fully understand what goes wrong in `VsDevCmd.bat` either, but it's possible that `VsDevCmd.bat` isn't even the culprit returning the error code 1.  See https://github.com/pypa/setuptools/issues/2214#issuecomment-669537562 for another plausible explanation.  

It seems that calling `vcvarsall.bat` using `'cmd /u /c "{}"` can return the error code 1 for a different reason.  It would be useful if you or I try out [cmpotts](https://github.com/cmpotts)'s suggestion there, adding the `/d` parameter to the command line. If that accounts for our own problems, then we should link this issue to that one.

**Comment by MilanSkocic** [comment]
I did try to add the /d parameter (for disabling the execution of AutoRun commands) and in my case it worked. 
I forgot to mention that this issue occurred when I upgraded to Python 3.8 (Miniconda) if it is of any importance.

**Comment by fz007-hhh** [comment]
I met the same problem yesterday, and when I execute `cmd /u /c "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64 && set`,  the message is just `The input line is too long. The syntax of the command is incorrect.`

My situation was that I had installed Visual Studio 2019 a long time ago, but haven't used it for a very long time, and I had previously modified the environment variables. I tried to uninstall VS2019, then reinstall VS2022, and install the following two components:
```bash
Select: Workloads → Desktop development with C++
Then for Individual Components, select only:
Windows 10 SDK
C++ x64/x86 build tools
```
Afterwards, I restarted my computer, and when I executed the command again, everything worked as expected.
As for why to install the above two components, I referred to this website: https://stackoverflow.com/questions/64261546/how-to-solve-error-microsoft-visual-c-14-0-or-greater-is-required-when-inst
