### ISSUE TITLE
Overriding commands is inconsistent and partially broken

### ISSUE THREAD

**Issue by ghost** [pypa/setuptools#232]
Originally reported by: **schlamar (Bitbucket: [schlamar](http://bitbucket.org/schlamar), GitHub: [schlamar](http://github.com/schlamar))**

---

I want to override the install_scripts command to ship a customized
*.manifest on Windows because my script needs elevated rights. 
I noticed various inconsistencies and issues.

Basic script `cli.py`:

```
# coding: utf-8

import click


@click.command()
def cli():
    click.echo('OK')


if __name__ == '__main__':
    cli()
```

Basic setup:

```
from setuptools import setup

setup(
    name='test',
    version='0.1',
    py_modules=['cli'],
    install_requires=[
        'Click',
    ],
    entry_points='''
        [console_scripts]
        test=cli:cli
    ''',
)
```

Issue 1: custom install does not process `install_requires`.

Setup:

```
from setuptools.command.install import install

class custom_install(install):
    def run(self):
        install.run(self)

setup(
    cmdclass={'install': custom_install},
    ...
```

Running this as `python setup.py install` does not install Click.

Issue 2: custom install_scripts is ignored

Setup:

```
from setuptools.command.install_scripts import install_scripts

class custom_install_scripts(install_scripts):

    def run(self):
        print 'run'

setup(
    cmdclass={'install_scripts': custom_install_scripts},
```

Running this does not print 'run' to console.

Additional observation: overriding install + install_scripts does work,
but suffers from the first issue (install_requires does not get processed).

Setup:

```
from setuptools.command.install_scripts import install_scripts
from setuptools.command.install import install


class custom_install(install):
    def run(self):
        install.run(self)


class custom_install_scripts(install_scripts):

    def run(self):
        print 'run'
        install_scripts.run(self)

setup(
    cmdclass={'install': custom_install,
              'install_scripts': custom_install_scripts},
```

---
- Bitbucket: https://bitbucket.org/pypa/setuptools/issue/232

**Comment by abravalheri** [comment]
Thank you very much for pointing out at this problem!

I conducted some investigation, and my conclusions are as follow:

- `setuptools.commands.install` have a [`_called_from_setup` guard](https://github.com/pypa/setuptools/blob/a4c549dc8df0fd3f768283b5fdd7c90ab7cac43d/setuptools/command/install.py#L77).
  According to this guard, it will call `do_egg_install` (which delegates to `easy_install`) only if the `run` method is directly invoked from the `setuptools.dist.run_commands` functions.
  When you use inheritance and call `install.run(self)` or `super.run()` you add one level of depth to your stack and this guard fails falling back to the `distutils.commands.install` behaviour (which is not capable of handling dependencies).

- `do_egg_install` will not call `install_scripts` (instead it uses `easy_install.install_egg_scripts`), but `distutils.commands.install` will.
  That is reason why creating `custom_install_scripts` alone doesn't do anything, but works when you also create `custom_install`.

Since the `install` command is deprecated, I would say that it no longer makes sense to allow people to customise it, and close this issue for now. If there is any other use case that cannot be accomplished without it, please feel free to ask us to re-open this issue or go ahead and create a new one.
