### ISSUE TITLE
Can I choose where data files are installed?

### ISSUE THREAD

**Issue by mwouts** [pypa/setuptools#2341]
Hello,

I've been using `data_files` for a while, and it works very well.
Now I'd like to choose another file destination when the `--user` mode is activated (see https://github.com/mwouts/jupytext/issues/546).

Is it possible to choose the path depending on whether `--user` is set or no?

Also, while reading the documentation I saw a mention that *data_files is deprecated. It does not work with wheels, so it should be avoided.* Can I use [include_package_data](
https://setuptools.readthedocs.io/en/latest/setuptools.html#including-data-files) instead, and still install the files outside of the package itself?

Thanks!

**Comment by jaraco** [comment]
Short answer, no. The feature you're using is deprecated because it exposes too much platform-sensitive behavior to the package author.  `include_package_data` allows the package author to include data _inside the package_, wherever the package is installed.

I'd recommend to first ask yourself why are you trying to install files outside of the package or if you can just install the files with the package and reference them from there. Such an approach will be more robust in more environments.

If you can't do that, I'd consider using `include_package_data` and then sometime after installing, have another routine that your users will run to ensure that the package data is copied to the desired location... but I wouldn't recommend it.

**Comment by mwouts** [comment]
Thank you @jaraco , that is a very clear answer. Actually I think I agree with everything you said! I'll have a look at how the other python packages that also provide Jupyter extensions (e.g. plotly, voila) solve this issue. Thanks
