### ISSUE TITLE
egg_info.writers run on all subsequent package installs

### ISSUE THREAD

**Issue by NathanDeMaria** [pypa/setuptools#2346]
I'm running into an issue where I've defined a new `egg_info.writers` entry in `setuptools.setup`'s `entry_points` argument to add a new file to a package's `egg-info` (following instructions [here](https://setuptools.readthedocs.io/en/latest/setuptools.html#adding-new-egg-info-files)). This works fine for the package I want to add this file in, but then it seems to also run this writer function on all subsequent package installs, which is unexpected. Based on the documentation I've been able to find on this, it's not clear to me if this is just a surprising state, or a bug.

I've put together a reproducible example in [this GitHub repo](https://github.com/NathanDeMaria/egg_info_writers_issue) to hopefully demonstrate this more clearly.

I believe this happens consistently on various versions, but I most recently reproduced this on:

```
Python 3.8.5
setuptools==49.3.1
```

**Comment by jaraco** [comment]
I haven't reviewed the implementation, but it seems perfectly reasonable to me that egg-info writers would run on every invocation of `egg_info`, which also happens during installs... as the info could change on each invocation. What makes you think it should run just once?

**Comment by NathanDeMaria** [comment]
I wound up on [this section of the docs](https://setuptools.readthedocs.io/en/latest/setuptools.html#adding-new-egg-info-files) looking for a way to add some sort of marker to a package's `egg-info` that a later packages could find. Since it's something included in a package's `setup`, and adds to _that_ package's `egg-info`, it seemed like a reasonable way to do that. I was surprised when I realized this "marker" was also showing up on other packages. This line in particular made it seem like it should be only in packages where I'm setting this in their `setup`

> The egg_info command looks for extension points in an egg_info.writers group, and calls them to write the files. Here’s a simple example of a distutils extension defining a setup argument foo_bar, which is a list of lines that will be written to foo_bar.txt in the EGG-INFO directory of any project **that uses the argument**

If that's the intended behavior, I think it makes sense in retrospect since it's specified under `entry_points`.

**Comment by jaraco** [comment]
Oh, I see. Originally I thought you were talking about wanting the egg_info writer to only be invoked once on a solitary package, but now I see you're talking about multiple packages. I hadn't looked into the github repo, which I see now provides a lot more detail.

**Comment by jaraco** [comment]
Here's what's happening:

The setuptools `egg_info` command unconditionally runs all `egg_info.writers` that are installed. That's apparent from:

> The egg_info command looks for extension points in an egg_info.writers group, and calls them to write the files.

Normally, the `egg_info.writers` would be defined in the same package as the function that implements the writer, but in your example, you've defined the two in separate packages ("writer" and "writing").

This approach happens to work in your example because you install 'writer' first, so the implementation is available, then you install 'writing' which installs the `egg_info.writers` hook. That hook, however, is not meant to be conditional per package. It's meant to declare that this package implements a writer.

If you want the writing to be conditional, you'll need to define what that condition is and have the writer honor that condition. I'll put together an example.

**Comment by jaraco** [comment]
In [my fork](https://github.com/jaraco/egg_info_writers_issue), I've made three commits:

- https://github.com/jaraco/egg_info_writers_issue/commit/9be0d5b712484543af64b65a4c070abb6af748c5 demonstrates the recommended practice of implementing the writer and its hook in a single package.
- https://github.com/jaraco/egg_info_writers_issue/commit/8f01f568571be7b7a52d6e19645e962f6872a23a illustrates how the hook can be engineered to only conditionally generate its output.
- https://github.com/jaraco/egg_info_writers_issue/commit/d51a3c36a67fe2fe648872cfbcda69c7dd8b6f74 illustrates how one could use the preferred PEP 517/518 build instead of `setup_requires`. This change is ancillary to the reported issue, but I wanted to take this opportunity to share.

I hope that helps clarify the issue. Please let me know if you have additional questions.

**Comment by NathanDeMaria** [comment]
That's reasonable, thank you for the detailed explanation. https://github.com/jaraco/egg_info_writers_issue/commit/8f01f568571be7b7a52d6e19645e962f6872a23a is similar to the "workaround" I have in https://github.com/NathanDeMaria/egg_info_writers_issue/blob/dd05209e3b27e3e2a4259e5897489414d6b1f492/workaround-writer/writer.py#L8-L9. From what I can tell, that's what we'd need to do if we want to have the logic for _writing_ in one package and elect to use it conditionally in (potentially multiple) future package installs. Seems a little weird, but I suppose that's because I'm trying to use `egg_info.writers` in a way different from how it's intended.

Also, thanks for the pointer on `PEP-518`, I wasn't aware `setup_requires` was discouraged 🙇‍♂️
