### ISSUE TITLE
[options.packages.find_namespace] should be [options.packages.find] in package discovery guide

### ISSUE THREAD

**Issue by Pike** [pypa/setuptools#2406]
In https://setuptools.readthedocs.io/en/latest/userguide/package_discovery.html#using-find-namespace-or-find-namespace-packages, the docs say

```ini
[options.packages.find_namespace]
where = src
```

That fails with

```
distutils.errors.DistutilsOptionError: Unsupported distribution option section: [options.packages.find_namespace]
```

```ini
[options.packages.find]
where = src
```

actually works.

Filing this as a doc issue, but maybe that option should work the way it's documented?

**Comment by jaraco** [comment]
Thanks for the report.

I'm actually unsure what's the right thing here. The `find` is indeed a possible solution, but I suspect it doesn't support PEP 420 namespace packages. Clearly that documentation is meant to capture a feature that supports namespace packages as well. Someone will have to dig in deeper to find out what the correct syntax is for namespace packages.

**Comment by trharoldsen** [comment]
The description of `options.packages.find_namespace` is also found in https://setuptools.readthedocs.io/en/latest/userguide/declarative_config.html so at least two locations in documentation are expecting it to work.

```
Note packages - The find: and find_namespace: directive can be further configured in a dedicated subsection options.packages.find. This subsection accepts the same keys as the setuptools.find_packages and the setuptools.find_namespace_packages function: where, include, and exclude.
```


I did a little searching of the code and found a few things.  `options.packages.find` will work correctly according the the code.
Both options.packages.find and options.packages.find_namespace sections are parsed in `ConfigOptionsHandler._parse_packages` in `config.py` when the corresponding package value (`package = 'find[_namespace]'`) is parsed.

```
        find_directives = ['find:', 'find_namespace:']
        trimmed_value = value.strip()

        if trimmed_value not in find_directives:
            return self._parse_list(value)

        findns = trimmed_value == find_directives[1]

        # Read function arguments from a dedicated section.
        find_kwargs = self.parse_section_packages__find(
            self.sections.get('packages.find', {}))

        if findns:
            from setuptools import find_namespace_packages as find_packages
        else:
            from setuptools import find_packages

        return find_packages(**find_kwargs)
```

So it's actually expected that the `[options.packages.find]` form will be used.

The actual error occurs because the `options.packages` sections are parsed twice; once in the previously mentioned area and again when the the parser reaches the section.  At this point the parser does a lookup of the method based on the option name. 
 It finds the corresponding `options.packages.find` method, `_parse_section_find`, ignoring the result.  However, there is no corresponding `_parse_section_find_namespace` method for the `options.packages.find_namespace` section which leads to the error.

I suppose the real question at this time is cosmetic.  Should the code be updated to match the documentation or the other way around?

**Comment by drmuelr** [comment]
> I suppose the real question at this time is cosmetic. Should the code be updated to match the documentation or the other way around?

From a naive user perspective without having looked at the code: I was relying entirely on the docs to indicate the correct section name.

There seems to be naming parity between the `options.package.find_namespace` section name and
```INI
[options]
package = find_namespace:
```

However, I'm not familiar enough with setuptools to know if this kind of parity prevails elsewhere. Beyond that, it seems like simply updating the docs would be a fine solution.

**Comment by jaraco** [comment]
I recently began implementing `find_namespace` for one of the packages I maintain and did find the `options.packages.find` a little surprising. On the other hand, when I dug into the implementation, there was something nice about how the parameters are parsed by the same section. I think the intention is to eventually migrate everyone to the behavior of `find_namespace` but the simple syntax of `find`. So my instinct is to update the documentation to reference `options.packages.find`.

**Comment by ssbarnea** [comment]
@jaraco Were you able to find a solution? I am trying to port some old sphinx extensions that use namespace to setup.cfg and its seams that I am in an uncharted territory.

A link to a simple working example would likely be 10x more useful than all the documentation ever written around setuptools.

**Comment by omry** [comment]
After some debugging, this is what works for me:
hydra_plugins is the directory containing the namespace packages.

```ini
[options]
package_dir =
    =hydra_plugins
packages = find_namespace:

[options.packages.find]
where = hydra_plugins
```
The docs are definitely misleading right now.

**Comment by jaraco** [comment]
I'm now using `find_namespace` in most of my packages (those not supporting Python 2) based on [jaraco/skeleton](https://github.com/jaraco/skeleton/blob/main/setup.cfg).

**Comment by omry** [comment]
Thanks, will give it a try. I think your 
```toml
[options.packages.find]
exclude =
  build
  ...
```
Will help a lot. (I kept getting the build artifacts in my final wheel, now I understand why.

**Comment by jaraco** [comment]
I've updated the docs to remove the bad reference to 'options.packages.find_namespace'. I believe that fixes this issue. Feel free though to ask for clarification or open a new issue if there are other concerns that need addressed.

**Comment by omry** [comment]
Thanks, I opened a new issue (#2630).
