### ISSUE TITLE
  ImportError: cannot import name 'Feature' from 'setuptools' 

### ISSUE THREAD

**Issue by git0fun** [pypa/setuptools#2423]
File "/private/var/folders/jw/3jbz7d2d0wb6m5rkp6qkmqbm0000gn/T/pip-install-nchdg799/zope-i18nmessageid/setup.py", line 25, in <module>
        from setuptools import setup, find_packages, Extension, Feature
    ImportError: cannot import name 'Feature' from 'setuptools' (/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/__init__.py)

**Comment by jaraco** [comment]
This feature was removed intentionally in [46.0.0](https://setuptools.readthedocs.io/en/latest/history.html#v46-0-0) (see #65). You'll need to work with the package maintainer to find a suitable version of `zope.i18nmessageid` or downgrade to `setuptools<46` to build/install the package. Note also that the maintainer has uploaded wheels of the `zope.i18nmessageid`, which means that if you install the package with pip instead of the deprecated `easy_install`, you'll get the wheel and bypass the Setuptools compatibility issue altogether.
