### ISSUE TITLE
DeprecationWarning with load_module on Python 3.10 in pkg_resources._handle_ns

### ISSUE THREAD

**Issue by blueyed** [pypa/setuptools#2493]
> DeprecationWarning: the load_module() method is deprecated and slated for removal in Python 3.12; use exec_module() instead

Code ref: https://github.com/pypa/setuptools/blob/544687c3982696d924d49c4c9ea094b7a2dc8fe0/pkg_resources/__init__.py#L2212

**Comment by hroncok** [comment]
I've drafted https://github.com/pypa/setuptools/pull/2517 but I am sure that's not the correct path froward.

**Comment by encukou** [comment]
As for the calling of `load_module` in `pkg_resources.__init__`, it seems to me that the only purpose of the call is to ensure the module is loaded, so that its `__path__` can be fixed up using `_rebuild_mod_path`. The call uses the default loader.

So, it could be replaced by `importlib.import_module(packageName)`. From the [`load_module` docs](https://docs.python.org/3.9/library/importlib.html#importlib.abc.Loader.load_module), the only thing it does in addition to what `import_module` does is reloading the module if it already exists. To me, that seems like an unintended side effect.
But I could also be off; the docs are written for *implementing* of loaders, not for calling them.

I'll send a PR.
