### ISSUE TITLE
Remove support for LegacyVersion

### ISSUE THREAD

**Issue by jaraco** [pypa/setuptools#2497]
In #2466 and pypa/packaging#368, it's become apparent that Setuptools should get out of the business of supporting the `LegacyVersion`.

**Comment by yan12125** [comment]
I had a look into the `debt/remove-legacy-version` branch - the first failure (`Invalid version: '51.1.0.post20201221.post-20201221'`) is because setuptools itself generates non-PEP440 versions. Other issues are from the `package_index` module, which accepts non-PEP440 versions. Seems `package_index` is used by easy_install only? If so, dropping `LegacyVersion` might be related to dropping easy_install: https://github.com/pypa/setuptools/issues/917.

With some patches (https://github.com/yan12125/setuptools/commits/debt/remove-legacy-version), the number of failed tests goes down to 3: https://github.com/yan12125/setuptools/runs/1607790124.

**Comment by yan12125** [comment]
There is an ongoing PR on removing `LegacyVersion`: https://github.com/pypa/packaging/pull/407
