### ISSUE TITLE
`develop` and `install --single-version-externally-managed` are not compatible with each other for namespace packages

### ISSUE THREAD

**Issue by bb-migration** [pypa/setuptools#250]
Originally reported by: **hongqn (Bitbucket: [hongqn](http://bitbucket.org/hongqn), GitHub: [hongqn](http://github.com/hongqn))**

---

To reproduce this issue, do the following in a virtualenv:
1. prepare source code of two packages with same namespace package `ns`:
   
   ```
   mkdir -p pkg1/ns/pkg1 pkg2/ns/pkg2
   echo "from setuptools import setup, find_packages; setup(name='pkg1', packages=find_packages(), namespace_packages=['ns'])" > pkg1/setup.py
   echo "__import__('pkg_resources').declare_namespace(__name__)" > pkg1/ns/__init__.py
   touch pkg1/ns/pkg1/__init__.py
   echo "from setuptools import setup, find_packages; setup(name='pkg2', packages=find_packages(), namespace_packages=['ns'])" > pkg2/setup.py
   echo "__import__('pkg_resources').declare_namespace(__name__)" > pkg2/ns/__init__.py
   touch pkg2/ns/pkg2/__init__.py
   ```
2. install pkg1 using --single-version-externally-managed
   
   ```
   cd pkg1
   python setup.py install --single-version-externally-managed --record record.txt
   cd ..
   ```
3. install pkg2 using develop
   
   ```
   cd pkg2
   python setup.py develop
   cd ..
   ```
4. pkg1 is accessible
   
   ```
   python -c 'import ns.pkg1'
   ```
5. pkg2 is unexpectedly inaccessible
   
   ```
   python -c 'import ns.pkg2'
   Traceback (most recent call last):
     File "<string>", line 1, in <module>
   ImportError: No module named pkg2
   ```

This was discussed in pip's issue tracker https://github.com/pypa/pip/issues/3 years ago (because pip uses `install --single-version-externally-managed` for `pip install` and use `develop` for `pip install --editable`), but they still have not gotten a resolution.

I think this issue should be resolved in setuptools instead of pip.  `install --single-version-externally-managed` creates a `{pkg}-nspkg.pth` in site-packages directory.  It will create a ns module and assign its `__path__` to the ns directory in site-packages.  So `pkg_resources.declare_namespace()` in pkg2's ns/__init__.py has no chance to run.

 I have two proposals to fix it:
1. Fix `install --single-version-exteranlly-managed`.  Modify the `{pkg}-nspkg.pth` file to append a line
   
   ```
   import pkg_resources; pkg_resources.declare_namespace('ns')
   ```
   
   at the end of it.  So it will scan `sys.path` to gather other directories into `ns.__path__`.
   
   A tricky point is that we must ensure the `{pkg}-nspkg.pth` filename is alphabetically larger than `easy-install.pth`, so that we have source code directory installed by `develop` command in `sys.path` when running `declare_namespace`.  Is to rename to `zzz-{pkg}-nspkg.pth` a good idea?
2. Fix `develop` command.  Create a `{pkg}-nspkg.pth` in site-packages directory when a namespace package is installed using `develop` command, like what `install --single-version-externally-managed` does.  The content of the pth file could be:
   
   ```
   /path/to/sourcecode
   import pkg_resources; pkg_resources.declare_namespace('ns')
   ```
   
   The `/path/to/sourcecode` line is duplicated with what is inserted in easy-install.pth.  It is here to make sure `sys.path` contains it before `declare_namespace` runs.  It could be omitted if we have a `zzz-` prefix for the pth filename.

What's the dev team's opinion?  I prefer to the second proposal because it only affects `develop` command which is mostly used in develop environment so it will not affect production systems.

I'd like to contribute code fix if you agree with either one of the proposals.

---
- Bitbucket: https://bitbucket.org/pypa/setuptools/issue/250

**Comment by jaraco** [comment]
@embray Did you have any luck working on a patch for this issue?

**Comment by jaraco** [comment]
Building on the draft in #789, and with the help of Barry, Andrew, and Eric today, I made some progress on the [develop-nspkg branch](/pypa/setuptools/tree/develop-nspkg). Initial testing indicates that this technique does work as long as the `__init__.py` doesn't exist in the namespace under development.

Some concerns still remain:

- [ ] When pip uninstalling the package, the -nspkg.pth file isn't removed.
- [ ] `__init__.py` has to be removed, which can affect `find_packages`. One option is to make find_packages work in this model. Another could be to possibly adapt the -nspkg.pth file to run unconditionally.
- [ ] Should we have some tests?

**Comment by jaraco** [comment]
I've added a test that captures the basic expectation (linked above).

In the [develop-nspkg-always branch](https://github.com/pypa/setuptools/tree/develop-nspkg-always), I've removed the check for `__init__.py`, which allows the test to pass even without removing `__init__.py`, but [only on Python 3.2 and earlier](https://travis-ci.org/pypa/setuptools/builds/173837436). It appears that the mixed presence of the `__init__.py` (present for myns.pkgB under develop, but not present for myns.pkgA installed by pip) causes a conflict between the legacy namespace package support and the PEP 420 namespace package support. I'd like to see if there's a way to support this environment, because if it's necessary for package maintainers to remove these `__init__.py` files, that's likely to be difficult to support.

**Comment by jaraco** [comment]
In #789, @ncoghlan said:

> While I agree that situation [where `__init__.py` in the develop package] isn't ideal, I believe it should still work as long as the `__init__.py` does the necessary dance to set its own `__path__` correctly using pkg_resources or pkgutil.

And he's right. The problem is that the presence of the `__init__.py` file in any path representing the namespace causes the PEP 420 find/load behavior to be disabled and since #805, the `-nspkg.pth` behavior is also disabled, so there's nothing left to set up the namespace packages for installed packages.

If I [revert the behavior introduced in #805](/pypa/setuptools/commit/2268fb9887cfea2e28e156bd), the [tests in the develop-nspkg-always branch now pass](https://travis-ci.org/pypa/setuptools/builds/175484039). I think I want to write a test for #805 to demonstrate the use case and expectation.

In the meantime, can @ncoghlan or any one else imagine a way that the `-nspkg.pth` file could be written such that it doesn't interfere with the loading of PEP 420 namespace packages elsewhere in the PYTHONPATH? [This comment](https://github.com/jaraco/rwt/issues/5#issuecomment-238356450) provides some detail on the differences between these packages.

**Comment by jaraco** [comment]
> I want to write a test for `#805`

I've done this and pushed the test into master.

**Comment by ncoghlan** [comment]
@jaraco Looking more closely at that, the problematic piece is this expression: `types.ModuleType(%(pkg)r)`, and in particular the fact it doesn't set `__spec__` and various other attributes the interpreter is expected to see post PEP 451 (as long as `__spec__` is set, the import system can fill in most of the others, but without `__spec__` some operations won't work as expected).

So in 3.5+, what you probably want to be doing is:

1. Use https://docs.python.org/3/library/importlib.html#importlib.machinery.PathFinder.find_spec to create the namespace spec based on the values of `pkg` and `pth`.
2. Use https://docs.python.org/3/library/importlib.html#importlib.util.module_from_spec to create the module based on that

I *think* the necessary parameters to replace the current types.ModuleType call in the template would look something like:

    module_from_spec(PathFinder.find_spec(%(pkg)r, [os.path.dirname(p)])

The current explicit version check would then be replaced by a check for `module_from_spec` (which only appeared in 3.5).

If you wanted to handle 3.4 as well, then the simplest approach would likely be to extract the pieces of https://hg.python.org/cpython/file/3.5/Lib/importlib/_bootstrap.py#l570 that are applicable to `_NamespaceLoader` in 3.4.

**Comment by jaraco** [comment]
Thanks @ncoghlan. That's really helpful. I've tested it and it appears to be working on Python 3.5 and 3.6. The problem is now Python 3.3 and 3.4 - since they don't have the interfaces, and since this code needs to be embedded in a .pth line, it's not really feasible to backport importlib machinery.

I think it's also not viable to include the behavior in a library (like setuptools) -- because this logic runs at startup, it probably shouldn't have dependencies on any functionality not in the stdlib. I did draft an implementation using such a technique, but it would be very brittle in scenarios where setuptools is downgraded or possibly upgraded or uninstalled.

Which leads me to think that we might have specifically not to support Python 3.3 and 3.4 for this use case. Can anyone thing of a way around this issue?

**Comment by ncoghlan** [comment]
@jaraco Limiting support for this to 3.5+ only seems like a reasonable decision to me.

There were genuinely missing pieces in the initial iterations of PEP 420 and PEP 451, and they didn't get fully resolved until the new helper APIs were added in 3.5.
