### ISSUE TITLE
[BUG] 51.1 version released as v51.1.0.post20201221

### ISSUE THREAD

**Issue by webknjaz** [pypa/setuptools#2500]
@jaraco I noticed that there's a release on PyPI but no tag on GitHub. Could you please push it?

**Comment by jaraco** [comment]
The version in the release is a mistake.

**Comment by jaraco** [comment]
The issue here is that setuptools uses [this config section](https://github.com/pypa/setuptools/blob/d503f75e0535edb644a53fd77b4bc85a97fb4add/setup.cfg#L74-L76) to tag builds with '.post' and the current date such that everything but the official release has some indication that it's not the official release. Prior to #2486, setuptools provided a separate 'release' command for cutting the official release without those tags. I don't believe it's possible for a PEP 517 build to provide that sort of customization.

Most other projects avoid this situation by not caring and just leaving every release to re-use the same version as official releases despite not having the same code. Other projects use setuptools_scm to generate a version based on git metadata so provide tags to the version to indicate their distance to the last tagged release.

I don't think setuptools can use setuptools_scm. At least, I'm not confident it can without problems, so I'm first going to remove that config section and once again cut 51.1.0 and remove 51.1.0.post from PyPI.

**Comment by jaraco** [comment]
On further consideration, it looks like it may be possible to just-in-time re-write the cfg file to remove those settings:

```diff
diff --git a/tox.ini b/tox.ini
index 517dd4d90..9680ec010 100644
--- a/tox.ini
+++ b/tox.ini
@@ -68,6 +68,8 @@ setenv =
 commands =
 	python -m bootstrap
 	python -c "import path; path.Path('dist').rmtree_p()"
+	# unset tag_build and tag_date pypa/setuptools#2500
+	python setup.py egg_info -Db "" saveopts
 	python -m pep517.build .
 	python -m twine upload dist/*
 	python -m jaraco.develop.create-github-release
```

This approach brings the behavior back in line to where it was before, with the biggest exception being that the setup.cfg file in the release will never match what's in the tagged commit. But I guess that's an acceptable limitation until the build tooling gets better.

**Comment by jaraco** [comment]
I've re-tagged dfd1552 as v51.1.0. Now I'll use the yank feature to yank the post release.

**Comment by jaraco** [comment]
![image](https://user-images.githubusercontent.com/308610/102798874-b74b3900-437f-11eb-900c-a3922a364846.png)
