### ISSUE TITLE
Import error on ContextualZipFile inside pkg_resources.py

### ISSUE THREAD

**Issue by bb-migration** [pypa/setuptools#252]
Originally reported by: **jabagawee (Bitbucket: [jabagawee](http://bitbucket.org/jabagawee), GitHub: [jabagawee](http://github.com/jabagawee))**

---

Running the latest setuptools and pip from get-pip.py on Linux Mint 17 to install any package causes an ImportError to occur when trying to import ContextualZipFile from pkg_resources. The ensure_directory import on the same line has no issues. Checking pkg_resources.py confirms that the class ContextualZipFile does in fact exist.

Alternatively, installing the python-pip package from my package manager makes everything work just fine. I'm probably being very unclear, so feel free to ping me for clarification.

---
- Bitbucket: https://bitbucket.org/pypa/setuptools/issue/252

**Comment by riturajtiwari** [comment]
I have this issue on MacOS Sierra 10.12.3, Python 2.7. The previous suggestion of simply removing import of ContextualZipFile simply kicks the can down the road. I immediately run into another import issue: 
```
/Users/rituraj_tiwari/PythonVirtualEnvs/tensorflow/lib/python2.7/site-packages/setuptools/command/easy_install.py in <module>()
     63 
     64 # Turn on PEP440Warnings
---> 65 warnings.filterwarnings("default", category=pkg_resources.PEP440Warning)
     66 
     67 __all__ = [

AttributeError: 'module' object has no attribute 'PEP440Warning'
```

**Comment by jaraco** [comment]
@riturajtiwari Can you describe how it was you created that PythonVirtualEnvs/tensorflow environment?

**Comment by riturajtiwari** [comment]
I upgraded PIP to 9.0.1, then ran 
```
$ virtualenv --system-site-packages tensorflow
$ source tensorflow/bin/activate
$ pip install --upgrade tensorflow
```

**Comment by jaraco** [comment]
It's [working for me](https://gist.github.com/jaraco/bed7168bce24673219ae773081fd4ab6), but that's probably because I have setuptools 18.5 installed in my system site packages:

```
$ /usr/bin/python2.7 -m easy_install --version
setuptools 18.5 from /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (Python 2.7)
```

My guess is you have an older version of setuptools (or just pkg_resources) in your system site packages that's interfering. You'll either need to investigate what's wrong with your system site packages or avoid the `--system-site-packages`.

If there's something that setuptools can/should do to address this issue, I'm open to suggestions. I'd also be willing to investigate deeper if someone can replicate the failure on Travis-CI or docker. As it stands, it's an unfortunate consequence of the sordid history of python packaging.
