### ISSUE TITLE
find_packages() `where` arg prevents package data from being migrated

### ISSUE THREAD

**Issue by hainesm6** [pypa/setuptools#2546]
### Disclaimer

This issue may belong in the [twine](https://github.com/pypa/twine) repository instead. Appologies if that's the case.

### Summary

Package data was not uploaded to pypi when the `where` argument was specified as the package directory when calling the setuptools.find_packages() function. As a workaround we are using the `exclude` arg instead but this cost us (and potentially other users) some time to figure out.

### Details

We recently submitted a [package](https://github.com/LondonBiofoundry/basicsynbio) containing additional package data files. I tried specifying package data files in both a MANIFEST.in file and using the `package_data` arg when calling the setuptools.setup() function. However, while I was able to generate .whl and .tar.gz files, the package data was not migrated to pypi when uploading these files using `twine upload dist/*`.

As a work around we are using the `exclude` arg with no problesm. Here is a `git diff` comparing the relevant sections of the old and working setup.py files:

```git
setuptools.setup(
     long_description=long_description,
     long_description_content_type="text/markdown",
     packages=setuptools.find_packages(
-        where="basicsynbio"
-    ),
-    package_dir={"":"basicsynbio"},
-    package_data={
-        "": ["*.gb"]
-    },
+        exclude=("tests")
+    ),  # package_data not correctly migrated if "where" arg used.
```

**Comment by layday** [comment]
There's a few things going on here.  Firstly, `where` should specify the parent folder which contains the packages; `basicsynbio` is the package you want to find itself.  The `exclude` is not a tuple; it's a string which gets broken up into `("t", "e", "s", "t", "s")`; and the `tests` folder is not a package as far as setuptools is concerned because it does not contain an `__init__.py`, so the exclude is redundant.  As far as I can tell, the issue is that the `basicsynbio` package wasn't picked up at all; only the `parts_linkers` and `utils` sub-packages were.

**Comment by hainesm6** [comment]
Thanks for the reply @layday. Yes, I forgot the `exclude` was no longer necessary and I've just realised the [example](https://setuptools.readthedocs.io/en/latest/userguide/package_discovery.html) given has packages placed in a `src` parent directory which explains why in my case it didn't work. Thanks for the explanation 👍
