### ISSUE TITLE
fix -R option of build_ext for OSX

### ISSUE THREAD

**Issue by tovrstra** [pypa/setuptools#2554]
I'm re-opening an issue I once opened for distutils. I received a message that distutils will be deprecated and the issue might have to be re-opened for setuptools. I quick check of the code confirms that the same issue also also present in setuptools.

The original pull request can be found here: https://github.com/python/cpython/pull/12418/files and https://bugs.python.org/issue36353.

I can make a new pull request if desired. Just let me know.

**Comment by abravalheri** [comment]
Hi @tovrstra, thank you very much for submitting this!

It seems that the problem has already been fixed in the [`pypa/distutils` repository](https://github.com/pypa/distutils/blob/bb018f1ac34bb638ef0aa76d7fff0fe7dace6754/distutils/unixccompiler.py#L239) (which is where setuptools pulls distutils from).

Could you confirm if my assumption is correct?

I will close this issue for the time being, but please feel free to submit a fix to https://github.com/pypa/distutils if one is still missing.

**Comment by tovrstra** [comment]
Thanks for checking this out. The code looks good to me, and it even seems to be a better fix.
