### ISSUE TITLE
Add issue forms

### ISSUE THREAD

**Issue by webknjaz** [pypa/setuptools#2556]
@jaraco GH is currently alpha-testing issue forms — they are similar to issue templates except they can force the users to fill out the required fields when filing an initial issue.

Demo: https://github.com/pypa/pip/issues/new?template=bug-report.yml

Would it be okay to enable them for setuptools? After looking at issues like https://github.com/pypa/setuptools/issues/2555 it only feels right to do so.

**Comment by jaraco** [comment]
Perhaps. It can be difficult to devise a form that effectively solicits the right information, but I'm not particularly opposed to it if someone wishes to invest the effort. Forms can be particularly challenging because they may end up asking for too much or too little information for the particular issue and if fields are required, they can annoy the user for whom that information is unavailable or irrelevant. I'd say aim for something modest but complete.

**Comment by webknjaz** [comment]
@jaraco I've made a PR and a demo for you: https://github.com/webknjaz/setuptools-issue-forms-demo/issues/new/choose.
