### ISSUE TITLE
`find:` for `options.scripts` in `setup.cfg` file

### ISSUE THREAD

**Issue by alexreg** [pypa/setuptools#2587]
I currently have something like this in my `setup.cfg`.

```ini
[options]
scripts =
	src/bin/foo
	src/bin/bar
```

It would be great to make possible something like the following.

```ini
[options]
scripts = find:

[options.scripts.find]
where = src/bin/
```

(Ideally it would only pick out files with their executable bit set, but in my case, it does't matter, since they are the only files in the directory.)

Would you consider adding this feature?

**Comment by abravalheri** [comment]
Hi @alexreg thank you very much for bringing this topic.

I believe this is not the direction Python ecosystem is moving towards...

The latest PEPs (e.g. PEP 621) assume `scripts` are created via entry-points.
So for any new package I (personally) would recommend avoid creating script files, but instead relying on [`console_scripts`](https://setuptools.pypa.io/en/latest/userguide/quickstart.html?highlight=console_scripts#entry-points-and-automatic-script-creation).

Because of this I don't see many benefits such a feature would bring... Do you have any complex use cases this feature would help you to solve?

**Comment by alexreg** [comment]
@abravalheri Thanks for the reply. Thats sounds fair enough.
