### ISSUE TITLE
[BUG] setup.cfg find_namespace: includes build directory

### ISSUE THREAD

**Issue by omry** [pypa/setuptools#2630]
### setuptools version

54.2.0

### Python version

3.8.2

### OS

Ubuntu 18.04

### Description

I am not sure if this is a bug or a documentation issue (or both).
My goal is to port the minimal setup.py based example [here](https://github.com/omry/python-build-tests/tree/main/namespace_package_example/setup_py) to the minimal setup.cfg based example [here](https://github.com/omry/python-build-tests/tree/main/namespace_package_example/setup_cfg).
Outputs for each variant are in READMEs of each of the directories.

The output contains the build directory if it exists in the local directory, even though setup.cfg excludes it (or attempt to at least).

Side note:
The setup.py based example do not need to explicitly exclude build, and does not end up with a build dir in the wheel even on subsequent runs.
In terms of usability, it would be great if we can achieve the same behavior without an explicit blacklist of directories.

### Code of Conduct

I agree to follow the PSF Code of Conduct

**Comment by abravalheri** [comment]
Hi @omry, thank you very much for bringing this up.

I think it all boils down to the fact that you are using the [`include` parameter with `setup.py`](https://github.com/omry/python-build-tests/blob/b41f71606e27a639cf40c754baebaaa3afc2df7f/namespace_package_example/setup_py/setup.py#L10), but then you use [`exclude` with `setup.cfg`](https://github.com/omry/python-build-tests/blob/b41f71606e27a639cf40c754baebaaa3afc2df7f/namespace_package_example/setup_cfg/setup.cfg#L10-L17)...

Have you tried also using `include` with `setup.cfg`?

There also seems to be a problem with your exclude configuration, both `include` and `exclude` accept package names, not file paths. So instead of `build/*`, I would use `build.*`...

I will close this issue for now, but please let me know if this does not work for you and I will re-open it.
