### ISSUE TITLE
[BUG] rfc6266 library installing

### ISSUE THREAD

**Issue by DanilaCharushin** [pypa/setuptools#2767]
### setuptools version

setuptools==58.0.0

### Python version

python 3.8.2

### OS

Debian (python 3.8.2-slim base docker image)

### Description

Module **rfc6266==0.0.4** setups incorrect since 06.09.2021 after setuptools update to version 58.0.0.

Module [rfc6266](https://pypi.org/project/rfc6266/) installing as a dependency for [pyrus-api](https://github.com/simplygoodsoftware/pyrusapi-python) library

In [rfc6266 sources](https://github.com/g2p/rfc6266/blob/master/rfc6266.py#L16) code is bad **(but when package is installed - code is different, see below)**, it is for old urllib library style, but despite this, when I calling methods from pyrus-api that uses rfc6266 code - all works good. Before setuptools==58.0.0 site-packages/rfc6266.py had this code:
```python
...
from lepl import *
from collections import namedtuple
from urllib.parse import quote, unquote
from urllib.parse import urlsplit
from string import hexdigits, ascii_letters, digits
...
```
both repos ([rfc6266](https://github.com/simplygoodsoftware/pyrusapi-python) and [pyrus-api](https://github.com/simplygoodsoftware/pyrusapi-python)) was updated months ago, this is reason for decision that new release of setuptool==58.0.0 broke normal code behavior.

For now, solution is not to install latest setuptools version, but I think that it is bad solution.

PS: in Dockerfile installing setuptools by this:
```console
pip install --upgrade pip setuptools wheel
```

### Expected behavior

This code in site-packages/rfc6266.py:
```python
...
from lepl import *
from collections import namedtuple
from urllib.parse import quote, unquote
from urllib.parse import urlsplit
from string import hexdigits, ascii_letters, digits
...
```

### How to Reproduce

1. Rollback to lates setuptools version

### Output

```console
File "/usr/local/lib/python3.8/site-packages/pyrus/client.py", line 24, in <module>
    import rfc6266
File "/usr/local/lib/python3.8/site-packages/rfc6266.py", line 16, in <module>
    from urllib import quote, unquote
ImportError: cannot import name 'quote' from 'urllib' (/usr/local/lib/python3.8/urllib/__init__.py)
```

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by jaraco** [comment]
Thanks for the report.

The behavior is working as intended. See the [changelog for the 58 release](https://setuptools.readthedocs.io/en/latest/history.html#v58-0-0).

The problem is that rfc6266 is using very old deprecated syntax and relying on Setuptools and lib2to3 to port the code to Python 3 syntax. Python 2 is no longer supported in the ecosystem, so projects should really not be relying on lib2to3. My recommendations (in order of my preference):

- rfc6266 should drop support for Python 2 and release a Python 3 compatible version.
- rfc6266 should use six to support Python 2 and 3 in the same codebase.
- rfc6266 should provide an internal support for both Python 2 and 3.
- rfc6266 should use PEP 518 to declare `setuptools<58` to build itself.
- users relying on rfc6266 should pin to `setuptools<58` until one of the above is accomplished.

It does look like rfc6266 is abandoned, so it may also be necessary to revive the project under another name.
