### ISSUE TITLE
[BUG] Should fail hard when installing packages that want 2to3

### ISSUE THREAD

**Issue by plumdog** [pypa/setuptools#2769]
### setuptools version

setuptools==58.0.0

### Python version

Python 3.9

### OS

Linux

### Description

Tried to install a package that uses 2to3 (specifically https://pypi.org/project/demjson/), got a message from pip like:
```
Successfully installed demjson-2.2.3
```
But really it wasn't successful, and then get confusing `SyntaxError` exceptions.

### Expected behavior

I have now worked out that this is because of the change to remove `2to3` from setuptools, which I think is a perfectly reasonable change, and because my setuptools version wasn't pinned. But setuptools is not doing something the package is asking for, and the result is going to be something that does not run (though I guess there are caveats here).

I would have expected to get an error like "This module wants to use 2to3, but this is not supported [link to github issue about removing 2to3 support]". At least, that would certainly have saved me time.

### How to Reproduce

Install `demjson==2.2.3` with `setuptools==58.0.0`. Attempt to import and get a syntax error.

### Output

```console
$ pip install -U setuptools==58.0.0 && pip install demjson==2.2.3 && python -c 'import demjson'
Collecting setuptools==58.0.0
  Using cached setuptools-58.0.0-py3-none-any.whl (816 kB)
Installing collected packages: setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 56.0.0
    Uninstalling setuptools-56.0.0:
      Successfully uninstalled setuptools-56.0.0
Successfully installed setuptools-58.0.0
Collecting demjson==2.2.3
  Using cached demjson-2.2.3.tar.gz (131 kB)
Using legacy 'setup.py install' for demjson, since package 'wheel' is not installed.
Installing collected packages: demjson
    Running setup.py install for demjson ... done
Successfully installed demjson-2.2.3
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/example/venv/lib/python3.9/site-packages/demjson.py", line 645
    class json_int( (1L).__class__ ):    # Have to specify base this way to satisfy 2to3
                      ^
SyntaxError: invalid syntax
```

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by jaraco** [comment]
Good suggestion. I think I agree.

**Comment by arpheno** [comment]
I think this broke a lot of builds unintentionally.

**Comment by ikapelyukhin** [comment]
> I think this broke a lot of builds unintentionally.

It sure did. :grimacing:

**Comment by plumdog** [comment]
My intention when raising this issue was to make it so builds fail, rather than getting runtime errors because 2to3 wasn't applied to a dependency that needs it. That is, this behaviour breaks builds intentionally where the setuptools version and the dependencies are incompatible.

**Comment by mattclay** [comment]
@plumdog Unfortunately the implementation in https://github.com/pypa/setuptools/pull/2770 also breaks builds which explicitly disable the `use_2to3` feature, which would otherwise install correctly.

**Comment by plumdog** [comment]
@mattclay Oh. 😬

**Comment by ajnelson-nist** [comment]
Commenting as one of the folks whose CI is now halted because of this Issue's resolution:
#2770 's effect is something I think could be safely considered "Backwards-incompatible."  In SEMVER terms, I would have expected it to come out in a major release (`v59.0.0`) rather than a patch release (`v58.0.2`).

I appreciate the patch addresses a bug in the build system.  I would have preferred to get a deprecation warning rather than a build-halt, as I'm in a corner case that was impacted as collateral damage: The projects I work with that are affected by this were using the `use_2to3` flag in a somewhat vestigial manner.  They work fine at import time.  But, they now cause any downstream imports to fail if I'm using up-to-date `setuptools`.

Would it be possible to adjust the resolution of this Issue to raise a `DeprecationWarning`, reverting and postponing the full effect of #2770 to `v59.0.0`?
I'd respect a "No," as I'm not quite sure I follow all of the background preceding this Issue---`2to3` used be imported by `setuptools`, but now isn't?---and I also respect that an install-time `DeprecationWarning` might not be appreciated by someone hitting the run-time error.  But I'd like to hope we can have a more socialized and time-smoothed approach to sunsetting this property.

**Comment by jaraco** [comment]
Note that the hard failure is the preferred behavior for packages where 2to3 isn’t just a vestige but is needed to make the code viable. It’s only in your reported case where use2to3 is true but unneeded that it might be valuable not to hard fail.

You’re right that it’s very difficult to surface deprecation warnings. I wish This project could go back 8 years and deprecate this functionality, but even if this project had, I’m not confident that would have substantially limited the disruption.


> Would it be possible to adjust the resolution of this Issue to raise a `DeprecationWarning`, reverting and postponing the full effect of #2770 to `v59.0.0`?

Would this approach help if the full effect were released immediately as v59? Would the CI still be broken? How long would you recommend to postpone the hard failure?

**Comment by arpheno** [comment]
In particular this broke all `apache-airflow` builds if you need more reports of unintentionally breaking builds.

**Comment by jaraco** [comment]
> In particular this broke all `apache-airflow` builds if you need more reports of unintentionally breaking builds.

Specifically, https://github.com/apache/airflow/issues/18075, which is now fixed.

**Comment by ajnelson-nist** [comment]
> > Would it be possible to adjust the resolution of this Issue to raise a DeprecationWarning, reverting and postponing the full effect of #2770 to v59.0.0?
>
> Would this approach help if the full effect were released immediately as v59? Would the CI still be broken? How long would you recommend to postpone the hard failure?

Speaking to my understanding (which I won't claim is perfect) of SEMVER, I would suppose a feature deprecation would occur in a minor release (using the "major.minor.patch" version vector), and the deprecation would warn that the feature is to be removed in either the next major release or the following major release.

I don't have a good feel for what that should translate to in calendar days in this situation.  Some, but not all, projects my community uses were able to resolve matters within a week of our CI halting.  The resolutions weren't always trivial.

I do agree it's better to prevent runtime issues by catching at install-time.  I think there should have been more warning than the timeline of this ticket---opened-to-merged within a day?  I had a glance through other `2to3` tickets, and saw there actually was a plan to deprecate `use_2to3` in [2086](https://github.com/pypa/setuptools/issues/2086), but it looks like that didn't become a squawk from the build system, so I'm not sure how well socialized the deprecation was.

I think it would be a preferable situation to get deprecation warnings until at least the next major `setuptools` release; this is me appealing to not have a patch-release break builds.  It might be helpful for the warnings to include a pointer to documentation on how to remove a project's dependence on the `use_2to3` flag.  Would an inlined suggestion to follow the directions around `2to3 -w` on [the 2to3 documentation](https://docs.python.org/3/library/2to3.html) help?

2086 sets a time point for `lib2to3` not being available, and I now see the deprecation notice for `lib2to3` at the *bottom* of the `2to3` page.  If that notice doesn't move to the top of that page, it might also be helpful to note Python 3.10's stance on `lib2to3` in a deprecation warning.

**Comment by jaraco** [comment]
> I think there should have been more warning than the timeline of this ticket---opened-to-merged within a day?

Right, because in my mind, this ticket identified an unanticipated flaw in the release of v58.0.0 where the feature was (intentionally) broken, but the builds weren't failing and were instead creating invalid builds. I chose to violate semver because v58.0.0 had only been out a few days and I wished to correct for the flaw ASAP. Ideally, this change would have been part of the original v58.0.0 release.



> I think it would be a preferable situation to get deprecation warnings until at least the next major `setuptools` release.

I don't believe there's any value in rolling back this change to a DeprecationWarning (thereby re-enabling the silently-breaking builds) only to immediately release a v59 which once again breaks. What value would that add? Users of the latest setuptools version would still be broken. And those that need to pin Setuptools could already pin to `<58`, so pinning to `<59` for a version that issues deprecation warnings and makes broken builds seems like the worst of all worlds to me.

> this is me appealing to not have a patch-release break builds.

Agreed. And I would fix it if I thought that doing so would benefit anybody. I could, for example, yank v58.0.2+ and release v59 to correct the semver violation, but how much would that help at this point?


> Would an inlined suggestion to follow the directions around `2to3 -w` on [the 2to3 documentation](https://docs.python.org/3/library/2to3.html) help?

I suspect not. I've been actively seeking out projects affected by this change and working to address the issues in those projects. The hardest part seems not to be how to port the code but how to package it up and get it released. You're welcome to propose a change to the error message or documentation, but until I see at least one example where someone can show that it would have helped, I'm not keen to invest that effort.

**Comment by ajnelson-nist** [comment]
@jaraco , I apologize, I just found I'd forgotten to reply.

Your reasoning makes sense, and I won't push the issue further.  What I hadn't appreciated fully is that `2to3`-related breakage was supposed to be introduced with this major release.  Thank you for the kind discussion.
