### ISSUE TITLE
use_2to3 is invalid (ibm_db)

### ISSUE THREAD

**Issue by caixiangibm** [pypa/setuptools#2787]
### setuptools version

setuptools==58.0.4

### Python version

Python 3.6

### OS

Linux Centos 8

### Description

Our build failed when using setuptools-58.0.4 and then to install ibm_db, it had worked with setuptools==57.5.0

```
pip3 install --upgrade setuptools PyYAML
=> Successfully installed PyYAML-5.4.1 setuptools-58.0.4
pip3 install --no-cache-dir ibm_db
Collecting ibm_db
  Downloading https://files.pythonhosted.org/packages/dc/7c/26c1eb0ce78689a6a6775337b43f498f8e901790ec0bafd6f24e2ef594af/ibm_db-3.0.4.tar.gz (796kB)
    Complete output from command python setup.py egg_info:
    Detected 64-bit Python
    Downloading https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz
    error in ibm_db setup command: use_2to3 is invalid.
```

### Expected behavior

setuptools-58.0.0+ need to support use_2to3

### How to Reproduce

As mentioned in Description

### Output

```
pip3 install --no-cache-dir ibm_db
Collecting ibm_db
  Downloading https://files.pythonhosted.org/packages/dc/7c/26c1eb0ce78689a6a6775337b43f498f8e901790ec0bafd6f24e2ef594af/ibm_db-3.0.4.tar.gz (796kB)
    Complete output from command python setup.py egg_info:
    Detected 64-bit Python
    Downloading https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz
    error in ibm_db setup command: use_2to3 is invalid.
```

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by jaraco** [comment]
[That project](https://pypi.org/project/ibm-db/#history) does appear to be actively developed. The "homepage" leads back to PyPI, so I'd suggest emailing the maintainers and ask if they're aware of the issue and if they can issue a fixed version. I'm happy to advise on a fix if needed.

**Comment by caixiangibm** [comment]
@jaraco , would you advise how to fix here or input into this ibmdb git issue - https://github.com/ibmdb/python-ibmdb/issues/655?
It seems that some persons are being blocked as "use_2to3 is invalid" error in their builds.

**Comment by WhyNotHugo** [comment]
I'm seeing this same error with a different package (`suds-jurko`) on my CI setup too:

https://github.com/jazzband/django-payments/pull/268/checks?check_run_id=3646180494

Any hints on how to work around this other than pinning `setuptools`? Pinning setuptools is bound to be incompatible with downstream setups.

**Comment by jaraco** [comment]
In the linked issue and other issues linked to it, I've demonstrated that the workaround provided does the trick. I've also published an sdist in devpi that does install under pip. I've furthermore gone an extra step and provided a proposed change to move the codebase to a single, shared codebase rather than rely on 2to3. I'm considering this issue closed, but I will be happy to assist if these contributions aren't enough to get this project unblocked.

**Comment by WhyNotHugo** [comment]
@jaraco Can you clarify what that workaround is?

I've tried adding this to `pyproject.toml`:

```toml
[build-system]
# Pin setuptools to an older version, since suds-jarko
# doesn't build with the latest.
requires = ["setuptools<58"]
build-backend = "setuptools.build_meta"
```

But `pip install` still fails. I've tried pinning via `setup_requires` in `setup.py`, but that didn't work either:

```python
setup_requires=["setuptools<58"]
```

**Comment by jaraco** [comment]
Until ibm_db releases a new version with the fix, you have a couple of options:

# Pin Setuptools

To pin Setuptools, you have to install the older version of Setuptools prior to installing ibm_db. You can't do this through pyproject.toml or setup_requires (because it has to affect the environment). You also need to disable build isolation to allow ibm_db to build. Ex:

```
pip install "setuptools<58"
pip install --no-build-isolation ibm_db
# uninstall setuptools or install preferred version
# finally, pip install anything else
```

# Install from a patched file

I've uploaded a patched version of ibm_db. If you install from there, you'll get the version declaring the pinned Setuptools:

```
pip install -i https://m.devpi.net/jaraco/dev ibm_db
# or 
pip install -i https://m.devpi.net/jaraco/dev mypackage  # depends on ibm_db
```

I would only recommend this approach in low-security situations or where you can also verify the SHA hash:

`sha256=0ad5b913eac1da2d4050d09dc93e068eb7ef437a6384b6e4aca02fa9cf1ad154`

# Build a wheel

Another solution could be to build a wheel of the project (using one of the techniques above) and then save that wheel to a trusted location and reinstall from there.

```
pip install "setuptools<58"
pip wheel --no-build-isolation ibm_db
# then pip install that wheel on similar architectures
```

**Comment by jaraco** [comment]
I notice, though, you mention `suds-jurko` in your attempt. Although some projects could use similar mitigations, the mitigations for that project may be different. Please follow #2784 for suds-jurko.

**Comment by jaraco** [comment]
FYI - ibm_db has released a new version.
