### ISSUE TITLE
[BUG] Unable to install with PyPy on macOS 11

### ISSUE THREAD

**Issue by radarhere** [pypa/setuptools#2929]
### setuptools version

59.6.0

### Python version

PyPy 7.3.7 (3.7.12 and 3.8.12)

### OS

macOS

### Additional environment information

This is happening on GitHub Actions.

### Description

Over at python-pillow, we started experiencing an error when installing with setuptools with PyPy on macOS. This only starting happening after GitHub Actions upgraded to macOS 11.

### Expected behavior

I expected a successful setuptools install.

### How to Reproduce

Here is my minimal reproduction - https://github.com/radarhere/Pillow/tree/pypy. This can be seen failing at https://github.com/radarhere/Pillow/actions/runs/1581698128, only for PyPy on macOS 11.

### Output

Part of the output from GitHub Actions is
```console
Installed /Users/runner/hostedtoolcache/PyPy/3.8.12/x64/lib/pypy3.8/site-packages/UNKNOWN-1.0.0-py3.8-macosx-10.7-x86_64.egg
Processing dependencies for UNKNOWN==1.0.0
Searching for UNKNOWN==1.0.0
Reading https://pypi.org/simple/UNKNOWN/
No local packages or working download links found for UNKNOWN==1.0.0
error: Could not find suitable distribution for Requirement.parse('UNKNOWN==1.0.0')
```

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by jaraco** [comment]
I can confirm. Using your repro and running `setup.py install`, I get the same error. Without the repro, this would have been difficult to even verify, so thanks for that.

Interestingly, if I run `setup.py install` a second time after the failure, it does succeed.

Even if I remove the target env and rebuild it, the error does not occur.

Only when I `rm -r *.egg-info` does the problem recur.

I suspect that something is happening between pypy and macos 11 that's breaking assumptions around sys.path and the current working directory, and so pkg_resources doesn't find the package immediately after installing it.

Good news, though, is that `pip install .` works fine even under the conditions where `setup.py install` fails.

Since `setup.py install` is [deprecated](https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html), I recommend to instead use `pip install`. Is there a reason you're not using that already?

Given the deprecated nature, I'm somewhat reluctant to ascertain the root cause of the issue, but if you're willing to dig deeper to identify the cause and propose a patch, I'd consider it as long as it doesn't add too much complication to the implementation.

**Comment by radarhere** [comment]
No reason to not use `pip install`, no - thanks very much for figuring that out!
