### ISSUE TITLE
[BUG] stdlib test_distutils on python3.8 runs only with SETUPTOOLS_USE_DISTUTILS=stdlib

### ISSUE THREAD

**Issue by mattip** [pypa/setuptools#2965]
### setuptools version

setuptools==60.0.0

### Python version

Python 3.8

### OS

Ubuntu 20.04

### Description

Collecting the stdlib test_distutils.py test suite fails unless I use SETUPTOOLS_USE_DISTUTILS=stdlib with setuptools>60

### Expected behavior

I can set SETUPTOOLS_USE_DISTUTILS=stdlib, but thought this should work without it?

### How to Reproduce

```console
$ sudo apt install libpython3.8-testsuite python3-venv
$ python3.8 -venv /tmp/venv_py3.8
$ /tmp/venv_py3.8/bin/python /usr/lib/python3.8/test/test_distutils.py
# tests run, 2 fail
$ /tmp/venv_py3.8/bin/python -m pip install "setuptools>59"
...
Successfully installed setuptools-60.1.0
$ /tmp/venv_py3.8/bin/python /usr/lib/python3.8/test/test_distutils.py
Traceback (most recent call last):
  File "/usr/lib/python3.8/test/test_distutils.py", line 8, in <module>
    import distutils.tests
ModuleNotFoundError: No module named 'distutils.tests'
```

### Output

```console

$ /tmp/venv_py3.8/bin/python /usr/lib/python3.8/test/test_distutils.py
Traceback (most recent call last):
  File "/usr/lib/python3.8/test/test_distutils.py", line 8, in <module>
    import distutils.tests
ModuleNotFoundError: No module named 'distutils.tests'
```

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by jaraco** [comment]
The way the distutils hack works, it makes Setuptools' own copy of distutils take precedence over the standard library, so causes `import distutils` to put `sys.modules['distutils'] = <setuptools._distutils>`. So it's not a big surprise to me that running the tests from the standard library against code not in the standard library will have problems.

What is something of a surprise is the error message you encountered. I don't encounter that error if I run [`.tox/python/bin/python -m test.test_distutils`](https://gist.github.com/jaraco/6d27cebd4e86a8f978201d315d620b36) from the setuptools source.

I'm guessing that because [`packages.find` excludes `tests*` and `*.tests`](https://github.com/pypa/setuptools/blob/dcdeedbed77711549f41e1f46f186c94ef9c4657/setup.cfg#L35-L36), that means that the tests get omitted on install, so that `distutils.tests` package simply isn't present.

My recommendation would be to continue to run tests with `=stdlib` or to avoid running those tests. I know some people have invested energy into ensuring that Setuptools doesn't install its tests, so it's not a mistake that the distutils tests aren't present either. And even if they were present, having them execute when running stdlib tests doesn't seem like the right or intended behavior.

Do you have any other recommendations in mind?

**Comment by frapa-az** [comment]
Hi, I just got stuck in a similar error. On python 3.8 (which by the way is the default on ubuntu 20.04 LTS), with setuptools 60.x I am unable to install packages in editable mode without `SETUPTOOLS_USE_DISTUTILS=stdlib`. If I downgrade, install normally or add `SETUPTOOLS_USE_DISTUTILS=stdlib` the installation works as expected.

Here a reproducible example:

[setuptools_60_issue.zip](https://github.com/pypa/setuptools/files/7838364/setuptools_60_issue.zip)

To reproduce, perform the following steps in the unpacked folder:

```bash
$ docker build . -t setuptools_60_issue
$ docker run -it setuptools_60_issue
root@cfb245293780:/#

# As expected if the module is not installed if fails
root@cfb245293780:/# python3 -c "import example_mod"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'example_mod'

# But it also fails when the module is installed in editable mode
root@cfb245293780:/# pip install -e package/
Obtaining file:///package
Installing collected packages: setuptools-60-issue
  Running setup.py develop for setuptools-60-issue
Successfully installed setuptools-60-issue
root@cfb245293780:/# python3 -c "import example_mod"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'example_mod'
```
