### ISSUE TITLE
[BUG] Problem installing package that depends on automatic `build_py_2to3` conversion.

### ISSUE THREAD

**Issue by egaudry** [pypa/setuptools#2997]
### setuptools version

setuptools==60

### Python version

Python-3.7

### OS

Linux (Rocky Linux 8.5 aarch64)

### Additional environment information

aarch64, not x86_64 related.

### Description

Observed when building numexpr with setuptools==60.3.0, setuptools when launched from a custom build of python on aarch64 believes it deals with python2 when it is actually python3.

### Expected behavior

Proper python3 detection.

### How to Reproduce

pip install setuptools==60.3.0
pip install --no-binary :all: numexpr==2.7.3 --verbose

check numexpr/__init__.py file, it contains python2 syntax, same goes for "long" used in numexpr/expression.py

### Output

```$ cat /usr/local/bin/python-3.7.10/lib/python3.7/site-packages/numexpr/__init__.py 
###################################################################
#  Numexpr - Fast numerical array expression evaluator for NumPy.
#
#      License: MIT
#      Author:  See AUTHORS.txt
#
#  See LICENSE.txt and LICENSES/*.txt for details about copyright and
#  rights to use.
####################################################################

"""
Numexpr is a fast numerical expression evaluator for NumPy.  With it,
expressions that operate on arrays (like "3*a+4*b") are accelerated
and use less memory than doing the same calculation in Python.

See:

https://github.com/pydata/numexpr

for more info about it.

"""

from .__config__ import show as show_config, get_info
```

the ```.__config__``` is expected, not ```__config__ ```

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by abravalheri** [comment]
Hi @egaudry, thank you very much for reporting this.

Any chance this problem is the same described in #2979?
i.e., any chance `numexpr==2.7.3` relies on the deprecated `build_py_2to3` command?

This command used to be present in old versions of setuptools and distutils.
Depending on the version of Python you have installed in your machine, the stdlib version of `distutils` might still have this command available, but you will need to export the environment variable `SETUPTOOLS_USE_DISTUTILS=stdlib` to use it during the build.

Please notice the automatic 2to3 syntax conversion was deprecated and removed a while ago, so I personally would recommend using a more recent version of the package.

**Comment by egaudry** [comment]
@abravalheri very likely indeed.
would you recommend closing this ticket and create another at numexpr instead then ?

**Comment by egaudry** [comment]
check done with SETUPTOOLS_USE_DISTUTILS=stdlib, confirming what @abravalheri suggested, hence closing this bug report.

thanks
