### ISSUE TITLE
[Docs] Spaces in code blocks look like underscores

### ISSUE THREAD

**Issue by not-my-profile** [pypa/setuptools#2999]
### Summary

I was looking at the [Quickstart documentation](https://setuptools.pypa.io/en/latest/userguide/quickstart.html), where I saw the following:

![image](https://user-images.githubusercontent.com/73739153/148210654-e45172a7-207f-4524-b7f6-dfe45d6130e7.png)

I read this as `______docutils` and `______requests` and got confused wondering why there are so many underscores.

### Additional Information

Removing the underline styling would remove this source of confusion.

**Comment by abravalheri** [comment]
Thank you very much @not-my-profile, that is a tricky one!

It seems that this happens because of a combination of problems with `pygments`:

![image](https://user-images.githubusercontent.com/320755/148215615-74783546-fe78-45cd-90ff-848460665806.png)

![image](https://user-images.githubusercontent.com/320755/148215512-343f371a-818a-440e-b20a-9813d8bb24c3.png)

I think the idea here is that the colour of the whitespace (`.w` class) should be the same as the background, but it ended up being misconfigured in the built-in css (instead of `#666666` in the first figure it should be `#202020` like in the second) - at least that is what happens in the light version of the theme (no idea why they want preserve the underline though).

My hypothesis is that this was introduced in [Pygments 2.11.0](
https://github.com/pygments/pygments/releases/tag/2.11.0) since they did a series of whitespace improvements.

**Comment by abravalheri** [comment]
The issue seems to be fixed in `pygments`, hopefully everything should be fine as soon as they release a new version.
