### ISSUE TITLE
[BUG] AttributeError: 'WindowsPath' object has no attribute 'read_text'

### ISSUE THREAD

**Issue by cz6ace** [pypa/setuptools#3071]
### setuptools version

setuptools==60.7.0

### Python version

3.8.10

### OS

Windows 10

### Description

There's regression in compare to previous setuptools==60.6.0  (which works)

E.g. installing latest setuptools and pip and then installing e.g. `pathlib` fails with following error: `AttributeError: 'WindowsPath' object has no attribute 'read_text'`

### Expected behavior

it works

### How to Reproduce

1. install latest pip (22.0.2)
2. install latest setuptools (60.7.0)
3. install pathlib using pip

### Output

```
python -m pip install -U pip
(cut)
pip install -U setuptools
(cut)

(venv) C:\Temp\setuptools>pip install -U pathlib
Collecting pathlib
  Using cached pathlib-1.0.1.tar.gz (49 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 14, in <module>
        File "c:\temp\setuptools\venv\lib\site-packages\setuptools\__init__.py", line 16, in <module>
          import setuptools.version
        File "c:\temp\setuptools\venv\lib\site-packages\setuptools\version.py", line 1, in <module>
          import pkg_resources
        File "c:\temp\setuptools\venv\lib\site-packages\pkg_resources\__init__.py", line 74, in <module>
          from pkg_resources.extern.jaraco.text import (
        File "c:\temp\setuptools\venv\lib\site-packages\pkg_resources\_vendor\jaraco\text\__init__.py", line 227, in <module>
          lorem_ipsum: str = files(__name__).joinpath('Lorem ipsum.txt').read_text()
      AttributeError: 'WindowsPath' object has no attribute 'read_text'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by abravalheri** [comment]
Hi @cz6ace, that you very kcih for bringing this up.

Is this error related to the fact you are installing `pathlib` specifically?

Can you reproduce this error without installing an external `pathlib` (or any package with a dependency on it)?

`pathlib` is suppose to be provided by the stdlib. (I.e. it should come with the Python installation, not from a package in PyPI). Overwriting it with a 3rd party package is problematic.

I also noticed that the PyPI package has a warning about being no longer maintained: https://pypi.org/project/pathlib/. This is a sign that the API is no longer compatible with the API provided in the stdlib, and probably the origin of the error you are facing.

**Comment by parthea** [comment]
@abravalheri, Is it possible that a breaking change was introduced in 60.7.0? I haven't figured out how to work around the issue yet. I only encountered this issue today after [60.7.0](https://pypi.org/project/setuptools/60.7.0/) was released. I think I'm going to try re-creating the issue with a fresh environment and see if the issue still exists. There are only [2 reports](https://github.com/search?q=%22from+pkg_resources.extern.jaraco.text+import%22&type=issues) on all of github with this stacktrace so I suppose it could be my environment.

**Comment by abravalheri** [comment]
Hi @parthea every release has a chance of breaking something for someone, so I don't discard the possibility, but the way this particular issue is described sounds like the problem is caused by a replacement of a module in the stdlib with a non-API compliant 3rdParty.

Either that or the Python docs are extremely misleading, since https://docs.python.org/3/library/pathlib.html seems to indicate `read_text` should be present (which I find very unlikely)

If anyone manage to create a reproduction without installing `pathlib` from PyPI (or a library that depends directly or indirectly from it), we can proceed with the investigation.

**Comment by abravalheri** [comment]
@parthea, for the problems you are facing, can you check if anyhow `pathlib` gets pulled from PyPI instead of being used from the stdlib?

If that is not the case, I think the best is to consider it has a different origin from the issue described here and open another ticket with a minimal reproduction.

**Comment by jaraco** [comment]
No one should be using `pathlib`. It was abandoned years ago and it masks the stdlib module and it doesn't even install on Python 3.10. If you need backward compatibility for pathlib, you should use `pathlib2`.

The reason the issue triggered with Setuptools 60.7 was because this version vendors jaraco.text, which utilizes importlib.resources/importlib_resources, which utilizes pathlib.

I apologize for the incompatibility. Setuptools could work around the issue, but it would be preferable for users to fix the root issue that pypi:pathlib is deprecated and should not be used at all.

**Comment by parthea** [comment]
I'm using the built-in pathlib so it is a different issue.

**Comment by cz6ace** [comment]
> Hi @cz6ace, that you very much for bringing this up.
> 
> Is this error related to the fact you are installing `pathlib` specifically?

We have the `pathlib` as a dependency, probably from `hexrec` package. Now I can see the most recent version got rid of it: "Removed dependency of legacy pathlib package; using Python’s own module instead."

> Can you reproduce this error without installing an external `pathlib` (or any package with a dependency on it)?

No, just with pathlib

At the end - we can easily fix to upgrade the `hexrec` package which do not rely on obsolete `pathlib` any more.

>No one should be using pathlib.

This ticket can be closed if I understand it correctly.
