### ISSUE TITLE
[BUG] Stray files in 60.9.2 release

### ISSUE THREAD

**Issue by mgorny** [pypa/setuptools#3115]
### setuptools version

60.9.2

### Python version

n/a

### OS

n/a

### Description

The `setuptools-60.9.2.tar.gz` (sdist) archive seems to include some stray files:

```
setuptools-60.9.2/tools/__pycache__/finalize.cpython-310.pyc
setuptools-60.9.2/tools/__pycache__/finalize.cpython-37.pyc
setuptools-60.9.2/tools/__pycache__/finalize.pypy37.pyc
setuptools-60.9.2/tools/__pycache__/ppc64le-patch.cpython-310.pyc
setuptools-60.9.2/tools/__pycache__/ppc64le-patch.cpython-37.pyc
setuptools-60.9.2/tools/__pycache__/ppc64le-patch.pypy37.pyc
setuptools-60.9.2/tools/__pycache__/vendored.cpython-310.pyc
setuptools-60.9.2/tools/__pycache__/vendored.cpython-37.pyc
setuptools-60.9.2/tools/__pycache__/vendored.pypy37.pyc
setuptools-60.9.2/tools/vendored.py.orig
```

### Expected behavior

No stray files ;-).

### How to Reproduce

```
wget https://files.pythonhosted.org/packages/bf/b0/b4599baf535aff5a8675f038a9b4b380df7e5de33c78a155e0883da05403/setuptools-60.9.2.tar.gz
tar -tf setuptools-60.9.2.tar.gz
```

### Output

```console
[...]
setuptools-60.9.2/tools/
setuptools-60.9.2/tools/__pycache__/
setuptools-60.9.2/tools/__pycache__/finalize.cpython-310.pyc
setuptools-60.9.2/tools/__pycache__/finalize.cpython-37.pyc
setuptools-60.9.2/tools/__pycache__/finalize.pypy37.pyc
setuptools-60.9.2/tools/__pycache__/ppc64le-patch.cpython-310.pyc
setuptools-60.9.2/tools/__pycache__/ppc64le-patch.cpython-37.pyc
setuptools-60.9.2/tools/__pycache__/ppc64le-patch.pypy37.pyc
setuptools-60.9.2/tools/__pycache__/vendored.cpython-310.pyc
setuptools-60.9.2/tools/__pycache__/vendored.cpython-37.pyc
setuptools-60.9.2/tools/__pycache__/vendored.pypy37.pyc
setuptools-60.9.2/tools/finalize.py
setuptools-60.9.2/tools/msvc-build-launcher-arm64.cmd
setuptools-60.9.2/tools/msvc-build-launcher.cmd
setuptools-60.9.2/tools/ppc64le-patch.py
setuptools-60.9.2/tools/towncrier_template.rst
setuptools-60.9.2/tools/vendored.py
setuptools-60.9.2/tools/vendored.py.orig
setuptools-60.9.2/tox.ini
```

**Comment by jaraco** [comment]
Well, that's annoying and unintended. I cut the release from my laptop due to issues in the CI release pipeline (https://github.com/pypa/setuptools/issues/3093#issuecomment-1041517254). I probably should have cleaned up ignored files first. Nothing I can do about it for this release and I do prefer to use the CI pipelines for releases in general. I do have plans to adopt `setuptools_scm` (#2656), which would have avoided this issue (even for a local release with ignored files). It's conceivable this project could invest energy in getting the perfect MANIFEST.in to match what's in the SCM, but that sounds uninteresting and toilsome to me.

Thanks for the report. Please feel free to follow up with more details, especially if you experienced issues beyond the basic annoyance/flux.

**Comment by mgorny** [comment]
Nah, just wanted to give you a heads up in case you changed the release process and something went wrong.
