### ISSUE TITLE
[BUG] setuptools 64.0.0 breaks editable install

### ISSUE THREAD

**Issue by ajasmin** [pypa/setuptools#3504]
### setuptools version

setuptools==64.0.0

### Python version

Python 3.10.6

### OS

Ubuntu jammy

### Description

After creating a simple project and installing it as editable with `pip install -e`, I'm unable to import modules from the package.

### Expected behavior

We should be able to import a package installed as editable.

### How to Reproduce

*1. Create this simple project structure*

`pyproject.toml`
```
[build-system]
requires = [
  "setuptools==64.0.0",
  "wheel",
]
build-backend = "setuptools.build_meta"

[project]
name = "foo"
version = "1.0.0"

[tool.setuptools]
packages.find.include = ["foo.*"]
```

`setup.py`
```
from setuptools import setup

setup()
```

`foo/__init__.py`
```
__version__ = "1.0.0"
```

*2. Create and activate a venv:*
```
python -mvenv venv
. venv/bin/activate
```

*3. Install the project as editable:*
```
python install -e .
```

Change to another directory and try to import the package:
```
python -c "import foo"
```

### Output

```console
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'foo'
```

**Comment by abravalheri** [comment]
Hi @ajasmin thank you very much for reporting this.

I went through your reproduction steps, but I have a doubt: have you activated your virtual environment? (It does not seem to be part of the steps).

Instead of relying on the activation steps, I tried to reproduce the same experiment, but using the path to the Python executable directly. This is what I run in my terminal:

```bash
cd /tmp
rm -rf foo
mkdir -p foo/foo
cd foo
cat <<EOF > pyproject.toml
[build-system]
requires = [
  "setuptools==64.0.0",
  "wheel",
]
build-backend = "setuptools.build_meta"

[project]
name = "foo"
version = "1.0.0"

[tool.setuptools]
packages.find.include = ["foo.*"]
EOF

cat <<EOF > setup.py
from setuptools import setup

setup()
EOF

echo '__version__ = "1.0.0"' > foo/__init__.py

python3.8 -mvenv venv

./venv/bin/python -m pip install -e .

cd /tmp

/tmp/foo/venv/bin/python -c "import foo"
```

... I cannot see any error with these steps.

Could you please verify if the same problem persists if you use:

a) the activation script before running Python
b) the explicit path for the Python executable

?

If you still see the error, maybe we will need to create a reproducer using something like a container...

**Comment by ajasmin** [comment]
> I went through your reproduction steps, but I have a doubt: have you activated your virtual environment? (It does not seem to be part of the steps).

I activated the venv in my tests it was missing from the description.

**Comment by abravalheri** [comment]
> I activated the venv in my tests it was missing from the description.

Umm... Could you also try using the explicit path instead of the activation script?

**Comment by abravalheri** [comment]
Sorry @ajasmin, my bad! I don't trust the activation script in my own machine so I biased against it.

There was an error when I tried to replicate the error: when I `cd` into the `tmp` folder but the root directory of the project was also named `foo` and that created another acidental namespace package...

I was able to replicate your error by renaming the root directory to a name different than the package.

---

What is happening here is not related to the editable installation, you should be able to have the same error even if you omit `-e` and use v63 of setuptools, for example by running:

```bash
cd /tmp
rm -rf proj
mkdir -p proj/foo
cd proj
cat <<EOF > pyproject.toml
[build-system]
requires = [
  "setuptools==63.0.0",
  "wheel",
]
build-backend = "setuptools.build_meta"

[project]
name = "foo"
version = "1.0.0"

[tool.setuptools]
packages.find.include = ["foo.*"]
EOF

cat <<EOF > setup.py
from setuptools import setup

setup()
EOF

echo '__version__ = "1.0.0"' > foo/__init__.py

python3.10 -mvenv venv

/tmp/proj/venv/bin/python -m pip install .

cd /tmp

/tmp/proj/venv/bin/python -c "import foo"
```

The reason why the experiment is failing is related to the line:

```
packages.find.include = ["foo.*"]
```

`include` simply runs a glob pattern matcher with the names of the packages. In your case the package name is `foo` which does not match `foo.*` because it  does not contain a `.`.

If you replace:

```diff
- packages.find.include = ["foo.*"]
+ packages.find.include = ["foo*"]
```

things should work.

---

This behaviour is explained in our [docs](https://setuptools.pypa.io/en/latest/userguide/package_discovery.html):

> *include* and *exclude* accept strings representing [glob](https://docs.python.org/3/library/glob.html#module-glob) patterns. These patterns should match the full name of the Python module (as if it was written in an import statement).
>
> For example if you have `util` pattern, it will match `util/__init__.py` but not `util/files/__init__.py`.
>
> The fact that the parent package is matched by the pattern will not dictate if the submodule will be included or excluded from the distribution. You will need to explicitly add a wildcard (e.g. `util*`) if you want the pattern to also match submodules.

**Comment by abravalheri** [comment]
Please let me know if this works for you!

**Comment by NickCrews** [comment]
@abravalheri I think it is a difference between 63 and 64, I think I'm getting hit with this.

[This PR](https://github.com/dedupeio/dedupe/pull/1081), which uses `setuptools>=64`, fails CI with `package dedupe has no attribute ...` errors.
So I made a [followup PR](https://github.com/dedupeio/dedupe/pull/1082), identical to the other except I swapped to `setuptools==63`, and that one is fine (well there is one failing test, but that is unrelated).

**Comment by ajasmin** [comment]
> `include` simply runs a glob pattern matcher with the names of the packages. In your case the package name is `foo` which does not match `foo.*` because it does not contain a `.`.

Thank you! I will make the change.

Though, for what's it worth. there is a behavior change in 64. I've written a Dockerfile.

Changing the `setuptools==64.0.0`to `setuptools==63.*` will make the import work.

```Dockerfile
# syntax=docker/dockerfile:1.4

FROM ubuntu:jammy

RUN export DEBIAN_FRONTEND=noninteractive && \
	apt-get update -yq && \
	apt-get install -yq python3-full

RUN mkdir -p my_project/foo/bar
RUN printf '%s\n' \
'[build-system]' \
'requires = [' \
'  "setuptools==64.0.0",' \
'  "wheel",' \
']' \
'build-backend = "setuptools.build_meta"' \
'' \
'[project]' \
'name = "foo"' \
'version = "1.0.0"' \
'' \
'[tool.setuptools]' \
'packages.find.include = ["foo.*"]' \
> my_project/pyproject.toml

RUN printf '%s\n' \
'from setuptools import setup' \
'' \
'setup()' \
> my_project/setup.py

RUN echo '__version__ = "1.0.0"' > my_project/foo/bar/__init__.py

RUN tail -n +1 $(find my_project -type f)

RUN python3 -mvenv venv

RUN venv/bin/python -m pip install -U pip==22.2.1
RUN venv/bin/python -m pip install -e my_project

RUN mkdir t

RUN cd t && ../venv/bin/python -c "import foo.bar"

```

**Comment by P403n1x87** [comment]
We started getting the same issue in our CI jobs. All of a sudden, our library started failing importing a variable from a module. Adding the requirement `setuptools<64` to `pyproject.toml` also fixed the issue for us. However, we also have discovered that by rearranging some of our imports also works: https://github.com/DataDog/dd-trace-py/pull/4079#issuecomment-1212922688. The actual problem in CI can be seen here: https://github.com/DataDog/dd-trace-py/runs/7801873067?check_suite_focus=true (it's a big output because of the error; searching for `ImportError: cannot import name ORIGIN_KEY` will bring you to the point where the import error occurs).

I think it would be interesting to understand whether this is a regression in `setuptools` or an issue that has always been there in our library, and that the latest release of `setuptools` has brought up. At this point in time, I'd be inclined to think the former is more likely, based on other comments in this issue report.

**Comment by abravalheri** [comment]
Ok, I think I understand what is happening based on the example provided in https://github.com/pypa/setuptools/issues/3504#issuecomment-1212585233. Thank you very much @ajasmin.

#### Deep explanation

- The given package configuration is effectively telling setuptools to include in the wheel all the packages named `"foo.*"`, but to not include the `foo` package itself.
- In a regular installation setuptools will try to follow this configuration. However, (since packages are implemented in Python as normal directories) in order to create the `foo.bar` package, `setuptools` will add the `foo/bar/__init__.py` path to the wheel (which is a regular zip file).
- When the wheel file gets unzipped, the directory `foo/bar` will be created, and therefore also the directory `foo`.
- Since a regular directory is also a valid Python package (even if it does not include a `__init__.py`) a new `foo` [namespace package](https://docs.python.org/3/reference/import.html#namespace-packages) gets created as a side-effect.
  - This `foo` namespace package does not exactly correspond to the `foo` directory in the original project source tree:
    - For example, if you add Python files there (e.g. `my_project/foo/other.py`), they will be ignored and not added to the wheel.
    - Consider it as a brand new, unrelated, `foo` directory that gets created automatically to allow the `foo/bar` directory to exist.

In an editable installation, we don't have to use directories, we can do the installation using [custom import hooks](https://docs.python.org/3/reference/import.html#import-hooks)... This way, it is possible that the the "side effect" of creating `foo` as a namespace package is not observed, and the import fails.

#### Next steps

Since the idea of an editable installation is to emulate how a regular installation works, this is very definitely a bug. I think I have found a solution and I am working on a PR. Thank you for the patience.

**Comment by abravalheri** [comment]
If anyone reading this still experience any problems after installing the latest version, please feel free to comment in this issue and I can reopen it after a quick investigation.

**Comment by P403n1x87** [comment]
@abravalheri I think this is still broken: https://github.com/DataDog/dd-trace-py/runs/7818500434?check_suite_focus=true

**Comment by abravalheri** [comment]
Hi @P403n1x87 thank you very much for reporting this.
It seems that v64.0.3 fixes the issue reported in this ticket, which matches this reproducer: https://github.com/pypa/setuptools/issues/3504#issuecomment-1212585233.

Maybe this is a separated problem? Could you please open a new issue with the steps to reproduce the error? (If you can simply it to a minimal example, that would help a lot).

**Comment by kasium** [comment]
I have an issue since setuptools 64 (and also with 65) when using a local flake8 plugin. I have eliminated flake8 and drilled it down to a single import.

**With setuptools <64**

_pyproject.toml_
```toml
[build-system]
requires = ["setuptools<64", "wheel"]
build-backend = "setuptools.build_meta"
```

_setup.py_
```py
from setuptools import find_packages, setup

if __name__ == "__main__":
    setup(packages=find_packages(include=("src",)))
```

_src/\_\_init__.py_
```py
import plugin
```

Create also an empty _plugin.py_ in the root dir.
Running then `pip install -e .` and then `python src/__init__.py` works fine.

**With setuptools >=64**

* Change the version in the ``pyproject.toml`
* `pip install -e .` 
* `python src/__init__.py`

```
Traceback (most recent call last):
  File "src/__init__.py", line 1, in <module>
    import plugin
ModuleNotFoundError: No module named 'plugin'
```

I'm aware that `plugin.py` is not part of wheel, but before it worked fine. Also from the changelog it's not obvious what I need to do to get it back to work.

**Comment by abravalheri** [comment]
> I'm aware that plugin.py is not part of wheel, but before it worked fine.

I am sorry to hear you are having problems @kasium, but one of the main reasons why the implementation was done in the way it was done is exactly to prevent spurious files that are not part of the package to be "installed". So my opinion is that this should not be reverted.

Editable installs should emulate as much as possible the installation and that is what setuptools is trying to do here. The fact that `plugin.py` file was "installed" before version 64 can be considered a bug.

You are right in saying that the changelog does not obviously point in that direction. I can add some text there to make sure this message is clear. Also please feel free to suggest a modification in the changelog file to reflect the limitation that you found.

**Comment by abravalheri** [comment]
@P403n1x87, based on https://github.com/DataDog/dd-trace-py/pull/4093, it seems that the issue is related to the behaviour of the import statement in a Cython file (probably)...

Please feel free to open a different issue if you find a different bug in setuptools implementation.

**Comment by kasium** [comment]
@abravalheri thanks for your fast support. 
A possible text could be "Note, that files which were included before but were not part of the package might not be included anymore".

Is the only solution to include the files in the `packages`? The idea is, that I need `plugin` during development and in the CI but it should not be exposed in the wheel

**Comment by brettlangdon** [comment]
> @P403n1x87, based on the deep investigative work exposed in [DataDog/dd-trace-py#4093](https://github.com/DataDog/dd-trace-py/pull/4093) (thank you very much @brettlangdon ❤️), it seems that the issue is related to the behaviour of the import statement in a Cython file (probably)...
> 
> Please feel free to open a different issue if you find a different bug in setuptools implementation.

Yes, from my investigation it seems to be related to how Cython < 3 implements `__Pyx_Import`. I haven't dug far enough into what about Cython 3 fixes it, or why it was working with `.egg-link` but not the `.pth`/loader approach. It _seems_ like Cython is just calling `__import__`.

I haven't decided if I am going to keep digging further since we have a mitigation at this time, but I am curious if anyone has any thoughts.

**Comment by abravalheri** [comment]
> Is the only solution to include the files in the `packages`? The idea is, that I need `plugin` during development and in the CI but it should not be exposed in the wheel

I believe there are a few different ways of achieving this, just to mention a few:

- You might try placing `plugin.py` in a directory and then adding that directory to the `PYTHONPATH` environment variable.
- You can change the way you are invoking your script to rely on the fact that the `python` executable will add some directories automatically to `sys.path`:
  - when you call `python` with a script, it will add the script's directory to `sys.path`. So by running `python my/script.py`, the `my` folder ends up in `sys.path`,
  - however, when you call `python` with a module (e.g. `python -m my.module`), `$PWD` is automatically added to `sys.path`... You can take advantage of that.

**Comment by kasium** [comment]
@abravalheri thanks a lot. Fyi: in my case with setuptools <64, a file `easy-install.pth` is created in the site_packages which includes the full root path. I verified that this enabled the import of `plugin.py` by changing the path inside the file

**Comment by abravalheri** [comment]
> With setuptools 65 the file is empty

In setuptools < 64, setuptools uses an `.egg-link` file that adds your project directory to `sys.path` (which is considered flawed and undesirable). In setuptools > 64, setuptools will add a `__editable__.<something><something>` file that will load a ["finder"/"import hook"](https://docs.python.org/3/reference/import.html#finders-and-loaders) that will load precisely your top-level packages without adding the project directory to `sys.path`.

(This behaviour changes depending on "how safe" your project directory is).
