### ISSUE TITLE
[BUG] Setuptools 65 does not copy binary files (.so) in editable install

### ISSUE THREAD

**Issue by bashtage** [pypa/setuptools#3522]
### setuptools version

65.0.0

### Python version

3.9

### OS

Ubunty 20.04

### Additional environment information

Standard setup using Cythonized sources.  Cython to C then compiled to .so/.pyd files.

### Description

As of 65 the binary extensions are not being copied back into the tree when using an editable install.  This means that they are not available when importing the library.  The install command is very vanilla

```
python -m pip install -e .
```

### Expected behavior

The .so/.pyd files would be in the same directory as their target (which is the same as the .pyx files and their compiled c version).

### How to Reproduce

1. `pip install -e ,` for a project containing Cython
2. Check tree for missing extension modules

On linux,

```
git clone https://github.com/bashtage/arch
cd arch
python -m pip install -e .
ls arch/univariate/recursions*
````

Note that the .so is missing when using 65.  If using an older setuptools, e.g., 63.
### Output

```console
The error depends on whether the binary modules are required.
```

**Comment by misl6** [comment]
I have a similar issue since `setuptools>=64`, and I may have found the root cause.

Looks like you're doing something similar to me here:
https://github.com/bashtage/arch/blob/1b141cb7710b9c8ba2192038d9ea6158e75c201d/setup.py#L20

Basically, since this commit: https://github.com/pypa/setuptools/commit/075a3c801910a6b65dccf8b9eb26a0637315627a, `setuptools` added a way to export the output mapping, which is later used here: https://github.com/pypa/setuptools/blob/7021149ad29c30e4cccfa076dba30ede6ae205ee/setuptools/command/editable_wheel.py#L250 during editable installs.

**Why is failing for our similar use-cases:**

We both need to avoid using Cython when not available or could not be used, even if available.

I can see 3 different use-cases:

1. Do not use Cython `build_ext` as is not available
2. Do not use Cython even if available, as I can't use it. (`c` files are provided instead)
3. Feel free to use Cython, as is available and can be used.

On `setuptools<64.0.0`, a custom `build_ext` `cmdclass` based on top of `distutils.command.build_ext` ( case 1 and 2) or on top of `Cython.Distutils.build_ext` (case 3) worked great.

That's hacky, worked in past, but may not be the best way to do that.

**Additional:**
Looks like `setuptools` added a check on their side, here:
https://github.com/pypa/setuptools/blob/e6b911708e900f57c98e3b5b03af6de2953dbc76/setuptools/command/build_ext.py#L16-L24

That may be enough for case 1, but not for case 2.

(I'm currently investigating a way that avoids me to fall into case 2)

PS: Adding a switch that avoids the usage of `Cython.Distutils.build_ext` may be great BTW.

**Comment by bashtage** [comment]
Thanks.  Please let me know if you find a good solution - I have just pinned <64 for now.

**Comment by abravalheri** [comment]
Thank you very much @misl6 for the comprehensive summary.

Could you please expand a little bit more about the motivation of the use case 2 (which I believe is related to the suggestion of the switch you made...)?

In the case of a project with `pyproject.toml` the use case 3 should aways be the case, right? And if someone decides to call `python setup.py bdist_wheel` directly I suppose setuptools will automatically choose the most appropriate method depending on the availability of `Cython`, right?

---

Hi @bashtage , I believe a good solution here is to just use `setuptools.command.build_ext` directly, as it will automatically use Cython if it is installed, or fallback to pre-generated `.c` files otherwise.

**Comment by bashtage** [comment]
@abravalheri Thanks, I'll give it a try. FWIW I also do support scenario #2, although I mostly use it for testing.

**Comment by abravalheri** [comment]
I am preparing a PR to fix this issue, but I would be interested in learning about the second use case (just curiosity).

**Comment by misl6** [comment]
Sure!

So... from my recent tests (which are been done solely on my machine, so should not be considered exhaustive), as now `setuptools` correctly check if Cython is here, and looks usable, this hack is probably not needed anymore on our side.
I will try to set up some tests, so we can make sure of that.

BTW, at [Kivy](https://github.com/kivy), we need to cross-compile for Android and iOS, and Cython is not expected to be installed into the python environment used for the build, and neither on the one which runs on the mobile device. (And it seems that in past that was an issue for `setuptools`)

Let's consider that we have 3 Python environments:
1. The one the user is actually using to invoke the build script (which could be a virtualenv or not and does no matter how the user installed it)
2. `hostpython3`, which runs on the machine that is performing the build.
3. `python3`, which runs on the mobile device (iOS or Android)

`hostpython3` and `python3` are of the exact same version, and both are built by the build script.

Once we need to build a `Cython` package (and **kivy/kivy**, which have the `distutils` hack is one of them) the build is split into two major phases:
- `c` files are created from `pyx` via `Cython` which is installed into the environment **(1)**.
- Now that we have our `c` files, a build is performed via environment **(2)** (with the proper hacks) and then is copied to `python3` `site-packages` folder.

I tried to summarize as much as possible, and may not be fully clear, but feel free to give a look at [kivy](https://github.com/kivy/kivy), [python-for-android](https://github.com/kivy/python-for-android) and [kivy-ios](https://github.com/kivy/kivy-ios) 😄

**Comment by misl6** [comment]
So, in replying to "Why option 2 is needed":

This commit:  https://github.com/pypa/setuptools/commit/ca71bc26f65f1eac9f26b5e5b0d7b4109186fe59 probably fixed the issue which option 2 was trying to circumvent, at least on my use-case.

**Comment by abravalheri** [comment]
Thank you very much for the explanation @misl6!

> This commit: https://github.com/pypa/setuptools/commit/ca71bc26f65f1eac9f26b5e5b0d7b4109186fe59 probably fixed the issue which option 2 was trying to circumvent, at least on my use-case.

Yeah, in my mind that would be the case, I was just trying to understand if you need to prevent setuptools from automatically using Cython's class...

Anyway, I should release the patch soon (the CI is probably going to take some time until it is fully published). Hopefully that will prevent other builds to fail.

**Comment by bashtage** [comment]
@abravalheri your suggestion worked for me, thanks.
