### ISSUE TITLE
[BUG] release v65.6.0 breaks packages downstream due to removal of `distutils.log.Log`

### ISSUE THREAD

**Issue by sphuber** [pypa/setuptools#3693]
### setuptools version

65.6.0

### Python version

Python 3.10

### OS

Ubuntu

### Description

The `distutils.log.Log` class was removed in https://github.com/pypa/setuptools/commit/74652cabdeaacadc76ccf126563bed8ee2ccf3ef. This causes popular packages downstream, such as `numpy`, to fail: see https://github.com/numpy/numpy/issues/22623

### Expected behavior

The module `distutils.log` module was not officially marked as deprecated even though https://github.com/pypa/setuptools/commit/74652cabdeaacadc76ccf126563bed8ee2ccf3ef added to the docstring that the module is `Retained for compatibility and should not be used.`. It would be great if the removed class could be reinstated and a deprecation pathway be provided.

### How to Reproduce

1. `pip install setuptools==65.6.0`
2. `from numpy.distutils import Log`

### Output

```
In [4]: from numpy.distutils import Log
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-4-f8e71815afcd> in <module>
----> 1 from numpy.distutils import Log

~/.virtualenvs/aiida_dev/lib/python3.9/site-packages/numpy/distutils/__init__.py in <module>
     22 # Must import local ccompiler ASAP in order to get
     23 # customized CCompiler.spawn effective.
---> 24 from . import ccompiler
     25 from . import unixccompiler
     26 

~/.virtualenvs/aiida_dev/lib/python3.9/site-packages/numpy/distutils/ccompiler.py in <module>
     18 from distutils.version import LooseVersion
     19 
---> 20 from numpy.distutils import log
     21 from numpy.distutils.exec_command import (
     22     filepath_from_subprocess_output, forward_bytes_to_stdout

~/.virtualenvs/aiida_dev/lib/python3.9/site-packages/numpy/distutils/log.py in <module>
      2 import sys
      3 from distutils.log import *  # noqa: F403
----> 4 from distutils.log import Log as old_Log
      5 from distutils.log import _global_log
      6 

ImportError: cannot import name 'Log' from 'distutils.log' (/home/sph/.virtualenvs/aiida_dev/lib/python3.9/site-packages/setuptools/_distutils/log.py)
```

**Comment by oscarbenjamin** [comment]
This actually breaks just importing `numpy.distutils` altogether:
```python
In [2]: import numpy.distutils
---------------------------------------------------------------------------
ImportError
...
~/38venv/lib/python3.8/site-packages/numpy/distutils/log.py in <module>
      2 import sys
      3 from distutils.log import *  # noqa: F403
----> 4 from distutils.log import Log as old_Log
      5 from distutils.log import _global_log
      6 

ImportError: cannot import name 'Log' from 'distutils.log' (~/38venv/lib/python3.8/site-packages/setuptools/_distutils/log.py)

```

**Comment by bentheiii** [comment]
This is a serious issue for people using older numpy (that can only install with distutils) and poetry (as poetry doesn't respect PEP-518 AFAICT). We have no way to install our dependencies except to manually install numpy with the `--no-build-isolation` flag.

**Comment by maxnoe** [comment]
Also running into this, numpy 1.23.5 is also affected.

**Comment by cliffwoolley** [comment]
`export SETUPTOOLS_USE_DISTUTILS=stdlib` appears to be another workaround, which allowed me then to build/install `scipy==1.4.1` on ARM (where there are no prebuilt binaries).

@bentheiii 's alternative above of `pip install --no-build-isolation scipy==1.4.1` after pinning back setuptools was the only other way I got to work so far.

**Comment by tulbureandreit** [comment]
Running into this for statsmodels==0.13.0 and numpy==1.22.0

**Comment by cliffwoolley** [comment]
For numpy, follow one of the two options I listed for scipy.  (Scipy hits it because of its dependence on numpy.)

**Comment by tulbureandreit** [comment]
> For numpy, follow one of the two options I listed for scipy. (Scipy hits it because of its dependence on numpy.)

@cliffwoolley I have a package which we use in Dev which is used with Poetry. Hence I cannot use your PIP-based fix. I found the problem being statsmodels and zict (as a prerequisite).

So I think trying to fix their dependencies might be worth it ?

**Comment by abravalheri** [comment]
Thank you all for reporting the problem, in https://github.com/pypa/distutils/pull/192 I am proposing a backfill for the appreciation of `pypa/distutils` maintainers. If accepted, this patch will find its way into setuptools.

Not that is still something that needs to be debated in `pypa/distutils`, since in https://github.com/pypa/setuptools/issues/2372 the numpy maintainers agreed with setuptools strategy of making `SETUPTOOLS_USE_DISTUTILS=local` the default behaviour.

Also note that the recommendation from the numpy team for everyone using `numpy.distutils` is the following:

>   `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
  of the deprecation of `distutils` itself. It will be removed for
  Python >= 3.12. For older Python versions it will remain present.
  It is recommended to use `setuptools < 60.0` for those Python versions.
  For more details, see: https://numpy.org/devdocs/reference/distutils_status_migration.html

**Comment by oscarbenjamin** [comment]
Thanks @abravalheri.

I just want to note that the suggestion from the numpy team to pin setuptools is not appropriate for all use cases. In SymPy's case `numpy.distutils` is used to build an extension on the user's machine so this is really a runtime dependency rather than something that can be worked around at build time (this is discussed at https://github.com/numpy/numpy/issues/22027). I don't think it would be appropriate for sympy releases to pin the version of setuptools in the *user's* installation.

I think it is however easy to fix this in SymPy's case by switching to setuptools instead of numpy.distutils because I don't think the additional features of numpy.distutils are needed there. The bug here though means that users will see broken functionality immediately if they update setuptools now (e.g. in any new venv).

I realise that both `distutils` and `numpy.distutils` are deprecated but if there is any purpose in maintaining them as deprecated then it should be that they at least maintain compatibility in basic use cases. Probably it would make sense for something in setuptools CI to test that a basic `numpy.distutils` extension still compiles.

**Comment by abravalheri** [comment]
Hi @oscarbenjamin thank you very much for the comment.

The `pypa/distutils` team is doing their best to support any deprecated usage as well as fixing all the existing bugs in the library. Please note that the intention here is not to keep the library bug-by-bug compatible but actually do some modernization and fixing problematic bits.

Unfortunately we are in the middle of a catch 22 here:

- In https://github.com/pypa/setuptools/issues/2372#issuecomment-687575343 the setuptools/distutils leading developer offered to the `numpy` to adopt the features from `numpy.distutils`. But due to the fact that the numpy team does not have the bandwidth to work on the port this option was considered unfeasible/impractical.

- Initially setuptools integration tests included numpy, however since numpy is pinning the setuptools version used, this integration test also became impractical and was removed.


If you (or anyone else in the community) is interested in keeping the compatibility between numpy and setuptools, I believe the best would be reaching out in the https://github.com/pypa/setuptools/issues/2372 thread and volunteering to carry out the port of the numpy-specific features/functionalities (e.g. fortran compiler) and checking if the setuptools leading developer would be interested even if the numpy team is not directly supporting the port.

**Comment by cliffwoolley** [comment]
> @tulbureandreit  I have a package which we use in Dev which is used with Poetry. Hence I cannot use your PIP-based fix.

One of the comments on the related numpy issue suggests that the env var approach does work with poetry.  I haven't tried it myself, but intuitively it does seem like that option should be independent of pip.
https://github.com/numpy/numpy/issues/22623#issuecomment-1321725976

**Comment by oscarbenjamin** [comment]
> * Initially setuptools integration tests included numpy, however since numpy is pinning the setuptools version used, this integration test also became impractical and was removed.

I'm not sure I understand this. SymPy's CI just does `pip install numpy` and then tries to run a `setup.py` to build an extension module. It would have though it would be straight-forward to have a CI job for setuptools that does the equivalent of that.

> If you (or anyone else in the community) is interested in keeping the compatibility between numpy and setuptools

I am not personally interested in doing this. Both distutils and numpy.distutils are deprecated so the expected downstream response as I understand it is just to stop using them. I find it strange though that backwards incompatible changes would be made if these are deprecated and basically shouldn't be used any more.

The problem right now is that it isn't clear what the expected alternatives for distutils/numpy.distutils are supposed to be. Note that the SymPy code in question is using numpy.distutils in the way that is still suggested in the NumPy documentation:
https://numpy.org/doc/stable/user/c-info.ufunc-tutorial.html
The issue I already referred to (https://github.com/numpy/numpy/issues/22027) discusses changing that and the discussion there found a solution that (probably) works for SymPy. That solution doesn't work for all projects though and I think that those docs are not updated just because it isn't clear what they should now be updated to say.

**Comment by cliffwoolley** [comment]
Another way out from this situation would have been pip constraints, but as far as I can tell, constraints don't seem to apply to the isolated build environment:

```
root@20ccdca7a737:/# echo 'setuptools<60' > constraints.txt
root@20ccdca7a737:/# pip install -c constraints.txt scipy==1.4.1 --verbose
Using pip 22.3.1 from /usr/local/lib/python3.8/dist-packages/pip (python 3.8)
Collecting scipy==1.4.1
  Downloading scipy-1.4.1.tar.gz (24.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 10.3 MB/s eta 0:00:00
  Running command pip subprocess to install build dependencies
  Ignoring numpy: markers 'python_version == "3.5" and platform_system != "AIX"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.6" and platform_system != "AIX"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.7" and platform_system != "AIX"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.5" and platform_system == "AIX"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.6" and platform_system == "AIX"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.7" and platform_system == "AIX"' don't match your environment
  Ignoring numpy: markers 'python_version >= "3.8" and platform_system == "AIX"' don't match your environment
  Collecting wheel
    Using cached wheel-0.38.4-py3-none-any.whl (36 kB)
  Collecting setuptools
    Using cached setuptools-65.6.0-py3-none-any.whl (1.2 MB)  <---------------
  Collecting Cython>=0.29.13
    Downloading Cython-0.29.32-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.manylinux_2_24_aarch64.whl (1.8 MB)
```

It looks like https://github.com/pypa/pip/issues/10669 asked for exactly this (for the same reason of distutils breakage), but that one was duped onto https://github.com/pypa/pip/issues/4582 which is still open.

**Comment by tulbureandreit** [comment]
> @tulbureandreit
> 
> > I have a package which we use in Dev which is used with Poetry. Hence I cannot use your PIP-based fix.
> 
> One of the comments on the related numpy issue suggests that the env var approach does work with poetry. I haven't tried it myself, but intuitively it does seem like that option should be independent of pip. [numpy/numpy#22623 (comment)](https://github.com/numpy/numpy/issues/22623#issuecomment-1321725976)

@cliffwoolley I cannot run it. We have dockerized the model and each time it does poetry install, it needs to install statsmodels, which statsmodels has no PIN for setuptools < 65.6.0, so it fails.

We pinned our own models constraints to be <65.6.0

Another Q would be, starting which version of numpy would we get rid of this problem? 1.23.1?

**Comment by jaraco** [comment]
I've cut a release 65.6.2 with the fix. Sorry it took so long to get a remedy out. That was mainly my fault. Huge thanks to abravalheri for multiple fixes and validation work.

**Comment by cliffwoolley** [comment]
For those diving right in to verify like I am, it seems 65.6.1 also has the relevant change; 65.6.2 that @jaraco mentioned was about half an hour later with relnote-only tweaks.  https://github.com/pypa/setuptools/compare/v65.6.1...v65.6.2 .  65.6.2 hasn't made it to PyPI yet as of this writing https://pypi.org/project/setuptools/#history , but presumably would be there soon.

**Comment by oscarbenjamin** [comment]
Thanks all.

**Comment by tulbureandreit** [comment]
@cliffwoolley I solved it with SETUPTOOLS_USE_DISTUTILS=stdlib poetry install. I heard maybe 65.6.2 fixed it ?

**Comment by haraldschilly** [comment]
I can confirm that setuptools version `65.6.3` fixes this, i.e. I got that numpy error when importing pyscf.

**Comment by eli-schwartz** [comment]
> * Initially setuptools integration tests included numpy, however since numpy is pinning the setuptools version used, this integration test also became impractical and was removed.

There should probably be a distinction between building *numpy* (with pinned setuptools) in CI, versus building a carefully crafted test case that *depends* on numpy and setuptools, and does `from numpy.distutils import ...`.

The latter is what really needs to be tested here in order to make sure that yet more projects using numpy.distutils are operational.
