### ISSUE TITLE
[FR] Fail on mixed pyproject.toml + setup.py configuration setups

### ISSUE THREAD

**Issue by pradyunsg** [pypa/setuptools#3853]
### What's the problem this feature will solve?

This is intended to reduce user confusion around the behaviour that setuptools has with pyproject.toml configuration.

### Describe the solution you'd like

Disallow mixing pyproject.toml configuration with setup.py/setup.cfg configuration. If any of the metadata that _can_ be declared in pyproject.toml + not-dynamic is declared in setup.py, error out.

### Alternative Solutions

Only removing the soft-rejection logic introduced in https://github.com/pypa/setuptools/pull/3215

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by abravalheri** [comment]
Hi @pradyunsg could you please specify what is the user confusion around `pyproject.toml`?

I believe that complementing the config with `setup.py` should be allowed (not everything for every package can be specified statically). Of course, the users should use `dynamic` if they want `setup.py` to provide the equivalents of the `[project]` table.

The suggested alternative approach should be fine. Right now there are some warnings when processing `pyproject.toml` that could be transformed in hard errors. I haven't done it yet because I can never tell when this kind of change generates strong push back from the community.

**Comment by Gabzygreen11** [comment]
> ### What's the problem this feature will solve?
> 
> This is intended to reduce user confusion around the behaviour that setuptools has with pyproject.toml configuration.
> 
> 
> ### Describe the solution you'd like
> 
> Disallow mixing pyproject.toml configuration with setup.py/setup.cfg configuration. If any of the metadata that _can_ be declared in pyproject.toml + not-dynamic is declared in setup.py, error out.
> 
> 
> ### Alternative Solutions
> 
> Only removing the soft-rejection logic introduced in https://github.com/pypa/setuptools/pull/3215
> 
> ### Additional context
> 
> _No response_
> 
> ### Code of Conduct
> 
> - [X] I agree to follow the PSF Code of Conduct

**Comment by abravalheri** [comment]
`_skip_bad_config` was removed in `v68.0.0`, so the "alternative solution" is in place and people should be required to specify `[project] dynamic` if they want to use `setup.py` to provide the equivalents of the `[project]` table.

I will close the issue for now. Please feel free to reopen if there any aspects left (or things are not working how I imagine they are).
