### ISSUE TITLE
[BUG] Optional deps cause problems when loading entrypoints in conda

### ISSUE THREAD

**Issue by Finesim97** [pypa/setuptools#3892]
### setuptools version

setuptools==67.6.1

### Python version

Python 3.10

### OS

Ubuntu

### Additional environment information

Only happens when using `pkg_resources` with conda (Could be caused by a packaging weirdness):

```sh 
mamba create -p setuptoolsbugconda python=3.10
conda activate setuptoolsbugconda
mamba install jupyter-rsession-proxy
# Now copy and paste the old and new code for testing
python
```

venv+pip works

```sh
python -m venv setuptoolsbug
source setuptoolsbug/bin/activate
pip install setuptools jupyter-rsession-proxy
# Now copy and paste the old and new code for testing
python
```

### Description

See https://github.com/jupyterhub/jupyter-server-proxy/issues/378

When loading the entrypoints, there seems to be some sort of issue with optional dependencies:

```
pkg_resources.DistributionNotFound: The 'webcolors>=1.11; extra == "format-nongpl"' distribution was not found and is required by jsonschema
```

With importlib.metadata everything appears to be working fine.

### Expected behavior

When using pip, the entry points load without issue. I am aware that `pkg_resources` is deprecated, therefore sry, if this is a wontfix.

### How to Reproduce

Setup the environments as shown above and then run both:

```
import pkg_resources

for entry_point in pkg_resources.iter_entry_points('jupyter_serverproxy_servers'):
    name = entry_point.name
    print(name)
    server_process_config = entry_point.load()()
    print(server_process_config)
```

```
from importlib.metadata import entry_points

for entry_point in entry_points().select(group='jupyter_serverproxy_servers'):
    name = entry_point.name
    print(name)
    server_process_config = entry_point.load()()
    print(server_process_config)
```

### Output

Working:

```console
rstudio
{'command': <function setup_rserver.<locals>._get_cmd at 0x7fdea57d15a0>, 'timeout': 15, 'environment': <function setup_rserver.<locals>._get_env at 0x7fdea57d0160>, 'rewrite_response': <function rewrite_auth at 0x7fdea5853d00>, 'launcher_entry': {'title': 'RStudio', 'icon_path': '/opt/conda/lib/python3.10/site-packages/jupyter_rsession_proxy/icons/rstudio.svg'}}
```

Crashing:

```console
DistributionNotFound                      Traceback (most recent call last)
Cell In[49], line 6
      4 name = entry_point.name
      5 print(name)
----> 6 server_process_config = entry_point.load()()
      7 print(server_process_config)

File /opt/conda/lib/python3.10/site-packages/pkg_resources/__init__.py:2516, in EntryPoint.load(self, require, *args, **kwargs)
   2509     warnings.warn(
   2510         "Parameters to load are deprecated.  Call .resolve and "
   2511         ".require separately.",
   2512         PkgResourcesDeprecationWarning,
   2513         stacklevel=2,
   2514     )
   2515 if require:
-> 2516     self.require(*args, **kwargs)
   2517 return self.resolve()

File /opt/conda/lib/python3.10/site-packages/pkg_resources/__init__.py:2539, in EntryPoint.require(self, env, installer)
   2533 # Get the requirements for this entry point with all its extras and
   2534 # then resolve them. We have to pass `extras` along when resolving so
   2535 # that the working set knows what extras we want. Otherwise, for
   2536 # dist-info distributions, the working set will assume that the
   2537 # requirements for that extra are purely optional and skip over them.
   2538 reqs = self.dist.requires(self.extras)
-> 2539 items = working_set.resolve(reqs, env, installer, extras=self.extras)
   2540 list(map(working_set.add, items))

File /opt/conda/lib/python3.10/site-packages/pkg_resources/__init__.py:827, in WorkingSet.resolve(self, requirements, env, installer, replace_conflicting, extras)
    824 if not req_extras.markers_pass(req, extras):
    825     continue
--> 827 dist = self._resolve_dist(
    828     req, best, replace_conflicting, env, installer, required_by, to_activate
    829 )
    831 # push the new requirements onto the stack
    832 new_requirements = dist.requires(req.extras)[::-1]

File /opt/conda/lib/python3.10/site-packages/pkg_resources/__init__.py:868, in WorkingSet._resolve_dist(self, req, best, replace_conflicting, env, installer, required_by, to_activate)
    866         if dist is None:
    867             requirers = required_by.get(req, None)
--> 868             raise DistributionNotFound(req, requirers)
    869     to_activate.append(dist)
    870 if dist not in req:
    871     # Oops, the "best" so far conflicts with a dependency

DistributionNotFound: The 'webcolors>=1.11; extra == "format-nongpl"' distribution was not found and is required by jsonschema
```

**Comment by abravalheri** [comment]
Hi @Finesim97, after some investigation it seems to me that `pkg_resources` is working as expected.

If we follow the dependency chain (specified via the [`Requires-Dist` field in the `METADATA` file of each distribution](https://packaging.python.org/en/latest/specifications/core-metadata/#requires-dist-multiple-use)), we can find the following relationships:

```
jupyter_rsession_proxy-2.1.0.dist-info/METADATA
  Requires-Dist: jupyter-server-proxy (>=3.2.0)

jupyter_server_proxy-4.0.0.dist-info/METADATA
  Requires-Dist: jupyter-server>=1.0

jupyter_server-2.6.0.dist-info/METADATA
  Requires-Dist: jupyter-events>=0.6.0

jupyter_events-0.6.3.dist-info/METADATA
  Requires-Dist: jsonschema[format-nongpl]>=3.2.0

jsonschema-4.17.3.dist-info/METADATA
  Requires-Dist: webcolors>=1.11; extra == 'format-nongpl'
```

This means that the `jsonschema` is required to be installed with the `format-nogpl` extra which means that `webcolors` should be installed.

However, when you install the project with `conda/mamba`, `webcolors` is not installed[^1] 

This is probably a "specification bug" in one of the elements in the dependency chain as they are published in conda-forge. Likely to caused when translating Python requirements to the conda recipe file (conda does not have an `extras` counterpart, so it is very difficult to have a 1 to 1 translation). Maybe one of the maintainers of those packages is interested in taking the investigation further.

Note that according to the docs [`pkg_resources.EntryPoints.load`](https://setuptools.pypa.io/en/latest/pkg_resources.html#entrypoint-objects) will call `pkg_resources.EntryPoints.require`, which in turn will enforce that all dependencies (including necessary extras) are installed. If you don't want to enforce that I suppose you could try `pkg_resources.EntryPoints.resolve` instead.

I am not sure what is the behaviour of `importlib-metadata`, probably it is more similar to the `resolve` method for performance reasons and will raise an exception just in the case of import errors...

I will close this issue for now since I think there is no action point on the setuptools side (plus `pkg_resources` is deprecated, so we are trying to keep changes limited).

[^1]: If you install the project with `pip`, `webcolors` will be installed, which explains why it works.

**Comment by Finesim97** [comment]
Thank you for the detailed investigation and explanation! I totally agree with you that this not a problem in setuptools.
