### ISSUE TITLE
The generated exe such as easy_install.exe and pip.exe should use relative path for python

### ISSUE THREAD

**Issue by bb-migration** [pypa/setuptools#393]
Originally reported by: **lygstate (Bitbucket: [lygstate](http://bitbucket.org/lygstate), GitHub: [lygstate](http://github.com/lygstate))**

---

At the current time, the setuptools always using absolute 
path and that cause the Python can not be portable.

---
- Bitbucket: https://bitbucket.org/pypa/setuptools/issue/393

**Comment by pythonicca** [comment]
It looks like there's a fallback in launcher.c (around line 199) that enables portability but it's never triggered if an absolute path is provided (which seems to be always - at least I've never seen otherwise). 

If the Python install directory is relocated any executable in Scripts (derived from cli.exe/cli-32.exe or cli-64.exe) fails with (the not very helpful) "failed to create process" Windows error.

Possible Workaround(s):

**If you have files ending in '-script.py' in your Scripts folder:**
Remove the first line from all *-script.py that starts with a shebang.
Steps:
Open a *-script.py (easy_install-script.py, pip-script.py, etc..) in a text editor
On the first line you might see something like this:
`#!C:\<your python install folder>\python.exe`
Remove the line and save the file. 

**If you only have executables in your Scripts folder:**
Edit the executable and replace the existing shebang path with a relative path.
Steps:
Open the executable in a hex or text editor (Notepad++ works fine) . 
Search for  `__main__.py`
The first non-empty line above the first occurrence will end with a shebang path. Replace it with:
`#!%cd%\..\python.exe`
Save the file.

Either of these will force the launcher to reach the fallback code and start correctly. These files will need to be edited again if overwritten or updated.

Additional thoughts:
There may have been a very good reason why the absolute path takes precedence. Maybe someone else can provide an answer. A possible solution would be to add a check in launcher.c so that it looks for the presence of a file in the Scripts directory (say `portable.txt`) and if found immediately jump to the fallback code.

**Comment by jaraco** [comment]
The script wrappers in setuptools/easy_install are soft-deprecated in favor of the script wrappers that pip uses (via distlib). If you install packages with pip, are the script executables it generates able to follow a relocated python? If so, I'd recommend using that as the workaround. If not, this ticket should be filed with pip as that's the preferred mechanism.

I don't think it's worth investing the effort on this issue here; if anything, I'd like to see the effort focused on getting easy_install to use distlib for its script executables.

One should also consider if [pylauncher](https://www.python.org/dev/peps/pep-0397/) would have any benefit for resolving the relevant Python version.
