### ISSUE TITLE
Removal of escaping in shebang in pip install causes "failed to create process" on Windows

### ISSUE THREAD

**Issue by ghost** [pypa/setuptools#398]
Originally reported by: **joeyespo (Bitbucket: [joeyespo](http://bitbucket.org/joeyespo), GitHub: [joeyespo](http://github.com/joeyespo))**

---

I have Python installed in `C:\Program Files (x86)\Python` (for legacy reasons--it's kind of late to move it now), and any `console_script` I install from PyPI breaks now. Running the script causes a "failed to create process" error.

I noticed that older console_scripts were working, and turns out it's because they were quoted. Ex: `#!"C:\Program Files (x86)\Python\python.exe"`

Manually adding quotes around the newly installed `projectname-script.py` fixes it.

It looks like the culprit may have been the fix in #188. From that issue:

> If it is possible to detect being on a posix platform (probably not that easy?), we could just skip the escaping, as it is never beneficial. If this is not possible, maybe just skip the escaping all together? The benefit seems very platform specific.

Turns out skipping escaping all together just threw the problem back over the fence to Windows. Perhaps it'd be best to detect the platform? Escaping is indeed a platform-specific thing.

---
- Bitbucket: https://bitbucket.org/pypa/setuptools/issue/398

**Comment by tomduck** [comment]
See [`pip` Issue #2783][1] for a discussion of the same problem, including a workaround that can be used in `setup.py`.

[1]: https://github.com/pypa/pip/issues/2783

**Comment by fkrull** [comment]
I did some digging into this issue; it's either a setuptools or distutils problem. I'll stick to cpplint, but any package using setuptools and entry points should show this behaviour. Things I have observed:

1) `pip install cpplint` installs the wheel and works fine.
2) `pip install --no-binary cpplint cpplint` **doesn't** quote the shebang properly. It installs from sdist by running `setup.py install --single-version-externally-managed` locally.
3) `setup.py install` from the source installs fine.
4) `setup.py install --single-version-externally-managed` from the source **doesn't** quote the shebang line properly.

I don't know what the egg installation code does different, but in [setuptools/command/install_scripts.py line 33](https://github.com/pypa/setuptools/blob/master/setuptools/command/install_scripts.py#L33) `exec_param` is retrieved from the build_scripts command which in turn gets it from the build command (`distutils/command/build_scripts.py` line 38) which, if unspecified, sets it to this (`distutils/command/build.py line 120):

    self.executable = os.path.normpath(sys.executable)

Then, `exec_param` -- which is just an unquoted path, possibly containing spaces -- gets passed to `CommandSpec.from_param` ([setuptools/command/install_scripts.py line 42](https://github.com/pypa/setuptools/blob/master/setuptools/command/install_scripts.py#L42)) which parses it as a command line by splitting it along spaces ([setuptools/command/easy_install.py line 1954](https://github.com/pypa/setuptools/blob/master/setuptools/command/easy_install.py#L1954)). As a consequence, the special quoting code gets bypassed.

Wrapping `exec_param` in a one-element list solved the problem (not quite a one-line fix because it shouldn't be wrapped if it's `None`). I can roll a PR, but I don't know the setuptools codebase well enough to determine if this is the best place to fix this.

**Comment by anthrotype** [comment]
You're right, it's a setuptools issue, not pip or distlib.

When installing from a binary wheel (or when installing from sdist package), pip uses distlib to create the console/gui scripts, and distlib does take care of "enquoting" the executable in the shebang:

https://github.com/pypa/pip/blob/master/pip/_vendor/distlib/scripts.py#L161-L164
https://github.com/pypa/pip/blob/master/pip/_vendor/distlib/scripts.py#L66-L79

I think it's in `easy_install.ScriptWriter.get_args` where the executable enquoting should go.

**Comment by anthrotype** [comment]
I confirm what @fkrull just said. 

The executable string from distutils `build_scripts` command is being split using shlex inside easy_install's [CommandSpec.from_string](https://github.com/pypa/setuptools/blob/master/setuptools/command/easy_install.py#L1966).

Passing `[exec_param]` as a one-element list (when not None) solves the issue, as `CommandSpec._render` method will then concatenate the strings with `subprocess.list2cmdline`, which in turn correctly escapes spaces with double quotes following MS rules.

Thanks for finding this out! 👍
