### ISSUE TITLE
[BUG] Invalid version read from long description readme

### ISSUE THREAD

**Issue by qw8z5fUB** [pypa/setuptools#4010]
### setuptools version

63.3.0

### Python version

3.8.10

### OS

Ubuntu Focal 20.04.6

### Description

I have a package with this in the setup.cfg file:
`long_description = file: README.md`
and this in the README.md file:
`Version: x.x.x` (I copy paste the tool's usage into the readme, and the usage includes the version, but I set to x.x.x in the readme instead of updating the readme with each version).

I'm using setuptools_scm to get the actual version.

When I run `python -m build`, I get the error:
setuptools.extern.packaging.version.InvalidVersion: Invalid version: 'x.x.x'

If I remove the line `long_description = file: README.md` from setup.cfg, then the build succeeds and the correct version is picked up.

Trying to understand the issue, it looks like [`_version_from_file`](https://github.com/pypa/setuptools/blob/ecbef02a5f141d5e24d6bacd7234fea2cf54df22/pkg_resources/__init__.py#L2614C24-L2614C24) is looking for any line in PKG-INFO which starts with "version:", and in my case that line from my readme is being picked up. 

### Expected behavior

Using `long_description = file: README.md` should not break the package build.

### How to Reproduce

Put in setup.cfg:
`long_description = file: README.md`
Put in README.md file:
`Version: x.x.x` 
Try to build:
`python -m build`

Apologies I don't have more time to document the bug with a complete reproducible example, I'm hoping the bug report is useful as-is.

### Output

```console
setuptools.extern.packaging.version.InvalidVersion: Invalid version: 'x.x.x'
```

**Comment by abravalheri** [comment]
Hi @qw8z5fUB I tried to see if the bug is already solved in the latest version of setuptools[^1]. I have used to following script based on your reproducer:

```bash
> docker run --rm -it python:3.8-bullseye /bin/bash
mkdir /tmp/myproj
cd /tmp/myproj
echo "Version: x.x.x" > README.md
touch mypkg.py
cat <<EOF > setup.cfg
[metadata]
long_description = file: README.md
EOF
cat <<EOF > pyproject.toml
[build-system]
requires = ["setuptools==68.0.0"]
build-backend = "setuptools.build_meta"
EOF
python -m venv .venv
.venv/bin/python -m pip install -U 'pip==23.2' 
.venv/bin/python -m pip install -U 'build==0.10.0'
.venv/bin/python -m build -C--verbose
# ...
# Successfully built mypkg-0.0.0.tar.gz and mypkg-0.0.0-py3-none-any.whl

unzip -c dist/mypkg-0.0.0-py3-none-any.whl mypkg-0.0.0.dist-info/METADATA
# Archive:  dist/mypkg-0.0.0-py3-none-any.whl
#   inflating: mypkg-0.0.0.dist-info/METADATA
# Metadata-Version: 2.1
# Name: mypkg
# Version: 0.0.0
# 
# Version: x.x.x
```

This seems to run fine.

Could you please provide a different [reproducer](https://stackoverflow.com/help/minimal-reproducible-example) based on the script above if you think this is not representative of the error you are seeing?

> Apologies I don't have more time to document the bug with a complete reproducible example, I'm hoping the bug report is useful as-is.

I recommend always creating a complete minimal [reproducer](https://stackoverflow.com/help/minimal-reproducible-example) (e.g. like the script I included above), that is very helpful to avoid back and forth and makes the communication more effective.

[^1]: According to the [release process of setuptools](https://setuptools.pypa.io/en/latest/development/releases.html), all bugfixes are added on top of the latest version. Unfortunately we don't have the resources of maintaining patches for LTS versions. So my recommendation is always to first see if the latest version can solve the problem.

**Comment by qw8z5fUB** [comment]
Hi @abravalheri , thanks for the prompt response, and for the the initial reproducer script. I've extended it to make it fail - it looks like it's some interaction with setuptools_scm which makes it fail:

```bash
mkdir /tmp/myproj
cd /tmp/myproj
echo "Version: x.x.x" > README.md
touch mypkg.py
cat <<EOF > setup.cfg
[metadata]
long_description = file: README.md
EOF
cat <<EOF > pyproject.toml
[build-system]
requires = ["setuptools==68.0.0", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"
[tool.setuptools_scm]
write_to = "_version.py"
EOF
git init
python -m venv .venv
.venv/bin/python -m pip install -U 'pip==23.2' 
.venv/bin/python -m pip install -U 'build==0.10.0'
.venv/bin/python -m build -C--verbose
# ...
# setuptools.extern.packaging.version.InvalidVersion: Invalid version: 'x.x.x'
```

Does this mean there's a setuptools_scm bug to report? I'm not clear how either of these things work, so not clear where the bug is likely to reside.

**Comment by abravalheri** [comment]
I am away from the computer right now (might have a look tomorrow morning).

Have you tried to do a `git tag v42` before running build, for example? Or fetch the tags for the existing repo. I think `setuptools-scm` needs that.

**Comment by abravalheri** [comment]
Thanks @qw8z5fUB, I suspect that the issue is caused by the way `setuptools-scm` attempts to parse the `PKG-INFO` file (the [core metadata](https://packaging.python.org/en/latest/specifications/core-metadata/) file for sdists) in https://github.com/pypa/setuptools_scm/blob/v7.1.0/src/setuptools_scm/utils.py#L144

The `PKG-INFO` file is a bit cumbersome to read (it is an "email message" format), and it happens that `Version: x.x.x` resembles the same email header that is used to store the message information. Because `setuptools-scm` seems to implement a simplified parsing that is not able to detect when the email headers stop (and when the body of the message starts), it ends up overwriting the correct version header with `Version: x.x.x`.

Just to validate this theory I hacked the `setuptools-scm` implementation in the following way:

```bash
> docker run --rm -it python:3.8-bullseye /bin/bash
mkdir /tmp/myproj
cd /tmp/myproj
echo "Version: x.x.x" > README.md
touch mypkg.py
cat <<EOF > setup.cfg
[metadata]
long_description = file: README.md
EOF
cat <<EOF > pyproject.toml
[build-system]
requires = ["setuptools==68.0.0", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"
[tool.setuptools_scm]
write_to = "_version.py"
EOF

# Ensure everything is set for setuptools-scm
git config --global init.defaultBranch main
git config --global user.email "you@example.com"
git config --global user.name "Your Name"
git init .
git add .
git commit -m "Initial commit"
git version v42

python -m venv .venv
.venv/bin/python -m pip install -U 'pip==23.2' 
.venv/bin/python -m pip install -U 'build==0.10.0' 'setuptools==68.0.0' 'setuptools-scm==7.1.0' 'wheel==0.41.1'

sed -i 's/for x in content.splitlines()/for x in reversed(content.splitlines())/g' .venv/lib/python3.8/site-packages/setuptools_scm/utils.py

.venv/bin/python -m build -C--verbose --no-isolation
# ...
# Successfully built mypkg-0.1.dev1+g2f4dddc.tar.gz and mypkg-0.1.dev1+g2f4dddc-py3-none-any.whl
```

After the hack it seems to be working...
(Please note that this hack is just a proof-of-concept and not production ready, I just reversed the order that the lines are analysed so the "wrong line" is replaced by the "right line").

**Comment by abravalheri** [comment]
Probably they are going to be better equipped to handle the problem in `setuptools-scm`.
But please let us know if we need to change something from setuptools perspective.
