### ISSUE TITLE
[BUG] Regression does not allow install_requires to be set in finalize_distribution_options hook

### ISSUE THREAD

**Issue by thatch** [pypa/setuptools#4054]
### setuptools version

setuptools==68.2.2

### Python version

CPython 3.11.3

### OS

Linux (and Mac, does not seem OS-specific)

### Description

Basically, the `setupmeta` project uses a `finalize_distribution_options` hook to set `install_requires`, and this stopped working.  I've bisected to 3c9d6ac96bb76670adc48535816fa3331b027c80 in setuptools.  This commit does not back out trivially on current main, and the 3 releases afterward are all broken in the same way (68.2.0, 68.2.1, and 68.2.2)

Is this a problem with the way we're using `finalize_distribution_options` or an untested code path in setuptools that should work?  I'm not sure.

### Expected behavior

`install_requires` gets set, and that makes it into the dist-info metadata (used by wheel)

### How to Reproduce

Repro steps are also in https://github.com/thatch/debug-setupmeta

```sh
git checkout https://github.com/thatch/debug-setupmeta
cd debug-setupmeta
python -m venv .venv
source .venv/bin/activate
pip install -U pip wheel setupmeta
pip install -e /path/to/setuptools
python setup.py dist_info
```

Basically, in this checkout just run `python setup.py dist_info` and see whether the requirements are missing

### Output

with a broken version

```
$ python setup.py dist_info
/home/tim/code/setuptools/setuptools/__init__.py:80: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
!!

        ********************************************************************************
        Requirements should be satisfied by a PEP 517 installer.
        If you are using pip, you can try `pip install --use-pep517`.
        ********************************************************************************

!!
  dist.fetch_build_eggs(dist.setup_requires)
running dist_info
creating foo.egg-info
writing foo.egg-info/PKG-INFO
writing dependency_links to foo.egg-info/dependency_links.txt
writing top-level names to foo.egg-info/top_level.txt
writing manifest file 'foo.egg-info/SOURCES.txt'
reading manifest file 'foo.egg-info/SOURCES.txt'
writing manifest file 'foo.egg-info/SOURCES.txt'
creating '/home/tim/code/debug-setupmeta/foo-0.0.0.dist-info'
$ grep '^Requires' foo-0.0.0.dist-info/METADATA
<nothing>
```

with a working version, note "requires.txt" and Dist-Requires

```
$ python setup.py dist_info
/home/tim/code/debug-setupmeta/.venv/lib/python3.11/site-packages/setuptools/__init__.py:84: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
!!

        ********************************************************************************
        Requirements should be satisfied by a PEP 517 installer.
        If you are using pip, you can try `pip install --use-pep517`.
        ********************************************************************************

!!
  dist.fetch_build_eggs(dist.setup_requires)
running dist_info
creating foo.egg-info
writing foo.egg-info/PKG-INFO
writing dependency_links to foo.egg-info/dependency_links.txt
writing requirements to foo.egg-info/requires.txt
writing top-level names to foo.egg-info/top_level.txt
writing manifest file 'foo.egg-info/SOURCES.txt'
reading manifest file 'foo.egg-info/SOURCES.txt'
writing manifest file 'foo.egg-info/SOURCES.txt'
creating '/home/tim/code/debug-setupmeta/foo-0.0.0.dist-info'
$ grep '^Requires' foo-0.0.0.dist-info/METADATA
Requires-Dist: thx
```

**Comment by abravalheri** [comment]
Hi @thatch, thank you very much for the report.

> I've bisected to https://github.com/pypa/setuptools/commit/3c9d6ac96bb76670adc48535816fa3331b027c80 in setuptools.

🤔 this commit was reversed shortly after (11edfe600)... so I am not sure it is the one responsible for the problem.

I tried your reproducer with both 'setuptools==68.2.2' directly from PyPI and from the git tag on Github and things seem to be fine:

```bash
> docker run --rm -it python:3.11-bullseye /bin/bash

cd /tmp
python -m venv .venv
source .venv/bin/activate
pip install -U pip wheel 'setuptools==68.2.2' setupmeta
git clone https://github.com/thatch/debug-setupmeta
cd debug-setupmeta
python setup.py dist_info
grep '^Requires' foo-0.0.0.dist-info/METADATA
# Requires-Dist: thx

pip install -U 'setuptools @ git+https://github.com/pypa/setuptools.git@v68.2.2'
rm -rf foo-0.0.0.dist-info
python setup.py dist_info
grep '^Requires' foo-0.0.0.dist-info/METADATA
# Requires-Dist: thx
```

You can see that in both cases `Requires-Dist: thx` shows up in the metadata file.

**Comment by thatch** [comment]
It looks like @zsimic added a workaround in setupmeta 3.5.2, see commit https://github.com/codrsquad/setupmeta/commit/4a72c468c5b7619405ec3e32af5980a4ce0776a4

The `install_requires` went from being settable on the dist, to also needing to be set on dist.metadata, it seems.

**Comment by abravalheri** [comment]
Hi @thatch, if `setupmeta` needs to make assumptions on which fields are available in the `metadata` object, it is very likely it is incompatible with any change in setuptools that introduces new fields in the metadata object, right?

> The install_requires went from being settable on the dist, to also needing to be set on dist.metadata, it seems.

The metadata object now uses this field to produce a "more standards-compliant" [core metadata](https://packaging.python.org/en/latest/specifications/core-metadata/#provides-dist-multiple-use) file. The intention of the 68.2 release was to bring the metadata implementation more up-to-speed with the standard.

**Comment by thatch** [comment]
ok, I think we can close this out then; setupmeta 3.5.2 either contains a fix or a workaround, depending on how you look at it.  Thanks for taking a look.

**Comment by zsimic** [comment]
Yes, currently if a `setuptools.finalize_distribution_options` hook does not set both `dist.install_requires` and `dist.metadata.install_requires`, then the produced package will not have `Requires-Dist:` info in all places.

Different `setup.py` commands will produce different outcomes, for example:
- `setup.py egg_info` seems to use `dist.install_requires`, and populates `*.egg-info/PKG-INFO` -> `Requires-Dist:` accordingly
- `setup.py dist_info` seems to use `dist.metadata.install_requires`, and populates `*.dist-info/METADATA` -> `Requires-Dist:` accordingly

**Comment by abravalheri** [comment]
> - setup.py egg_info seems to use dist.install_requires, and populates *.egg-info/PKG-INFO -> Requires-Dist: accordingly
> - setup.py dist_info seems to use dist.metadata.install_requires, and populates *.dist-info/METADATA -> Requires-Dist: accordingly

Interesting enough, the change in 68.2 was introduced in such a way that `dist.metadata` is used to populate `Requires-Dist` in the `PKG-INFO` file[^1]. That is the reason why we now have a "better PKG-INFO" which is more aligned with the last iteration of the core metadata spec.

On the other hand `dist_info` uses `wheel.bdist_wheel` to [convert an `*.egg-info` directory into `*.dist-info`](https://github.com/pypa/setuptools/blob/v68.2.2/setuptools/command/dist_info.py#L116). The way it is implemented  in the `wheel` package, this conversion ignores the `Requires-Dist` metadata present in the `PKG-INFO` and regenerates the field from the [old `requires.txt` file](https://github.com/pypa/wheel/blob/0.41.2/src/wheel/metadata.py#L150), which is not standard[^2] (but we haven't stopped generating because `wheel` depends on it).

Initially I tried to be clever and avoid having 2 sources for the same information, but that broke other 3rd party plugins, so I reverted to using the [`_finalize_requires`](https://github.com/pypa/setuptools/blob/v68.2.2/setuptools/dist.py#L382) for ensuring `dist.metadata.install_requires/extras_require` is sync-ed to `dist.install_requires/extras_require`.

The `_finalize_requires` method is automatically called at the end of the `setuptools.dist.Distribution.__init__` and also after `setuptools.dist.Distribution.parse_config_files`, in such a way that even if `install_requires` is set in `finalize_distribution_options`, I would expect that the synchronization is successful... So that is why I was a bit puzzled by this issue.

Note that calling `_finalize_requires` was always necessary for some form of synchronisation of requirements between `dist` and `dist.metadata` even before 68.2 (notably this method was and still is responsible for post-processing of requirements, which includes validation and generating the list of extras that will populate the `Provides-extra` core metadata field).

[^1]: The `egg_info` command calls `setuptools.command.egg_info.write_pkg_info` to create the `PKG-INFO` file. In turn `egg_info.write_pkg_info` delegates to `metadata.write_pkg_info`, which eventually calls [`_core_metadata.write_pkg_file`](https://github.com/pypa/setuptools/blob/v68.2.2/setuptools/_core_metadata.py#L144) with the `dist.metadata` object.

[^2]: The `requires.txt` file is [generated from `dist.install_requires` and `dist.extras_require`](https://github.com/pypa/setuptools/blob/v68.2.2/setuptools/command/_requirestxt.py#L112).
