### ISSUE TITLE
[Docs] I’m truly sorry if this is not protocol, I have out moronized myself and can’t figure out even to get this working in my spaces 

### ISSUE THREAD

**Issue by ryanoZphoto** [pypa/setuptools#4219]
### Summary

I’m pretty dumb when it comes to coding I’m a little decent at understanding and structured if anybody has it in her heart to feeling of sorrow for me to try to help me get this going I’d appreciate it

### OS / Environment

Apple iPad 

### Additional Information

It would be cool to have some thing for morons like myself that is more "one button " play

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by abravalheri** [comment]
No complete description of the problem. Assuming it is a spam.

**Comment by ryanoZphoto** [comment]
> No complete description of the problem. Assuming it is a spam.

I have no clue how to get the program that is my problem, not spam

**Comment by abravalheri** [comment]
Hi @ryanoZphoto I am afraid we need more information than that to understand what is happening.
The way this issue is currently written we cannot simply guess what the problem is about.

Please also note that this issue tracker is exclusive to the `setuptools` project, if you have problems with other pieces of software, this is not the best place to bring it up.

If you haven't yet read through the [Quickstart guide](https://setuptools.pypa.io/en/latest/userguide/quickstart.html), I recommend to do so.
In the very first paragraphs there is a description of how to install/use `setuptools`.
If you are not familiar with `pip` (mentioned in the Quickstart guide), I also recommend having a look on https://pip.pypa.io/en/stable/ and https://packaging.python.org/en/latest/overview/.

After that, if you still have a problem please open a new issue in https://github.com/pypa/setuptools/issues/new/choose and add a more specific description of what you are trying to achieve. If possible add a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the steps that you are currently using and why the steps you are using don't work for achieving your goals.
