### ISSUE TITLE
[BUG] importing `pkg_resources` makes `importlib.metadata.version()` believe that `wheel` is installed

### ISSUE THREAD

**Issue by sbidoul** [pypa/setuptools#4516]
### setuptools version

setuptools>=71.0.1

### Python version

3.12

### OS

linux

### Description

With setuptools>=71, after importing `pkg_resources`, `importlib.metadata.version("wheel")` returns '0.43.0' whereas the `wheel` package is not installed.

### Expected behavior

Importing pkg_resources should not influence `importlib.metadata.version`.
This was ok until 71.0.0

### How to Reproduce

repro.py

```
from importlib.metadata import version, PackageNotFoundError

try:
    wheel_version = version("wheel")
except PackageNotFoundError:
    pass
else:
    assert False, f"found wheel {wheel_version}"

import pkg_resources

try:
    wheel_version = version("wheel")
except PackageNotFoundError:
    pass
else:
    assert False, f"found wheel {wheel_version} after importing pkg_resources"
```

repro.sh

```
#!/bin/bash
set -eaux

SETUPTOOLS_VERSION=$1

VENV_DIR=$(mktemp -d)
python3 -m venv $VENV_DIR
$VENV_DIR/bin/python -m pip install "setuptools$SETUPTOOLS_VERSION"
$VENV_DIR/bin/python repro.py
```

`repro.sh "==71.0.0"` works
`repro.sh ">=71.0.1"` fails

### Output

...

**Comment by sbidoul** [comment]
Perhaps related, it seems `pkg_resources.working_set` now includes all setuptools vendored depencies. Is that an intended change?

**Comment by jaraco** [comment]
Setuptools 71 introduced a new perspective on vendored dependencies. Instead of hosting the vendored dependencies in a private `.extern` namespace, it now exposes its dependencies naturally on `sys.path`. It does this for several reasons:

- By exposing the dependencies naturally, they do not need to be re-written to reference each other.
- Setuptools can import the dependencies naturally instead of in the private namespace.
- Setuptools can prefer dependencies installed in the environment, giving the user/integrator more control over what versions are available.
- This natural approach simplifies the implementation and brings it a lot closer to a world with properly-declared dependencies without any vendoring.
- Setuptools can now present its vendored dependencies as package metadata (`setuptools[core]` extra).

What this means is that as soon as `pkg_resources` is imported, all of the packages found in `setuptools/_vendor` are now available on `sys.path`, including wheel.

All of that is a long-winded way of saying, yes, it's an intended change, and wheel is in fact installed. In a sense, it has to be installed, because setuptools depends on it. In a future world where the dependencies are declared properly, installing setuptools would install wheel (along with its other dependencies) and uninstalling wheel would invalidate the setuptools installation, and setuptools 71 simulates that world.



> Importing pkg_resources should not influence `importlib.metadata.version`.

Agreed. Unfortunately, due to [bootstrapping issues with build backends](https://github.com/pypa/packaging-problems/issues/342), setuptools cannot currently declare its dependencies properly without breaking pure from source builds, so what you see is a compromise.

The best way to align with the future vision of Setuptools and to achieve the stated expectation would be to explicitly install the dependencies (e.g. `pip install setuptools[core]`; just not in `build-system.requires`). If you did that, then `wheel` would be installed unconditional on the import of `pkg_resources`.

Does that help?

**Comment by sbidoul** [comment]
I see, thanks for the detailed explanation.

Time to hunt down the last places that import `pkg_ressources`, I guess :)

So far I got hit by this only in the pip-deepfreeze test suite which exercises legacy code paths for places where importlib.metadata is not available, but these won't get setuptools 71 anyway so everything should be alright.
