### ISSUE TITLE
install_requires installs dependencies after package specifying them

### ISSUE THREAD

**Issue by ghost** [pypa/setuptools#457]
Originally reported by: **andi0661 (Bitbucket: [andi0661](http://bitbucket.org/andi0661), GitHub: Unknown)**

---

When using "install_requires", the specified dependent packages are installed after the package that specifies them is installed. This makes it impossible to use the dependent packages in the setup.py of the depending package.

Use case: I maintain the PyWBEM package, which has a post-installation step in which the package is imported to invoke a function to build something. That depends on one of the dependent packages being already installed. The current behavior makes it impossible to have such a post-processing step - i either need to restructure the package so that the post-processing step no longer requires the dependent package, or find some other mechanism on how to do this. (advice is welcome!)

I suggest that the order is turned around: First install the dependencies, and then the depending package. Unless there is a real good reason to do it the other way around, this seems like a logical order to me, anyway.

This is with setuptools v17.0, which is the latest setuptools I get with virtualenv for python 2.6 on RHEL 6.7.

---
- Bitbucket: https://bitbucket.org/pypa/setuptools/issue/457

**Comment by pganssle** [comment]
I think at this point we should probably leave the installation logic as it is and stick with PEP 518.

@jaraco Do you still want this feature, or should we leave it to pip and PEP 518?

**Comment by bignose-debian** [comment]
> I think at this point we should probably leave the installation logic as it is and stick with PEP 518.

What's the rationale for this? Setuptools still has the described bug, as best I can determine.

**Comment by jaraco** [comment]
Thanks for pinging the bug. I'd lost track of it.

> What's the rationale for this? Setuptools still has the described bug, as best I can determine.

Paul is right. Setuptools now strategically aims not to be an install tool and to instead be a build backend. That means that the primary focus of Setuptools is to support the PEP 518 mechanism for supplying dependencies necessary to enact the build. That functionality is implemented and working as intended.



> Setuptools still has the described bug.

It's true - as described, Setuptools will not install `install_requires` when building a package. That's because those are run-time dependencies and not build-time dependencies. Even the OP acknowledged that expectation was naïve.

So I believe the reported issue to be obviated by the PEP 518 design. I'd say that _packagers should not expect their package's run-time dependencies to be installed at build time_ and package their project accordingly.

If PEP 518 doesn't solve the reported issue, I'd recommend to open a new issue describing how PEP 518 falls short (either in this project if setuptools-specific or in /pypa/packaging-problems if generally applicable).
