### ISSUE TITLE
[BUG] Regression: Vendored `jaraco.text` cannot be loaded when using Bazel

### ISSUE THREAD

**Issue by janhicken** [pypa/setuptools#4605]
### setuptools version

setuptools>=71.0.0

### Python version

Python 3.10

### OS

Arch Linux

### Description

After setuptools' dependencies [have been re-vendored](https://github.com/pypa/setuptools/commit/00384a5f4fd22c653172b99feefe13b0009eb870), the issue #3072 surfaced again. 

The file `Lorem ipsum.txt` from `jaraco.text` is loaded again [here](https://github.com/pypa/setuptools/blob/v71.0.0/setuptools/_vendor/jaraco/text/__init__.py#L230), which used to be removed in [this fix](https://github.com/pypa/setuptools/commit/cd12bff9f5df4843f521d8dd0ad841dfff69f07c).

This is a problem when using `setuptools` with Bazel, because it does not support paths with spaces.

### Expected behavior

See #3072.

### How to Reproduce

See #3072.

### Output

See #3072.

**Comment by abravalheri** [comment]
Hi @janhicken have you tried to discuss this problem with the bazel maintainers? As noted in #3072 this is not really a bug in the setuptools code base but rather in bazel and/or rules Python.

I did [open an issue](https://github.com/bazelbuild/rules_python/issues/617) a while ago in `rules_python` given a heads up that the patch introduced in https://github.com/pypa/setuptools/pull/3077 was not bullet proof and that the problem could re-surface. The issue was closed in favor https://github.com/bazelbuild/bazel/issues/4327.

I do believe that the best place to solve this problem is in bazel, and it is not really a bug in the setuptools implementation.

/cc @jaraco

**Comment by janhicken** [comment]
I agree with you, maybe #3077 should not have been implemented in the first place, because upgrading to `setuptools>=71.0.0` now feels like a regression.

Also, my issue is probably a duplicate of #4487 where this was already discussed in more detail. @jaraco already mentioned is intention to _not_ fix the issue here.

As Bazel 7.0 introduced experimental support for dealing with spaces in paths (`--experimental_inprocess_symlink_creation`), this missing piece seems to be https://github.com/bazelbuild/rules_python not supporting that. 

I'm going to open an issue there and close this one.
