### ISSUE TITLE
Some outdated packages still execute on "from distutils.msvccompiler import MSVCCompiler, get_build_architecture"

### ISSUE THREAD

**Issue by illume** [pypa/setuptools#4620]
### setuptools version

setuptools==74.0.0

### Python version

3.13.0-rc

### OS

windows

### Description

from distutils.msvccompiler import MSVCCompiler, get_build_architecture
ModuleNotFoundError: No module named 'distutils.msvccompiler'

### Expected behavior

It should be there.

### How to Reproduce

from distutils.msvccompiler import MSVCCompiler, get_build_architecture
ModuleNotFoundError: No module named 'distutils.msvccompiler'

### Output

```console
from distutils.msvccompiler import MSVCCompiler, get_build_architecture
ModuleNotFoundError: No module named 'distutils.msvccompiler'
```

**Comment by abravalheri** [comment]
Hi @illume , please note that the `distutils.msvccompiler` module was deprecated 2 years ago: https://github.com/pypa/distutils/commit/c802880bfba39d3072599eef2e0f34568f93e6cd, and it has been issuing a deprecation warning since then.

After 2 years, it has been removed accordingly. So, probably it is worth contacting the package you are trying to install to report the codebase needs maintenance.

**Comment by illume** [comment]
With the python 3.13 release just coming this is breaking stuff at an inopportune moment for python packages trying to release binaries.

Does the code still work? If so, I'd ask to put it in for a few months more? This would reduce the burden on maintainers for python 3.13.


Anyone coming in from internet search... 73.0.1 is the version before it was removed. This command will install that version and allow older pythons to get the most recent supported version as before.
```
python -m pip install "setuptools==73.0.1; python_version >= '3.8'" "setuptools; python_version < '3.8'"
```

In requirements format:
```
setuptools==73.0.1; python_version >= "3.8"
setuptools; python_version < "3.8"
```

**Comment by Doggie52** [comment]
This looks like it's still a problem in 74.1.0 even though it looks like there was an attempt to fix it?

This breaks a ton of stuff on Mac OS X, including `brew install glib` which is a dependency for a lot of packages. Brew's pedantic obsession with always using the latest version means there's no way to force it to stick to 73.0.1, at least not as far as I can see.

**Comment by abravalheri** [comment]
> it looks like there was an attempt to fix it

Hi @Doggie52 , I don't think there was...

74.1 restored `setuptools.msvc.Environmentinfo`, not `distutils.msvccompiler`.

`distutils.msvccompiler` has been deprecated for 2 years before its removal. This means that developers alredy had the time to work on the relevant replacements or contact the `pypa/distutils` repository on github to discuss use cases where replacements were not possible.

After 2 years, the module has been removed accordingly, so the bug is not on setuptools or distutils, but on the projects depending on deprecated functionality. 

Please contact the maintainers of the package you are trying to install, as it looks like the package needs to be modified accordingly.

**Comment by illume** [comment]
Closing this, because I didn't write that title. Please don't reopen it, but make a new one if you want to. Thanks.

**Comment by abravalheri** [comment]
Thanks @illume. I changed the title to reflect the state of the affairs more accurately.

**Comment by ehaliewicz** [comment]
Why was this removed?  What purpose does this serve other than breaking builds for packages that couldn't update in time?

**Comment by dae550** [comment]
> Hi [@illume](https://github.com/illume) , please note that the `distutils.msvccompiler` module was deprecated 2 years ago: [pypa/distutils@c802880](https://github.com/pypa/distutils/commit/c802880bfba39d3072599eef2e0f34568f93e6cd), and it has been issuing a deprecation warning since then.
> 
> After 2 years, it has been removed accordingly. So, probably it is worth contacting the package you are trying to install to report the codebase needs maintenance.

Fuck you
