### ISSUE TITLE
[BUG] No way to specify tool.setuptools.packages.find in a non-fragile way for flat layouts

### ISSUE THREAD

**Issue by vanschelven** [pypa/setuptools#4739]
### setuptools version

setuptools==75.3.0

### Python version

Python 3.11

### OS

Ubuntu

### Description

When using a flat (non-src-based) layout, it is not possible to configure using `pyproject.toml` in a way that doesn't immediately break when a new package is added to the project layout.

i.e. I configure using

```
[tool.setuptools.packages.find]
where = ["."]
include = [
    # ... long, and fragile, list
]

exclude = [
    # This, or similar syntaxes, don't seem to actually work.
    # https://stackoverflow.com/q/75091671/339144
]  # exclude packages matching these glob patterns (empty by default)
```

but if I add a new directory to my project, I must remember to add it to pyproject.toml.

As here: https://stackoverflow.com/questions/79169280/pyproject-toml-config-using-setuptools-with-correct-packages-automatically

### Expected behavior

I expect to have a way that will "just work forever".

### How to Reproduce

.

### Output

.

**Comment by abravalheri** [comment]
Hi @vanschelven please [provide a minimal and complete reproducer](https://stackoverflow.com/help/minimal-reproducible-example) regarding the `BUG` you want to report, otherwise we will not be able to consider this issue.

Regarding the given example, please note that values for the patterns used in https://stackoverflow.com/questions/75091671/pyproject-toml-exclude-some-python-sources-py-from-data-directory are conceptually wrong, for the reason that `setuptools.packages` deals with [Python package names](https://docs.python.org/3/tutorial/modules.html#packages) (i.e. "dotted" strings) not file paths, so that is the reason why your expression does not match. See details in https://setuptools.pypa.io/en/latest/userguide/package_discovery.html.

If you want to exclude the `mypackage/data` folder and anything under it, you should provide the following exclude pattern `exclude = ["mypackage.data", "mypackage.data.*"]`[^1].

The pattern `mypackage*data*py` is implying that you have `py` as part of the package name, which does not seem to be the case. Also note that [`packages`](https://docs.python.org/3/tutorial/modules.html#packages) in Python are collections of [modules](https://docs.python.org/3/tutorial/modules.html) (i.e. they map into ***directories***, while `modules` map into files), so you cannot use `exclude` for files specifically... The original pattern would match something like `mypackage/data/py/file.py`.


---

Now regarding the criticism about the methodology not being convenient for your use case, that is a fair comment. But setuptools understands that it is simply impossible to foresee and accommodate ALL the possible scenarios. Instead it offers the ultimate flexibility for all users that have a particular scenario in mind: you can implement your own discovery algorithm by using `setup.py` (note that you can keep most of your configuration in `pyproject.toml` and only define `setup(packages=[...])` in `setup.py`.

So, ultimately, you have tree choices

- You can choose convention over configuration and adequate your source layout to work with setuptools built-in automatic discovery.
- You can use some lightweight configuration in `pyproject.toml` using `include/exclude`.
- If that still don't work for you then, you can still implement your own algorithm in `setup.py`.

[^1]: Please also set `include-package-data = false` for now to avoid problems (see https://github.com/pypa/setuptools/issues/3260).

**Comment by vanschelven** [comment]
> You can choose convention over configuration and adequate your source layout to work with setuptools built-in automatic discovery.

Are you saying that `src`-based layouts is the convention that `setuptools` supports, and that flat layouts are not really supported anymore?

====

Re the `exclude` syntax/semantics, I now understand that at least 3 things come together here

* The above-mentioned confusion about filenames v.s. dotted paths.
* My desire to exclude _modules_ rather than packages is not supported. (not mentioned above, still a thing though)
* `include_package_data` must be false for `exclude` to work at all; this is blocking b/c I need `include_package_data` to be true in my setup.

My take-away is: I can't really use `exclude` to avoid the fragility.

I don't remember what pushed me to using a `pyproject.toml`-based setup in the first place, other than that it was prompted by some message in my toolchain warning about lack of support for a pure `setup.py` based approach. Given that I am on the `pyproject.toml` based setup now, what is the way to configure my own finder in that setup? Just putting a callable in setup.py is no longer possible, after all.

**Comment by abravalheri** [comment]
> Are you saying that src-based layouts is the convention that setuptools supports, and that flat layouts are not really supported anymore?

No. Setuptools supports both src and flat layouts. What is not supported is something more customised (like having Python files in the source three inside valid bavkages, but that need not be considered during packaging).

At the stage that you need something more custom-made and less general, it might be better to implement your own logic (or simply revert to a layout that is already supported, for example for moving the modules that should not be packaged outside of the package tree in a separated directory that can then be excluded).



> it was prompted by some message in my toolchain warning about lack of support for a pure setup.py based approach.

Setuptools issues warning prompting the users to not run CLI commands via `python setup.py ...`. The CLI features of `setup.py` are deprecated. But the file is still a perfectly fine configuration file, and it can be mixed and matched with `pyproject.toml` (given the `dynamic` fields in `pyproject.toml` are configured accordingly with PEP 517).


> Given that I am on the pyproject.toml based setup now, what is the way to configure my own finder in that setup? Just putting a callable in setup.py is no longer possible, after all.

You can have both `pyproject.toml` and `setup.py` at the same time in the project, and use a call to `setuptools.setup(...)` to only pass the dynamic bits. But to be honest, moving the Python files outside of the package tree into a different directory is easier.

**Comment by vanschelven** [comment]
My path forward is (somewhat) clear; this is not a bug, I'll close
