### ISSUE TITLE
ValueError: A 0.7-series setuptools cannot be installed with distribute [But we're on 20.7 now]

### ISSUE THREAD

**Issue by adowds** [pypa/setuptools#543]
When running buildouts bootstrap.py, setuptools generates the error below. This version is 20.7. It looks as if a regex meant to screen for version 0.7 is triggering an error for version 20.7?  This is breaking all builds, please help.

ValueError: A 0.7-series setuptools cannot be installed with distribute. Found one at /tmp/tmpIFxckv/setuptools-20.7.0-py2.7.egg
Traceback (most recent call last):
  File "bootstrap.py", line 172, in <module>
    "Failed to execute command:\n%s" % repr(cmd)[1:-1])
Exception: Failed to execute command:
'/var/lib/jenkins/jobs//job1/workspace/bin/python', '-c', 'from setuptools.command.easy_install import main; main()', '-mZqNxd', '/tmp/tmpIFxckv', 'zc.buildout==2.5.1'

**Comment by kzw** [comment]
Confirmed.  We have to hack up `gevent-psycopg2` to not use `distribute_setuptools` and had to upgrade `pycassa`.  `gevent-psycopg2` is unmaintained and we happen to be using it and our fault.

Can we release quickly 20.8.0 just to avoid this problem for the community?  And also have a safeguard to never release any version that will have '0.7' in the version string?

**Comment by jaraco** [comment]
oh, that's terrible! Yes.

**Comment by boegel** [comment]
So, wait, let me get this right... This problem was fixed by simply bumping the setuptools version from 20.7.0 to 20.8.0, and pretending this will never be hit again?

I understand you can't fix all setuptools versions out there that have this hard check on '`0.7`' in the version string, but at least you can put something in place to make sure you don't reintroduce this issue later?
