### ISSUE TITLE
Wrong error caught in RegistryInfo.lookup

### ISSUE THREAD

**Issue by shortenda** [pypa/setuptools#646]
Hello,

I believe that [RegistryInfo.lookup](https://github.com/pypa/setuptools/blob/master/setuptools/msvc.py#L433) should be except'ing WindowsError instead of IOError when it calls [open key](https://docs.python.org/2/library/_winreg.html#_winreg.OpenKey)

I ran into this issue trying to install a package. Sorry if this isn't correct as I'm not familiar with this project.

Thanks,
David

**Comment by jaraco** [comment]
What's the benefit of catching WindowsError instead of IOError? I see that WindowsError is a subclass of OSError, of which IOError is also a subclass on Python 3 (but apparently not Python 2).

What issue did you encounter? Is it possible there are conditions where a WindowsError might be raised, so perhaps multiple exceptions should be caught?

**Comment by shortenda** [comment]
OpenKey throws a WindowsError if the registry key it's looking for can't be found in python2. So in python2, where WindowsError is distinct from and not a subclass of IOError, a lookup attempt on a missing registry key is not caught and crashes setuptools. In my case a missing visual studio registry key was stopping the install, whereas the intention was to fall back to a default.

It actually seems like it would be most prudent to catch EnvironmentError, apparently this is what winreg.OpenKey throws in python3 and would also catch WindowsError in python2.

**Comment by jaraco** [comment]
@JGoutin Would you be willing to review? Do you concur with shortenda's analysis?

**Comment by JGoutin** [comment]
On Python 3, if `OpenKey` don't found the key a `FileNotFoundError` is raised (subclass of `IOError`, `FileNotFoundError`  is not available on Python 2). But, indeed, like wrote in the doc, this function may also raise `WindowsError` (On Python 2)  or `OSError` (On Python 3).

`IOError` have been merged in `OSError` only since Python 3.3.

So, to cover all case, we need to except `OSError` and `IOError`.
