### ISSUE TITLE
Deprecate and remove 'Features'

### ISSUE THREAD

**Issue by ghost** [pypa/setuptools#65]
Originally reported by: **jaraco (Bitbucket: [jaraco](http://bitbucket.org/jaraco), GitHub: [jaraco](http://github.com/jaraco))**

---

In #58, it comes to my attention that the Features implementation is incomplete and should be removed.

---
- Bitbucket: https://bitbucket.org/pypa/setuptools/issue/65

**Comment by jaraco** [comment]
Quickly reviewing the aforementioned projects:

- SQLAlchemy dropped the dependency on this feature in 2015
- Markupsafe no longer uses the feature.
- [Pyprotocols still uses it](https://github.com/OnShift/PyProtocols/blob/master/setup.py) but only because it hasn't changed since 2014.
- cffi is no longer using the feature (though I can't tell where it stopped)
- [Pymongo dropped it in 2014](https://github.com/mongodb/mongo-python-driver/commit/29db2e94d84971259b5dfb5dff55dd1b78e7b2f4#diff-2eeaed663bd0d25b7e608891384b7298).

Given the deprecation warning has been loud and obnoxious for half a decade, it's time to remove the functionality.

**Comment by jaraco** [comment]
It looks like `zope.interface` referenced above still relies on this feature. I'm going to ping that ticket and let them know about the impending breakage.
