### ISSUE TITLE
zipfile.BadZipfile: File is not a zip file

### ISSUE THREAD

**Issue by Cykooz** [pypa/setuptools#658]
https://github.com/pypa/setuptools/issues/599 - same error with version 24.0.3

**Comment by lukasgraf** [comment]
Same here (buildout user). This is getting *really* old.

**Comment by jaraco** [comment]
In #589, you can see where I adapted the release process to use pypi.io instead of pypi.python.org to avoid the Internal Server Error.

Looking at the [build where the upload was made](https://travis-ci.org/pypa/setuptools/jobs/144650493), it seems to have successfully uploaded the zip file, so I suspect that although the error message is the same, the underlying cause is different.

**Comment by jaraco** [comment]
Looking at [the PyPI site](https://pypi.python.org/pypi/setuptools/24.0.3), all three files of the release appear there:

![screen shot 2016-07-18 at 08 48 36](https://cloud.githubusercontent.com/assets/308610/16915201/7213985c-4cc4-11e6-923e-74f7b523858a.png)

**Comment by jaraco** [comment]
I furthermore downloaded and extracted [the zip file](https://pypi.python.org/packages/fe/d1/19813ec0d7966829b0f3fb2a975706e19c475251142e683d7a15660b180c/setuptools-24.0.3.zip#md5=2bfee18ad4305bbacb0cdb452bc5153d) without errors.

**Comment by jaraco** [comment]
I also just ran ez_setup.py and it worked just fine.

```
$ python ez_setup.py 
Downloading https://pypi.io/packages/source/s/setuptools/setuptools-24.0.3.zip
Extracting in /var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/tmpe8cl9k_3
...
Installed /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/setuptools-24.0.3-py3.5.egg
Processing dependencies for setuptools==24.0.3
Finished processing dependencies for setuptools==24.0.3
```

So it seems whatever the error was, it was transient, and probably an issue with PyPI itself.

I'm open to suggestions, but I don't see there's anything that Setuptools could have done differently.

**Comment by lukasgraf** [comment]
@jaraco I remember from an earlier occurence where I debugged this in some more detail, that when I got `zipfile.BadZipfile: File is not a zip file` it was due to one of the mirrors of a CDN returning some XML message from an Amazon S3 bucket that was basically saying 404 - file not found - but with a non-404 HTTP status code.

That XML then got saved as the setuptools ZIP file, resulting in that error.

IIRC only certain IP addresses / backends were affected: Downloading the same URL using `curl` or `wget` on my local machine, my co workers' machines and our CI server resulted in different behavior, depending on how the hostname was resolved.

I wasn't able to reproduce / confirm this today, just thought I'd mention it because it might be helpful in the future.
