### ISSUE TITLE
Setuptools doesn't play nice with Numpy

### ISSUE THREAD

**Issue by bcbrown** [pypa/setuptools#752]
See: https://github.com/numpy/numpy/blob/master/numpy/distutils/extension.py#L42-L52

That functionality was broken by:
https://github.com/pypa/setuptools/blob/master/setuptools/extension.py#L39-L41

In this pr: https://github.com/pypa/setuptools/pull/718

Here's the the pdb session where I debugged this:
```
(Pdb) old_Extension.__module__
'setuptools.extension'
```

**Comment by tlandschoff-scale** [comment]
Oops, I just sunk some time because of this and (wrongly) traced it to #728. Only after creating a simple travis build to illustrate this did I think about looking at the newest issues.

Currently it seems impossible to install numpy from source on a Unix system, as this build illustrates:

[![Build Status](https://travis-ci.org/tlandschoff-scale/setup-numpy-test.svg?branch=master)](https://travis-ci.org/tlandschoff-scale/setup-numpy-test)

It seems like @bcbrown is correct about the location of this problem.

**Comment by tlandschoff-scale** [comment]
I made pull request #753 for this, not sure why it is not picked up automatically.

**Comment by jaraco** [comment]
Can I also recommend that numpy only pass keyword arguments to `Extension` (for future simplicity)?

**Comment by tlandschoff-scale** [comment]
I think this is a good case for [PEP 3102 keyword only arguments](https://www.python.org/dev/peps/pep-3102/). Unfortunately they are available only starting with CPython 3. One of the great improvements - in my eyes the API should define if parameters should be passed positional or via keyword to ease backwards compatibility.

I think the best that setuptools can do is to generate a warning when positional arguments are used for the keyword parameters of Extension. Probably my company is not the only Python user that partially has obsolete libraries in use (be it for updates to a legacy branch of the software) but try to use the newest setuptools and pip packages for installing them...

**Comment by jaraco** [comment]
> I think this is a good case for PEP 3102 keyword only arguments.

I had the same thought (and same conclusions).

> I think the best that setuptools can do is to generate a warning when positional arguments are used for the keyword parameters of Extension.

Seems a good idea.
