### ISSUE TITLE
Setuptools v27 ignores the .pypirc file

### ISSUE THREAD

**Issue by nait-aul** [pypa/setuptools#785]
I've got in the `~/.pypirc` the following statements:

```
[pypi]
repository = https://pypi.python.org/pypi
...
```

and if I run a command `python setup.py register` with the latest setuptools version 27.1.2, I'll see:

```
Registering my_package_name to https://upload.pypi.org/legacy/  # <-- NOTE the difference 
Server response (410): This API is no longer supported, instead simply upload the file.
```

\+ traceback (I used an `--show-response` option):

```
Traceback (most recent call last):
  File "setup.py", line 13, in <module>
    include_package_data=True
  File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/nait-aul/.virtualenvs/mkdocs-doksit_env/lib/python3.5/site-packages/setuptools/command/register.py", line 10, in run
    orig.register.run(self)
  File "/usr/lib/python3.5/distutils/command/register.py", line 56, in run
    self.send_metadata()
  File "/usr/lib/python3.5/distutils/command/register.py", line 166, in send_metadata
    auth)
  File "/usr/lib/python3.5/distutils/command/register.py", line 302, in post_to_server
    msg = '\n'.join(('-' * 75, data, '-' * 75))
TypeError: sequence item 1: expected str instance, bytes found
```

In the previous version (26.y.z) it worked as expected (registering to https://pypi.python.org/pypi, not https://upload.pypi.org/legacy/), so I had to downgrade the `setuptools`.

**Comment by jaraco** [comment]
On one hand, that error message is expected if the pypi.org URL is being used.

On the other hand, I would have expected because `[pypi]` specifies the old location that it should still work.

**Comment by jaraco** [comment]
The issue here is that the meaning of `pypi` has changed to point to the new host. Simply setting a repository in the `[pypi]` section was never intended to override the default repository setting.

I recommend you adapt your project no longer to use the register command and simply to upload the package to the new PyPI.

If you must continue to use the old PyPI, you may do so by customizing your dev environment and projects to support the old pypi. For example in `.pypirc`:

```
[oldpypi]
repository=https://pypi.python.org/pypi
...
```

And in each project's setup.cfg:

```
[register]
repository=oldpypi
```

However, I recommend instead just using the latest setuptools and reconfiguring your projects not to register.
