### ISSUE TITLE
Doctest's testmod not run correctly when called from command line application

### ISSUE THREAD

**Issue by con-f-use** [pypa/setuptools#788]
Using the files `mymodule.py` and `setup.py` from this gist: https://gist.github.com/con-f-use/bac4c22e019497ab7380d05297bbc748

When run as shell script, doctest works as expected:

```
confus@confusion:/tmp/mymodule$ ./mymodule.py --test
File "./mymodule.py", line 13, in __main__.to_be_tested
Failed example:
    to_be_tested()
Expected:
    2
Got:
    1
**********************************************************************
1 items had failures:
   1 of   1 in __main__.to_be_tested
1 tests in 3 items.
0 passed and 1 failed.
***Test Failed*** 1 failures.
```

When run as command line application, installed by setuptools, the test for `to_be_tested()` is ignored:

```
confus@confusion:/tmp/mymodule$ ./setup.py install --user
confus@confusion:/tmp/mymodule$ mymoduleapp --test
1 items had no tests:
    __main__
0 tests in 1 items.
0 passed and 0 failed.
Test passed.
```

Used python version: Python 2.7.12 (setuptools 20.7.0), but seems a problem with recent versions, too.

**Comment by jaraco** [comment]
Looking at the code for `doctest.testmod()`, we see that the module to be tested is resolved using `sys.modules['__main__']`. Because the entry point was used to launch the script, `__main__` is the setuptools script and not mymodule. I don't think there's anything that setuptools can or should do about this condition, though if you can, please suggest it.

One possible workaround is to invoke your script with `-m`:

```
python -m  mymodule --test
```

Or alternately, invoke testmod with an explicit reference to the current module:

```
def main():
    mod = sys.modules[__name__]
    doctest.testmod(mod)
```
