### ISSUE TITLE
setuptools error when embbeding it into a frozen executable

### ISSUE THREAD

**Issue by nicoddemus** [pypa/setuptools#841]
Hi,

We distribute our applications in Windows and Linux using [cx-freeze](https://bitbucket.org/anthony_tuininga/cx_freeze).

Recently we upgraded `mock` from `1.0.1` to `1.4.0`, and one of the significant changes package-wise is that `mock` now [uses setuptools to determine its `__version__` attribute](https://github.com/testing-cabal/mock/commit/e795a4a240df0039bca711999ec57f7856189547).

Packaging `setuptools` inside a frozen application poses a problem though: this code from [`setuptools.sandbox`](https://github.com/pypa/setuptools/blob/master/setuptools/sandbox.py#L376) fails with an `AssertionError`:

```python
try:
    from win32com.client.gencache import GetGeneratePath
    _EXCEPTIONS.append(GetGeneratePath())
    del GetGeneratePath
except ImportError:
    # it appears pywin32 is not installed, so no need to exclude.
    pass
```

The problem is that `GetGeneratePath()` fails with an `AssertionError` when called from a frozen application because the module is on a read-only store (the zipfile with all python modules):

```python
def GetGeneratePath():
    """..."""
    assert not is_readonly, "Why do you want the genpath for a readonly store?"
```

As a workaround which seems to work for us, we *monkeypatched* `win32com.client.gencache.GetGeneratePath` to always raise an `ImportError` when the application is frozen so the error is handled by `setuptools.sandbox`, but I'm not sure if there are any ramifications that we are not seeing of that.

Any thoughts or advice on this issue would be really appreciated.

**Comment by jaraco** [comment]
It'd be nice if Setuptools weren't having to consider the implementation details of certain packages like this. Tracing the blame history, I find this behavior was committed in 2cb36ad983, referencing [distribute 118](https://bitbucket.org/tarek/distribute/issues/118/sandboxviolation-generating-com-wrappers).

**Comment by jaraco** [comment]
Looking at that original issue, I see that the WMI package has a setup.py with `import wmi` at the top level (in order to grab the `__version__` from that package)... and that's probably the behavior that was triggering the generation of caches at install time. I'd like to consider dropping support for that anti-pattern.

Looking at the latest WMI, it no longer imports wmi but instead does the following:

```
#
# Slight hack to avoid importing the module
# when setup is run
#
version = re.search (r'__version__ = "([a-z0-9\.]+)"', open ("wmi.py").read ()).group (1)
```

Although hacky, this approach is preferable to invoking behavior in dependencies, especially behavior that might write outside the sandbox.

Since the latest version of WMI, released 5 years ago already works around the issue, let's drop support for win32com generating interfaces during the install step.

**Comment by nicoddemus** [comment]
Thanks @jaraco!
