### ISSUE TITLE
Since setuptools 28.5.0, a "global-exclude .pyc" no longer matches .pyc files

### ISSUE THREAD

**Issue by rbarrois** [pypa/setuptools#849]
Since commit bb45468d27615c2ce9f9c9757a367c44d6ee80d2, if a project's MANIFEST.in contains ``global-exclude .py[co]``, the archive generated with ``python setup.py sdist`` will still contain all ``.pyc`` / ``.pyo`` files.

The test below shows that this line worked in setuptools 28.4.0, and broke in setuptools 28.5.0.

I'm not sure whether this can be considered a bug: the previous implementation looked up patterns without any anchoring, whereas the new one forces users to explicitly include wildcards in their ``MANIFEST.in``.
However, I think this change should have been mentioned in the version Changelog.

```patch
diff --cc setuptools/tests/test_manifest.py
index 6360270,ef4beda..0000000
--- a/setuptools/tests/test_manifest.py
+++ b/setuptools/tests/test_manifest.py
@@@ -425,12 -464,22 +425,19 @@@ class TestFileListTest(TempDirTestCase)
          assert file_list.files == ['b.txt']
          self.assertWarnings()
  
+         file_list = FileList()
+         file_list.files = ['a.py', 'b.txt', l('d/c.pyc'), 'e.pyo']
+         file_list.process_template_line('global-exclude .py[co]')
+         file_list.sort()
+         assert file_list.files == ['a.py', 'b.txt']
+         self.assertNoWarnings()
+ 
          # recursive-include
  ```

**Comment by jaraco** [comment]
I agree this looks like an unintentional regression.

**Comment by jaraco** [comment]
According to the changelog, #764 is implicated in this change. Since the unit tests didn't capture this behavior before, it's no surprise that it was missed during the re-write.

@timheap How difficult would it be to restore this expectation?

**Comment by timheap** [comment]
@jaraco It is simple to restore this behaviour for `global-include` and `global-exclude`. I've done so over in #853. Sorry for breaking your build, @rbarrois!

However, I will argue that the old behaviour is unexpected and not desired. In my opinion, a note in the Changelog about this breaking change should be included, rather than restoring the old behaviour. The new behaviour behaves much more like globbing does in other environments (e.g. a bash shell), and is less surprising. With the old behaviour, a pattern like `global-exclude bar.py` would exclude `bar.py`, but also surprisingly `foo_bar.py`, and there is no simple way of stopping this from happening. Under the new behaviour, `global-exclude bar.py` would only exclude `bar.py`, and not `foo_bar.py`. @rbarrois has already found the simple work around to restore the old behaviour by explicitly globbing the match like `global-exclude *.py[co]`.

**Comment by rbarrois** [comment]
@timheap thanks! I do agree with you: I wouldn't consider "properly anchoring patterns" as a bug, but rather as a proper bugfix. I'm totally in favor of keeping the fixed behavior, and simply documenting "a longstanding bug has been fixed in passing while cleaning up this code — please fix your manifests.".
