### ISSUE TITLE
Namespace package breaks module imports 

### ISSUE THREAD

**Issue by matham** [pypa/setuptools#895]
Here's a simple example to reproduce the problem. In https://github.com/matham/pip-nspace-broken there's a `farm` package as well as a `farm.deps.glew` meant to share a namespace with the `farm` package.

Also included are the wheels built with it. After installing the wheels with pip, I get the following:

```py
$ python
Python 3.4.4 (v3.4.4:737efcadf5a6, Dec 20 2015, 20:20:57) [MSC v.1600 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from farm import my_name
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'my_name'
```

If I remove `farm.deps.glew` I get the following:

```py
$ python
Python 3.4.4 (v3.4.4:737efcadf5a6, Dec 20 2015, 20:20:57) [MSC v.1600 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from farm import my_name
Imported farm
```

This is with `pip 9.0.1`.

So basically, having a namespace package seems to break the main package.

**Comment by jaraco** [comment]
I think the problem here is a misunderstanding of the purpose or function of namespace packages. You can't have a package that acts as a simple package (as the farm distribution does) but also acts as a namespace package (as the farm.deps.glew distribution does).

If you would like for `farm` to be a namespace package, you should (a) include the same `declare_namespace` in `farm/__init__.py` for every distribution, (b) declare `farm` as a namespace package in setup.py for every distribution, and (c) not put any functionality in `farm/__init__.py` as it will not be guaranteed to run and is likely not to run.

**Comment by matham** [comment]
Ok, I may have misunderstood about this then. First to clarify, the purpose is not for farm itself to be a "namespace" package, rather that the packages in `farm.deps.xxx` be namespace packages. I.e. that we can install various `farm.deps.xxx` packages separately. I assumed that the intermediate `__init__` in `farm`  would function as normal. So I guess that's not the case and if a subpackage is a namespace all intermediate packages are also namespaces and my approach will not work?

**Comment by jaraco** [comment]
That's right. All parents of a namespace package must also be namespace packages, as they will necessarily share that parent name space (farm and farm.deps in this example).

**Comment by jaraco** [comment]
@jerryz1982, I think [the openstack issue](https://bugs.launchpad.net/devstack/+bug/1651292) is the same as the one here. Behavior in a namespace package cannot be expected to run. @ncoghlan do you have any recommendations in this regard?

**Comment by matham** [comment]
What I ended up doing, which again my not be officially supported, is dropped any namespace reference and removed all the intermediate `__init__` from `farm.deps.glew`. So that the only contents in that package was:

```
farm.deps.glew/
    setup.py
    farm/
        deps/
            glew/
                __init__.py
                stuff
```

With the `setup.py` declaring the only package `farm.deps.glew` with the same name. And of course the main farm package remained the same. This created wheels and installed as (I) expected the `farm.deps.glew` package.

This only works because the `farm.deps.glew` package is installed to the `farm` package. But it'd be nice to know if this is also only a hack or if it's expected to work. For what it's worth, some random person on stackoverflow also suggested that this would work (https://stackoverflow.com/questions/23698712/python-install-package-as-sub-package-of-another-package).

Not sure if this would also work for openstack.

**Comment by jaraco** [comment]
@matham: That may work in some scenarios, but will probably not work in cases where `farm` and `farm.deps.glew` are not installed to the same location (i.e. one is installed in system site packages and the other in user site packages, or one under develop and the other not, or one or more of the packages are installed as an egg). Also, I'm sort-of surprised that `import farm.deps` (or anything below it) works at all on Python prior to 3.3, as there's no module for that package.

**Comment by ncoghlan** [comment]
For this kind of question, it's important to separate two different concepts:

1. Optional submodules, where a given component installs into a shared package module hierarchy. This doesn't require namespace packages at all, it just requires what @matham describes in https://github.com/pypa/setuptools/issues/895#issuecomment-268722067

In 3.3+ and when using `importlib2` that will work standalone (since `__init__.py` files become optional), while in 3.2 and earlier it will require `farm` or `farm.deps` as a dependency that provides the relevant `__init__.py` files.

2. Namespace packages, which allow a package to be split across multiple directories by having more than one entry in `__path__`.

Python 3.3+ treats any directory without an `__init__.py` file as a potential part of a namespace package automatically, while the `declare_namespace` functionality in setuptools lets you request the generation of a boilerplate `__init__.py` that takes care of setting `__path__` appropriately based on a search of `sys.path`.

The fact that these are separate questions means that a non-namespace package may have namespace packages as children, as long as it includes the necessary `__path__` expansion code in its `__init__.py`: https://docs.python.org/3/library/pkgutil.html#pkgutil.extend_path

The trick with doing that is that you don't tell *setuptools* that it is a namespace package, you instead publish it as a normal self-contained package that happens to manipulate its own `__path__` attribute.

However, if all you want is optional submodules, then you don't need to use namespace packages at all - just make the submodules depend on the parent package that they install into, and let the parent package take care of installing the necessary `__init__.py` files.
