### ISSUE TITLE
please continue to provide tarballs for new releases

### ISSUE THREAD

**Issue by doko42** [pypa/setuptools#902]
at least with 32.3.1 there is no source tarball (.tar.gz) anymore. Most Linux distributions support building using a tarball provided by upstream, but this is not the case for .zip files. While the zip file can be converted, it doesn't allow verification of the sources distributed by a distributor and upstream.

**Comment by jaraco** [comment]
PyPI no longer supports hosting of zip and tar.gz sdists per [PEP 527](https://www.python.org/dev/peps/pep-0527/). See pypa/warehouse#1591. Because `ez_setup.py` in the [bootstrap branch](/pypa/setuptools/tree/bootstrap) relies on it and because .zip files have better platform support (natively recognized by Unix, Windows, Mac), they are the preferable form.

You're welcome to produce your own tarballs from tagged commits, but I don't see any other alternative.

**Comment by carandraug** [comment]
@jaraco  wrote:
> PyPI no longer supports hosting of zip and tar.gz sdists per PEP 527. 

PyPI supports hosting of both zip and tar.gz. That is not an issue. That PEP also does not recommend against tar.gz, quite the opposite. From that PEP abstract:

> In addition, this PEP proposes removing support for [...], and any other extension besides .tar.gz and .zip.

Near the end of the document it roughly ends:

> Finally we get down to .tar.gz and .zip. Looking at the pure numbers for these two, we can see that .tar.gz is by far the most uploaded format, with 444,338 total uploaded compared to .zip's 58,774 
> [...]
>
> Instead of trying to standardize on either .tar.gz or .zip, this PEP proposes that we allow either .tar.gz or .zip for sdists.

So, nothing in that PEP recommends against tar.gz format.
