### ISSUE TITLE
bootstrap script cannot be executed without setuptools already installed

### ISSUE THREAD

**Issue by jjhelmus** [pypa/setuptools#950]
The `bootstrap.py` script cannot be used to bootstrap from an environment without setuptools.  The script imports `pip` which requires setuptools to be be installed.  This behavior was introduced in #933.

**Comment by jaraco** [comment]
Thanks for sharing. Do you think it should do anything differently?

**Comment by jjhelmus** [comment]
In previous versions of `setuptools` (for example 33.1.0) is was possible to use the `bootstrap.py` script to install `setuptools` into an environment which contained only Python (no `pip`, `setuptools`, or `wheel` packages installed).  This behavior was very helpful for downstream distributors who want to create packages of setuptools.  The currently behavior creates a circular dependency (`setuptools` requires `pip` which requires `setuptools`) which makes packaging difficult.  Providing a method to install `setuptools` into a bare Python environment would be very helpful.

My own needs for this is for [conda-forge](http://conda-forge.github.io/).  We create separate conda packages for `python`, `setuptools`, `pip` and `wheel` so that they can be upgraded independently.  Our build order for these packages was `python`, `setuptools`, `wheel` and then `pip`.  The new requirements on `pip` to install `setuptools` is causing some issues with this build order.

**Comment by jaraco** [comment]
I see. The issue is that Setuptools is seeking specifically to reverse that dependency. The responsibility for installing packages is being delegated to pip, and that's a more fundamental responsibility than that of building packages, for which setuptools will play a key role.

In that sense, I'd recommend you build packages in this order - `python`, `pip`, `wheel`, `setuptools` (or maybe setuptools before wheel).

Strictly speaking, pip doesn't depend on setuptools. Setuptools is required to build some packages (from source), but not for installing wheels. Setuptools is an optional dependency.

Is it possible with this different perspective that conda-forge can be adapted to work in this new model?

Alternatively, conda-forge could be responsible for retrieving build dependencies and bootstrapping the project. If it makes sense to separate the two responsibilities that `bootstrap.py` is performing, that would be possible.

**Comment by jjhelmus** [comment]
Thanks for the explanation.  I think I understand the rational behind the change and agree that it is a good step forward.  

The issue that I think conda-forge and other re-packagers may have is that pip uses setuptools to install itself. Although setuptools does not seem to be required at run-time many include it as a pip dependency.

I believe that separating the two tasks in the `bootstrap.py` script, retrieving build dependencies and bootstrapping the project, would make is easier for various projects, including conda-forge, to package setuptools.  In conda-forge we have other means to provide the build dependencies and an method to opt-out of pip providing these would be helpful.  I can put together a PR with a possible implementation if it would help.

**Comment by jaraco** [comment]
Yes, that would be helpful and most appreciated.

**Comment by jjhelmus** [comment]
Added an optional flag to the `bootstrap.py` script in PR #958 which when specified skips the installation of dependencies using pip.  This should solve the issue for re-packagers who are using other tools to install these dependencies.
