### ISSUE TITLE
please implement PEP 503

### ISSUE THREAD

**Issue by Niedes** [pypa/setuptools#991]
as specified in [python.org/dev/peps](https://www.python.org/dev/peps/pep-0503/#normalized-names).
We are using nexus to deploy our inhouse packages but they can't be found because nexus already implemented PEP 503.
So when e.g. the python pakage name is `my.pkg` after twine (or setup.py sdist) upload it appears as `my-pkg` in the nexus index and buildout fails (`Error: Couldn't find a distribution for 'my.pkg==1.0a1'`).
The Error occurs in 

> def find_packages(self, requirement):
>    ...
>    for url in list(self.package_pages.get(requirement.key, ())):
>             # scan each page that might be related to the desired package
>             self.scan_url(url)

and currently we have to patch around with `self.scan_url(url.replace('my.', 'my-'))`

Please see related topics at [https://github.com/pypa/pip/issues/3666](https://github.com/pypa/pip/issues/3666) and [https://issues.sonatype.org/browse/NEXUS-12501](https://issues.sonatype.org/browse/NEXUS-12501)

**Comment by NicolasGoeddel** [comment]
Anything new here? We can not make a buildout because our customer uses Nexus as an egg proxy.

**Comment by abravalheri** [comment]
Hi @Niedes and @NicolasGoeddel thank you very much for bringing this issue up.
I am sorry no maintainer had the time to come back to you before.

Since `easy_install` is currently [deprecated](https://setuptools.pypa.io/en/latest/history.html#v58-3-0) and setuptools are now supposed to be used together with a proper PEP 517 build backend, I think there is not much left to be done here, right? So I will close this issue right now, but please let me know if I am understanding something wrong...
