### ISSUE TITLE
Option 'python_requires' is not supported in configuration files

### ISSUE THREAD

**Issue by ma-ba** [pypa/setuptools#999]
The option `python_requires` is not supported when metadata / options are loaded from `setup.cfg` via #862.

On a side note: Is it intended behavior that those package specific metadata / options may be given in all configuration files given by `distutils.core.Distribution.find_config_files` (i.e. including the user's `.pydistutils.cfg`, which is not specific to the package)?

**Comment by jaraco** [comment]
It's probably a design flaw that these option definitions need to be defined in two places, but that's what we've got. Would you consider creating a PR to address the missing option?

> Is it intended behavior that those package specific metadata / options may be given in all configuration files?

That does seem like a defect, but perhaps ignorable. I can see how one might want to define the 'author' or 'maintainer' as users settings, though that does have some nasty implications around replicable builds. I don't think it was intentional that these other files are honored for these settings.

**Comment by ma-ba** [comment]
PR #1007 created.
Thanks for answering the question! I presumed this might be the case -- so let's just hope nobody does something that foolish to their `.pydistutils.cfg` 😄.
